### ISSUE TITLE
Add support for Sulion Ceiling Fan

### ISSUE THREAD

**Issue by ermitovski** [0x5e/homebridge-tuya-platform#106]
Hi, could you add support for this ceiling fan light?
In the current status:
- The fan can be started and change the speed but it can't be turned off
- The light can't be turned on or off but the brightness can be changed

Thanks for all the work you're doing with the plugin!!

Message from the log
`[11/20/2022, 4:27:45 PM] [TuyaPlatform] [SULION CEILING FAN] Missing one of the required schema: [ 'switch_fan', 'fan_switch', 'switch' ]`
...
`[11/20/2022, 4:27:45 PM] [TuyaPlatform] Unsupported device: SULION CEILING FAN.`

**Device info**
```json
  {
    "active_time": 1654457114,
    "biz_type": 0,
    "category": "fsd",
    "create_time": 1654457114,
    "icon": "smart/icon/ay1532925738261sot2B/c95fb2f886008e4eceac207077a60f56.png",
    "id": "bfbca6414142d0e86314eo",
    "ip": "X",
    "lat": "X",
    "local_key": "X",
    "lon": "X",
    "model": "Fungo",
    "name": "SULION CEILING FAN",
    "online": true,
    "owner_id": "X",
    "product_id": "llucuqpf8e2zdogu",
    "product_name": "Sulion Ceiling Fan ",
    "status": [
      {
        "code": "bright_value",
        "value": 10
      },
      {
        "code": "temp_value",
        "value": 0
      },
      {
        "code": "fan_speed",
        "value": 1
      },
      {
        "code": "fan_direction",
        "value": "forward"
      },
      {
        "code": "countdown_left_fan",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "+02:00",
    "uid": "X",
    "update_time": 1655533095,
    "uuid": "X",
    "schema": [
      {
        "code": "bright_value",
        "mode": "rw",
        "type": "Integer",
        "property": {
          "min": 10,
          "max": 1000,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "temp_value",
        "mode": "rw",
        "type": "Integer",
        "property": {
          "min": 0,
          "max": 1000,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "fan_speed",
        "mode": "rw",
        "type": "Integer",
        "property": {
          "unit": "",
          "min": 1,
          "max": 6,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "fan_direction",
        "mode": "rw",
        "type": "Enum",
        "property": {
          "range": [
            "forward",
            "reverse"
          ]
        }
      },
      {
        "code": "countdown_left_fan",
        "mode": "rw",
        "type": "Integer",
        "property": {
          "unit": "min",
          "min": 0,
          "max": 540,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "control_data",
        "mode": "wo",
        "type": "String",
        "property": {
          "maxlen": 255
        }
      }
    ]
  },
 ```

**Comment by 0x5e** [comment]
Your device seems missing two schema about the "fan switch" and "light switch", so the plugin is not working. That's because by default Tuya API will hide the non-standard schema.

Recently it can be unhided in the tuya platform. You can  find "Change Control Instruction Mode" of your device, switch to "DP Instruction" and then it shows. The entrance is difficult to describe, please see the photos below.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5144674/202912963-d9830738-6935-4c85-9791-d0a0abaa5e6b.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/5144674/202912793-242e7412-2925-4cb8-9e78-da7fb1f66f7c.png">

However unhide is not enough, there's still some works to do about the plugin, I will add a plugin config to allow users remap their "non-standard schema" into "standard schema", please wait the 1.7.0 version.

**Comment by 0x5e** [comment]
I open a new issue, this one will be closed.
#111

**Comment by ermitovski** [comment]
Hi! I managed to change to "DP Instruction" and now everything works! 
The message in the log about being unsupported disappeared and I can turn on and off the lights and the fan :D 
⚠️  If it helps to other people, the change of Control Instruction Mode took some hours for me. Be patient :D

**Comment by 0x5e** [comment]
Congratulations :) but I think not 100% device can works only switching mode, you are lucky that your "non-standard" device use the same dp code as the "standard" one, that's hard to explain, anyway happy to hear that.
