### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Almansio** [0x5e/homebridge-tuya-platform#108]
![image](https://user-images.githubusercontent.com/103188067/202916047-6ea67565-7193-4457-ace9-dc718ad9296c.png)

Error installing the Homebridge plugin on a raspberry pi.

**Describe the bug**

**Expected behavior**

**Screenshots**

**Device info**
If the issue is related to a device, please refer to the troubleshooting section to get device list info and debug logs. https://github.com/0x5e/homebridge-tuya-platform#troubleshooting

**Comment by 0x5e** [comment]
it looks like a network issue, can you open the npm website correctly in the rpi?

**Comment by 0x5e** [comment]
Update: it looks like network or cache issue, I'm not expert of npm, please try if this can help you.

https://github.com/anseki/vscode-color/issues/111#issuecomment-820287585

**Comment by Almansio** [comment]
Hey!Thanks for your reply. If I install a “random” plugin I have no npm issues and when installing the Tuya plug-in with the command in the terminal it also succeeded, but I don’t know how to configure the plugin in the terminal. Will try the cache clean later. Mac OS RpiHomebridge UIOp 21 nov. 2022 om 04:46 heeft gaosen ***@***.***> het volgende geschreven:﻿
Update: it looks like network or cache issue, I'm not expert of npm, please try if this can help you.
anseki/vscode-color#111 (comment)

**Comment by Almansio** [comment]
Tried it. Same error. :(Op 21 nov. 2022 om 10:00 heeft Almansio Figueiredo Soares ***@***.***> het volgende geschreven:﻿Hey!Thanks for your reply. If I install a “random” plugin I have no npm issues and when installing the Tuya plug-in with the command in the terminal it also succeeded, but I don’t know how to configure the plugin in the terminal. Will try the cache clean later. Mac OS RpiHomebridge UIOp 21 nov. 2022 om 04:46 heeft gaosen ***@***.***> het volgende geschreven:﻿
Update: it looks like network or cache issue, I'm not expert of npm, please try if this can help you.
anseki/vscode-color#111 (comment)

**Comment by Almansio** [comment]
Can you please provide me with a tutorial for installing the plugin by using the terminal? I successfully installed the https://github.com/tuya/tuya-homebridge plugin by following the https://developer.tuya.com/en/docs/iot/Tuya_Homebridge_Plugin?id=Kamcldj76lhzt tutorial. Unfortunately this plugin only adds the option to switch the Stringlight(wifi) on and off in homekit.  
Thanks!

**Comment by Almansio** [comment]
Probably some maintenance, tried the plugin today and the installation worked perfect.
