### ISSUE TITLE
Support for other app schema?

### ISSUE THREAD

**Issue by JackMoseley2001** [0x5e/homebridge-tuya-platform#109]
Hi, thank you for this great looking plugin!

We have all our devices connected via the "Gosund" app, rather than Smart Life or Tuya Smart and wondered if we can connect this app up somehow? I can't seem to find the `appSchema` for the `Godsund` app anywhere (tried just `gosund` and the app id, but got errors back) - is there somewhere specific to find this? Ideally we wouldn't need to reconnect all the devices to a different app if possible 😄 

Thank you.

**Comment by 0x5e** [comment]
I'm not sure if other oem tuya app account can link to the cloud projects, have you tried on tuya platform? If the link step not working then the `appSchema` is not useful.

`appSchema` I think there's two ways of get it:
1. It is a prefix to open the app, for example you open `tuyaSmart://xxxxxx` in the mobile web browser, the Tuya App will be opened. So If you can managed to get the App's package whatever iOS or Android, it can be get from package.
2. If you have the app download page made by tuya, the url `https://developerapp.tuyacn.com/download/test/xxx` like this, then `xxx` is the `appSchema` you need.

**Comment by 0x5e** [comment]
And personally suggest, the TuyaSmart App or SmartLife App is always the newest and have the latest and full features vs Tuya OEM Apps. OEM Apps is meaningful for manufactors to build their brand, but for users I will suggest using TuyaSmart/SmartLife instead :)

**Comment by JackMoseley2001** [comment]
Thank you! We'll look to move over to the Tuya Smart app in that case I think - as we were only on Gosund as some of the first devices we purchased were from that brand, without knowing about Tuya. 

I managed to add an OEM app to the developer console, so that seems to work, but having found the scheme via your message (fyi it seems to be `gosundsmart` which opens the app if downloaded) it sadly doesn't seem to be accepted by the API, so back to the drawing board.

**Comment by 0x5e** [comment]
You are not the owner of gosundsmart so I guess you are not able to use it in you project.

**Comment by JackMoseley2001** [comment]
I do have this inside of my devices (alongside Tuya Smart) but agree that due to not owning the app it likely won't accept it. I'll begin a transfer over to Tuya Smart I think. Thank you for your help!

[image](https://user-images.githubusercontent.com/10659397/203017946-e7c9bbb5-21c7-471d-91d9-21201abd7896.png)
