### ISSUE TITLE
Device not working properly

### ISSUE THREAD

**Issue by 0x5e** [0x5e/homebridge-tuya-platform#111]
If your device is in the support list, but basic function is not working, There maybe one of the two reasons:
1. Your device is a "non-standard" device, it's DP Code need to be mapped.
2. You found a plugin bug, welcome to submit the issue, provide your device detail info and logs.

For the first reason, please do these steps:
- Change the device's control mode:
  - Go to "[Tuya Platform Cloud Development](https://iot.tuya.com/cloud/) -> Your Project -> Devices -> All Devices -> View Devices by Product"
  - Find your device-related product, click the "pencil icon" (Change Control Instruction Mode).
  - <img width="500" alt="image" src="https://user-images.githubusercontent.com/5144674/202967707-8b934e05-36d6-4b42-bb7b-87e5b24474c4.png">
  - The "Table of Instructions" shows the cloud mapping, you can know which DP Codes of your device is missing, you need to manually map them in the plugin config.
  - <img width="500" alt="image" src="https://user-images.githubusercontent.com/5144674/202967528-4838f9a1-0547-4102-afbb-180dc9b198b1.png">

  - Select "DP Instruction" and save.
- Edit the plugin config (this feature will be developed in v1.7.0)
- If your device works perfect after config, please submit a PR, so everyone use the same product can benefit from your contribution。(this feature will be developed in v1.7.0)

The v1.7.0 will be started at early 2023, currently I'm preparing for the exam in 2022.12, don't have too much time to develop. Thanks for your patience.

PS: The standard instruction set documentation of most categories can be found here:
https://developer.tuya.com/en/docs/iot/standarddescription?id=K9i5ql6waswzq

**Comment by GotierLdl** [comment]
Hello, I am waiting for version 1.7.0 impatiently. Great !

**Comment by GotierLdl** [comment]
The update v1.6.0-beta.40 résolve My problem THX !!

**Comment by aayushbhatia06** [comment]
What should one do when their device does not have all the DP codes. Mine has only two out of 8
