### ISSUE TITLE
Thermostat temperature is off by factor of 10, possible fix

### ISSUE THREAD

**Issue by lisanet** [0x5e/homebridge-tuya-platform#112]
The thermostat temperature of a IR heater is off by a factor of 10.

This is the same issue as in the offical plugin, see issue https://github.com/tuya/tuya-homebridge/issues/268

There's a possible fix mentioned in the comments. https://github.com/xlinur/tuya-homebridge/pull/1/files

Maybe you can take a look at it.

**Comment by 0x5e** [comment]
I think its already fixed by #20. Are you still facing this problem?

**Comment by 0x5e** [comment]
And same issue here: https://github.com/0x5e/homebridge-tuya-platform/discussions/2#discussioncomment-3990021

**Comment by 0x5e** [comment]
Please upload logs and reopen the issue if problem still exists.
