### ISSUE TITLE
Plugs appears with two switches

### ISSUE THREAD

**Issue by arturlukosek** [0x5e/homebridge-tuya-platform#113]
Just swapped original plugin with this one and all plug devises seems to appear with two switches in HomeKit.  Left switch don’t change the device state only the right one. Left represent the device type  I have setup earlier like light or fan.  
is there a way to hide one switch?

![2832DF56-9B59-45AA-90F0-2E63C29D8262](https://user-images.githubusercontent.com/53251964/203136927-12225d17-31f0-4613-8797-1a1c7ee1081c.jpeg)

All plugs are the wifi devices from LSC brand.

**Comment by 0x5e** [comment]
It's a cache issue. I will try how to better solving this. or you could clean the single accessory cache in homebridge web gui

**Comment by arturlukosek** [comment]
@0x5e I did try to clean the accessory cache and plug appear with only one switch. There is a minion issue still as the switch that stays is the one with the appendix -1 so in my case I had to rename in and connect the device to scene or automations again. I believe new added plugs will show up without any issue. Thank you for very quick response. I will fix other plugs with steps above.
