### ISSUE TITLE
[Light] Motion Sensor Light (gyd) seen by Homebridge but not working in HomeKit

### ISSUE THREAD

**Issue by mamante** [0x5e/homebridge-tuya-platform#121]
**Describe the bug**
I have [Globe Electric Wi-Fi Smart Ambient Night Light with Motion Detection, No Hub Required, Voice Activated, Multicolor Changing RGB, Tunable White 2000K - 5000K ](https://www.amazon.com/Globe-Electric-50239-Automatic-Changing/dp/B08X72JY3V) that is not behaving as expected. 

This device is recognized as a [Light] Motion Sensor Light (gyd) by Tuya & supported by the current release of your plug-in (v1.6.0). I can fully control the light/PIR via the Tuya Smart app and have also successfully set up the device as an Tuya IOT Cloud Device so it can be used correctly by the plugin.

The issue is that I have gotten it to be recognized by Homebridge [via Tuya IoT Cloud set up) so that it is exposed and visible in HomeKit but when I see in Home app on iOS device, the app states the device is "unsupported" and cannot be controlled at all.

I also also set up a [Globe Electric Wi-Fi Smart Receptacle](https://www.amazon.com/Globe-Electric-Collection-Receptacle-50024/dp/B07VL5R245/?th=1) as well as an [iHome Flow Smart Power Strip ](https://www.amazon.com/iHome-Extension-Individually-Controlled-Activation/dp/B09C6M7YPT)which I have set up via the plug-in and both work flawlessly as expected.

**Expected behavior**
I'm hoping for nearly full control of the Globe Electric Wi-Fi Smart Ambient Night Light via Homekit so I can turn off and on the light, adjust its color settings, as well as be able to enable or disable the PIR sensor as well via Home app automations.

**Screenshots**
![IMG_3EC5E89AF421-1](https://user-images.githubusercontent.com/6117709/204038138-255aa826-d9d5-4db9-ac66-1d8e736b7fec.jpeg)

**Device info**
Here are the debug logs from Homebridge with sensitive data scrubbed:

[11/25/2022, 12:02:48 PM] [TuyaPlatform] [TuyaOpenMQ] Connected
[11/25/2022, 12:02:48 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/homes/XXX/devices
data = {
  "result": [
    {
      "active_time": 1641092331,
      "biz_type": 0,
      "category": "gyd",
      "create_time": 1641092331,
      "icon": "smart/icon/ay15281362075689iOHb/0d83466574b2736d9671bc16b62ced41.png",
      "id": “XXX”,
      "ip": “XXX”,
      "lat": “XXX”,
      "local_key": "XXX”,
      "lon": “XXX”,
      "model": "234232",
      "name": "Night Light",
      "online": true,
      "owner_id": “XXX”,
      "product_id": “XXX”,
      "product_name": "50239",
      "status": [
        {
          "code": "switch_led",
          "value": false
        },
        {
          "code": "work_mode",
          "value": "white"
        },
        {
          "code": "bright_value",
          "value": 1000
        },
        {
          "code": "temp_value",
          "value": 1000
        },
        {
          "code": "colour_data",
          "value": "{\"h\":0,\"s\":1000,\"v\":1000}"
        },
        {
          "code": "countdown",
          "value": 0
        },
        {
          "code": "device_mode",
          "value": "manual"
        },
        {
          "code": "pir_state",
          "value": "none"
        },
        {
          "code": "cds",
          "value": "2000lux"
        },
        {
          "code": "pir_sensitivity",
          "value": "low"
        },
        {
          "code": "pir_delay",
          "value": 5
        },
        {
          "code": "switch_pir",
          "value": true
        },
        {
          "code": "standby_time",
          "value": 1
        },
        {
          "code": "standby_bright",
          "value": 0
        },
        {
          "code": "scene_data",
          "value": "{\"scene_num\":1,\"scene_units\":[{\"bright\":200,\"h\":0,\"s\":0,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":13,\"unit_switch_duration\":14,\"v\":0}]}"
        }
      ],
      "sub": false,
      "time_zone": "-05:00",
      "uid": “XXX”,
      "update_time": 1656359322,
      "uuid": "XXX”
    },
    {
      "active_time": 1652317165,
      "biz_type": 0,
      "category": "cz",
      "create_time": 1641052506,
      "icon": "smart/icon/ay15281362075689iOHb/9ef5079ba2eff676e1e26b28d8848d5f.png",
      "id": “XXX”,
      "ip": “XXX”,
      "lat": “XXX”,
      "local_key": "XXX”,
      "lon": “XXX”,
      "model": "Litesun ",
      "name": "Receptacle",
      "online": true,
      "owner_id": “XXX”,
      "product_id": “XXX”,
      "product_name": "50024",
      "status": [
        {
          "code": "switch_1",
          "value": true
        },
        {
          "code": "countdown_1",
          "value": 0
        }
      ],
      "sub": false,
      "time_zone": "-05:00",
      "uid": “XXX”,
      "update_time": 1656359319,
      "uuid": “XXX”
    },
    {
      "active_time": 1641949912,
      "biz_type": 0,
      "category": "pc",
      "create_time": 1641949912,
      "icon": "smart/icon/ay1480002761059me2zH/c193821efa8b4fb7527c8e68064f5f45.png",
      "id": “XXX”,
      "ip": “XXX”,
      "lat": “XXX”,
      "local_key": “XXX”,
      "lon": "XXX",
      "model": "DR-2180/客户型号：IH-SW007",
      "name": "iHome Power Strip",
      "online": true,
      "owner_id": "XXX",
      "product_id": “XXX”,
      "product_name": "iHome SW007 6 outlet smart surge ",
      "status": [
        {
          "code": "switch_1",
          "value": true
        },
        {
          "code": "switch_2",
          "value": true
        },
        {
          "code": "switch_3",
          "value": true
        },
        {
          "code": "switch_4",
          "value": true
        },
        {
          "code": "switch_5",
          "value": false
        },
        {
          "code": "switch_6",
          "value": true
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "countdown_2",
          "value": 0
        },
        {
          "code": "countdown_3",
          "value": 0
        },
        {
          "code": "countdown_4",
          "value": 0
        },
        {
          "code": "countdown_5",
          "value": 0
        },
        {
          "code": "countdown_6",
          "value": 0
        },
        {
          "code": "relay_status",
          "value": "last"
        },
        {
          "code": "cycle_time",
          "value": ""
        }
      ],
      "sub": false,
      "time_zone": "-05:00",
      "uid": “XXX”,
      "update_time": 1656359317,
      "uuid": “XXX”
    }
  ],
  "success": true,
  "t": XXX,
  "tid": “XXX”
}
[11/25/2022, 12:02:48 PM] [TuyaPlatform] [TuyaOpenAPI] Request:
method = get
endpoint = https://openapi.tuyaus.com
path = /v1.0/devices/eb53284fd1452615e4wxjh/specifications
query = undefined
headers = {
  "t": “XXX”,
  "client_id": “XXX”,
  "nonce": “XXX”,
  "Signature-Headers": "client_id",
  "sign": “XXX”,
  "sign_method": "HMAC-SHA256",
  "access_token": “XXX”,
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.6.0-beta.39"
}
body = null
[11/25/2022, 12:02:48 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/XXX/specifications
data = {
  "result": {
    "category": "gyd",
    "functions": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\"]}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "colour_data",
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "countdown",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "device_mode",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "cds",
        "type": "Enum",
        "values": "{\"range\":[\"2000lux\",\"300lux\",\"50lux\",\"10lux\",\"5lux\",\"now\"]}"
      },
      {
        "code": "pir_sensitivity",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "pir_delay",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":5,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_pir",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "standby_time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":1,\"max\":480,\"scale\":0,\"step\":1}"
      },
      {
        "code": "standby_bright",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "scene_data",
        "type": "Json",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\"]}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "colour_data",
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "countdown",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "device_mode",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "pir_state",
        "type": "Enum",
        "values": "{\"range\":[\"pir\",\"none\"]}"
      },
      {
        "code": "cds",
        "type": "Enum",
        "values": "{\"range\":[\"2000lux\",\"300lux\",\"50lux\",\"10lux\",\"5lux\",\"now\"]}"
      },
      {
        "code": "pir_sensitivity",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "pir_delay",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":5,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_pir",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "standby_time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":1,\"max\":480,\"scale\":0,\"step\":1}"
      },
      {
        "code": "standby_bright",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "scene_data",
        "type": "Json",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": XXX,
  "tid": “XXX”

[11/25/2022, 12:02:49 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/XXX/specifications
data = {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": XXX,
  "tid": “XXX”
}
[11/25/2022, 12:02:49 PM] [TuyaPlatform] [TuyaOpenAPI] Request:
method = get
endpoint = https://openapi.tuyaus.com
path = /v1.0/devices/XXX/specifications
query = undefined
headers = {
  "t": “XXX”,
  "client_id": “XXX”,
  "nonce": "XXX",
  "Signature-Headers": "client_id",
  "sign": "XXX",
  "sign_method": "HMAC-SHA256",
  "access_token": “XXX”,
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.6.0-beta.39"
}

[11/25/2022, 12:02:50 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/eb90e4ef8713e69c372cwj/specifications
data = {
  "result": {
    "category": "pc",
    "functions": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_5",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_6",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_5",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "cycle_time",
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_5",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_6",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_5",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "cycle_time",
        "type": "String",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": XXX,
  "tid": “XXX”
}
[11/25/2022, 12:02:50 PM] [TuyaPlatform] Got 3 device(s).
[11/25/2022, 12:02:50 PM] [TuyaPlatform] Device list saved at /var/lib/homebridge/persist/TuyaDeviceList.XXX.json
[11/25/2022, 12:02:50 PM] [TuyaPlatform] Restoring existing accessory from cache: Night Light
[11/25/2022, 12:02:50 PM] [TuyaPlatform] Restoring existing accessory from cache: Receptacle
[11/25/2022, 12:02:50 PM] [TuyaPlatform] Restoring existing accessory from cache: iHome Power Strip

**Comment by 0x5e** [comment]
Thanks for the information. The resaon is this device has `color_data` but no `h`, `s`, `v` inside, then the plugin treate it as neither color light nor white light. Now it should be working.

**Comment by randymassey** [comment]
I actually, of relevant timing, only just installed one of these motion detecting outdoor flood lights, that also allows for changing the white color temperature of the LEDs. I had tried a plug-in by a different author, that just would not work (there is a proper IOT cloud project built). I found your version of the plug-in, & it’s only been in the last few days that I was testing this, first with an electrical cord before actually installing it onto the house, but after this update today, I can confirm that it is seeing all of the components of the light fixture now, it has the switch for the light, which it always did, you could change the color of the white light which always did work.  But I can confirm that it only saw it as a light bulb and that was it. Now, after this update, there is an on/off toggle switch for the PIR sensor,  as well as the motion sensor itself showing up as a motion sensor & of course the light itself.So that’s fantastic. Everything is working brilliantly. I was ironically just about to sit down in the next day or so and compose a message to you to inquire about this very topic. So for me, the timing at least was quite fortuitous in that I literally only just installed it on the house this very afternoon. At any rate I just wanted to say thank you for your efforts on the update. I also just wanted to give you a confirmation that it absolutely is working. You do have to remove, the occurrence from Apple home and re-add it back in for them to show.I run it as a child bridge for just this one plug-in under homebridge on a raspberry pi 4. So it was very easy to just delete that one child bridge, & as soon as I added it back in, everything showed up as a combined  item properly inside HomeKit. Thanks so much.RandySent from my iPhoneOn Nov 25, 2022, at 9:08 PM, gaosen ***@***.***> wrote:﻿
Closed #121 as completed.

**Comment by randymassey** [comment]
Oh, yes, & my light fixture is also dimmable, so I can confirm that the dimming function is also working….RMSent from my iPhoneOn Nov 25, 2022, at 11:17 PM, Randy Massey ***@***.***> wrote:﻿I actually, of relevant timing, only just installed one of these motion detecting outdoor flood lights, that also allows for changing the white color temperature of the LEDs. I had tried a plug-in by a different author, that just would not work (there is a proper IOT cloud project built). I found your version of the plug-in, & it’s only been in the last few days that I was testing this, first with an electrical cord before actually installing it onto the house, but after this update today, I can confirm that it is seeing all of the components of the light fixture now, it has the switch for the light, which it always did, you could change the color of the white light which always did work.  But I can confirm that it only saw it as a light bulb and that was it. Now, after this update, there is an on/off toggle switch for the PIR sensor,  as well as the motion sensor itself showing up as a motion sensor & of course the light itself.So that’s fantastic. Everything is working brilliantly. I was ironically just about to sit down in the next day or so and compose a message to you to inquire about this very topic. So for me, the timing at least was quite fortuitous in that I literally only just installed it on the house this very afternoon. At any rate I just wanted to say thank you for your efforts on the update. I also just wanted to give you a confirmation that it absolutely is working. You do have to remove, the occurrence from Apple home and re-add it back in for them to show.I run it as a child bridge for just this one plug-in under homebridge on a raspberry pi 4. So it was very easy to just delete that one child bridge, & as soon as I added it back in, everything showed up as a combined  item properly inside HomeKit. Thanks so much.RandySent from my iPhoneOn Nov 25, 2022, at 9:08 PM, gaosen ***@***.***> wrote:﻿
Closed #121 as completed.

**Comment by 0x5e** [comment]
@randymassey congratulations :)

**Comment by mamante** [comment]
> Thanks for the information. The resaon is this device has `color_data` but no `h`, `s`, `v` inside, then the plugin treate it as neither color light nor white light. Now it should be working.
> 
> And the pir sensor and switch should working too.

@0x5e Thank you for reviving this plug-in and getting it working! I'm super excited and appreciative of your efforts! And thank you @randymassey for your comments about success and timeliness with your use your PIR Motion Light .

As of now, I have the plugin working in HomeKit beautifully as expected and can not control the pir and the switch as well as see the white light as being tunable and can changes its color. However, I am still not able to see the color data nor adjust the color on a color wheel for this light like I can in the Tuya app. Does the HSV data needed to adjusted or added elsewhere in the plugin for this to show up in HomeKit? Is this something I can do or can you assist me?

Here is how it appears in the Tuya app:
![IMG_0756](https://user-images.githubusercontent.com/6117709/204089883-7a150042-f983-4c57-9acf-1081008bb768.PNG)

Thank you and I look forward to hearing back from you when you have a chance!

**Comment by 0x5e** [comment]
From the specification seems your light don't support colors. If it actually have color functions, please see #111

And please have a try in [Tuya Platform > Device Debugging](https://iot.tuya.com/cloud/device/detail). I want to know if the color changing can be set and get from the website.

**Comment by mamante** [comment]
The devices does support colors as it is listed as being a Multicolor Changing RGB, Tunable White 2000K - 5000K light. When I looked into [#111](https://github.com/0x5e/homebridge-tuya-platform/issues/111), as you mentioned, the Standard Instructions of the device seem to be properly mapping the "colour_data" to "colour_data" so I'm not sure what else is missing there. See screenshot below:

<img width="1404" alt="Screenshot 2022-11-26 at 1 32 09 PM" src="https://user-images.githubusercontent.com/6117709/204103860-f10a0725-ac6c-472d-9a2e-a52a5c54d3fe.png">

In additon, when I tried the [Tuya Platform > Device Debugging](https://iot.tuya.com/cloud/device/detail as you asked, the color changing of the device can be set and get from the website. All I needed to do was adjust the "work_mode" menu to "colour" then I could manually set the h,s,v in the colour_data field. Likewise, I could set the parameters in the Tuya app on my phone and choose Update Device Status to change the device color and also pull them into the IoT platform. See screenshot below:

<img width="1404" alt="Screenshot 2022-11-26 at 1 18 03 PM" src="https://user-images.githubusercontent.com/6117709/204104017-79eea9ba-c89c-4456-9c03-388cbbfe6d74.png">

Hopefully, this helps solve the issue and these features can be added to the plugin so they can be accessed and utilized  in HomeKit in addition to the PIR control and white tunable controls already working perfectly. Thank you again so much for your attention and help here and please advise what else is needed to wrap this up.

**Comment by randymassey** [comment]
Yeah, you bet. It really was fortuitous timing on my part. As I mentioned, I tried a different variation of the plug-in & struggled for almost a week & finally just gave up. Once I tried your plug-in, really just on a whim, I was at least able to get it ”connecting” as a light in HomeKit.  But as soon as you released those updates yesterday, 100% of the functionality was available. That was truly fantastic. Thank you for your time & efforts. Can I ask quickly, did I see something in your read me, that every 6 months we need to renew something on the Tuya IOT website where the project lives?My bestRandySent from my iPhoneOn Nov 26, 2022, at 10:40 AM, mamante ***@***.***> wrote:﻿
The devices does support colors as it is listed as being a Multicolor Changing RGB, Tunable White 2000K - 5000K light. When I looked into #111, as you mentioned, the Standard Instructions of the device seem to be properly mapping the "colour_data" to "colour_data" so I'm not sure what else is missing there. See screenshot below:

In additon, when I tried the [Tuya Platform > Device Debugging](https://iot.tuya.com/cloud/device/detail as you asked, the color changing of the device can be set and get from the website. All I needed to do was adjust the "work_mode" menu to "colour" then I could manually set the h,s,v in the colour_data field. Likewise, I could set the parameters in the Tuya app on my phone and choose Update Device Status to change the device color and also pull them into the IoT platform. See screenshot below:

Hopefully, this helps solve the issue and these features can be added to the plugin so they can be accessed and utilized  in HomeKit in addition to the PIR control and white tunable controls already working perfectly. Thank you again so much for your attention and help here and please advise what else is needed to wrap this up.

**Comment by 0x5e** [comment]
@randymassey Yes, the API subscription needs to extend the trial period every 6 months in website, so we have to do this manually. That's inconvenient :(

@mamante I think your device's `colour_data ` is broken, because we need the specific value like this:
```json
{
  "h": {
    "min": 0,
    "scale": 0,
    "unit": "",
    "max": 360,
    "step": 1
  },
  "s": {
    "min": 0,
    "scale": 0,
    "unit": "",
    "max": 1000,
    "step": 1
  },
  "v": {
    "min": 0,
    "scale": 0,
    "unit": "",
    "max": 1000,
    "step": 1
  }
}
```

Then the plugin will actually knows the range of `h`, `s`, `v`, then the color feature will be enabled.
I'm not sure the issue is from your device, or the `gyd` category default schema is wrong. I will submit a ticket to tuya next work day.
