### ISSUE TITLE
Unable to swap Fan icon 

### ISSUE THREAD

**Issue by ricardotpo** [0x5e/homebridge-tuya-platform#123]
Hi all,
I think I found a bug.

I've got a Tuya **ceiling** fan installed and working, however the **icon** on homekit is of a **table top** fan.
When I go to the device settings and try to tap on the fan icon to swap it, nothing happens.

Other than this, I have nothing but compliments !
This plugin is incredibly better than the official one.
Excellent work guys !

**Comment by 0x5e** [comment]
Hi @ricardotpo,
Icon customize feature is provided by homekit app, most accessories don't support icon changing, only few supported (Switch, Light).
See #93 .

**Comment by r2shyyou** [comment]
![image](https://user-images.githubusercontent.com/3274534/204266886-1bede663-5f60-4fc5-8fe1-4a7c55c56d93.png)

there is a fan device/accessory type that allows switching icons, as shown in attached

**Comment by 0x5e** [comment]
> ![image](https://user-images.githubusercontent.com/3274534/204266886-1bede663-5f60-4fc5-8fe1-4a7c55c56d93.png)
> 
> there is a fan device/accessory type that allows switching icons, as shown in attached
> 
> i came across this in the homebridge-irobot plugin, which uses a type of fan accessory to surface the vacuum

Thanks for the information, I will review it's code to see how it do.

**Comment by ricardotpo** [comment]
@0x5e Thank you !
I was not expecting such a fast response !

**Comment by 0x5e** [comment]
@ricardotpo @r2shyyou There's two services: [Fan](https://developers.homebridge.io/#/service/Fan) and [Fanv2](https://developers.homebridge.io/#/service/Fanv2), I'm using `Fanv2` and homebridge-irobot is using `Fan`.
`Fan` has more customizable icons, while `Fanv2` has more characteristics (mode: auto/manual, child lock, swing).

Seems the custom icon requirements is strong, before mode/child lock/swing implemented, I will use `Fan` instead.

**Comment by 0x5e** [comment]
So for the `fs` and `fskg` category, I need to check their schema and if one of the `mode`, `lock`, `swing` exists, I will treate it as `Fanv2`, else `Fan`. I think that's a final solution. Besides there's some cache cleanning work to be done.

**Comment by 0x5e** [comment]
Please try 1.7.0-beta.1, should work now :)
