### ISSUE TITLE
Add support for wxkg

### ISSUE THREAD

**Issue by Konstix08** [0x5e/homebridge-tuya-platform#125]
If you want to add support for the scene switch(cjkg) i can test and debug the plugin for you.

**Comment by Konstix08** [comment]
Because i bought one few days ago

**Comment by Konstix08** [comment]
Do i need a special subscription because the "data reporting" tab is not displayed for me.

**Comment by 0x5e** [comment]
No need. Can you take a picture?

**Comment by 0x5e** [comment]
Maybe only virtual device have "data reporting"... It's okay, you can enable the homebridge debug mode and upload your logs during physical and app control process.

**Comment by Konstix08** [comment]
Oh sorry i thought that the device was cjkg but it is wxkg. I fyoz want to add support for this i can send you the logs.

**Comment by Konstix08** [comment]
data = {
  "result": {
    "category": "wxkg",
    "functions": [],
    "status": [
      {
        "code": "switch_mode1",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"press\"]}"
      },
      {
        "code": "switch_mode2",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"press\"]}"
      },
      {
        "code": "battery_percentage",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },

**Comment by 0x5e** [comment]
> data = { "result": { "category": "wxkg", "functions": [], "status": [ { "code": "switch_mode1", "type": "Enum", "values": "{"range":["click","press"]}" }, { "code": "switch_mode2", "type": "Enum", "values": "{"range":["click","press"]}" }, { "code": "battery_percentage", "type": "Integer", "values": "{"unit":"%","min":0,"max":100,"scale":0,"step":1}" } ] },

Ok, from the data, It's a stateless switch and we can only get event on HomeKit and can not control it. Please enable the homebridge debug mode (see readme troubleshooting), and press the physical switch, single press, double press, long press, I don't know, it depends on your device. Then you can see the mqtt messages from homebridge logs.

I need to know the exactly meaning of `{"switch_mode1": "click"}`, `{"switch_mode1": "press"}`, thanks :)

**Comment by Konstix08** [comment]
Sure i'll do it when i am at home.

**Comment by Konstix08** [comment]
"status": [
    {
      "2": "single_click",
      "code": "switch_mode2",
      "t": "4",
      "value": "click"
    }




"status": [
    {
      "1": "single_click",
      "code": "switch_mode1",
      "t": "5",
      "value": "click"
    }
  ]



"status": [
    {
      "2": "long_press",
      "code": "switch_mode2",
      "t": "11",
      "value": "press"
    }
  ]



"status": [
    {
      "1": "long_press",
      "code": "switch_mode1",
      "t": "1670342532",
      "value": "press"
    }
  ]

**Comment by Konstix08** [comment]
I have 2 Buttons on this thing and it accept a long press and a click.

**Comment by 0x5e** [comment]
So `click` means single click, `press` means long press right?

**Comment by Konstix08** [comment]
Yes, correct

**Comment by 0x5e** [comment]
I've submitted 1.7.0-beta.2, please have a try :) I don't have home hub, not able to test.

**Comment by Konstix08** [comment]
Sure i am not home bow i'll test ur later.

**Comment by Konstix08** [comment]
It works perfect! Thank you for updating the plugin.

**Comment by 0x5e** [comment]
I update the plugin with some modification:
1. Fix fake click event during plugin initialization.
2. Hide single/double/long click for unsupported devices.

And there may still have some possibility of fake event due to #32 , it's a known issue and still working on it.

Please try if the second modification take effects. I don't have home hub and these three buttons are always disabled for me, I don't know if it can be hidden or disabled.

1.7.0-beta.3.

**Comment by Konstix08** [comment]
Ah sorry it works now it just needed a few restarts

**Comment by 0x5e** [comment]
Great :)
