### ISSUE TITLE
Christmas Stringlights full functionality 

### ISSUE THREAD

**Issue by Almansio** [0x5e/homebridge-tuya-platform#126]
Christmas is around the corner so it would be nice to have full functionality of the Stringlights in Homekit: different modes, dimmable, timer & music sync activation instead of the current on/off switch. 

Brand: LSC WW 400 LED Stringlight
Platform: Tuya

;))

**Comment by 0x5e** [comment]
Hi @Almansio , sorry I'm preparing an important exam next month, so before chrismas I will only submit the bug fix and small features. For the light accessory, there already have mode switching (color & white, not scene), brightness, hsv.
From your description I think some of your light's function not work properly, please see: #111 

HomeKit doesn't have timer picker so we can't provide the countdown timer functions. Music sync activation is the same.

**Comment by Almansio** [comment]
Changed the instruction to "Dp instruction", this creates a crash in HomeKit when selecting the device in HomeKit.

**Comment by 0x5e** [comment]
Can you upload the crash logs? If so, your light's instruction may have big difference with standard instructions. But anyway, we can't let the plugin crash.

**Comment by 0x5e** [comment]
If so, please wait for the schema transform feature implemented in 1.7.0, there's much works need to be done.

**Comment by Almansio** [comment]
I will do. Thanks.Op 1 dec. 2022 om 09:16 heeft gaosen ***@***.***> het volgende geschreven:﻿
If so, please wait for the schema transform feature implemented in 1.7.0, there's much works need to be done.

**Comment by Almansio** [comment]
Installed the 1.7.0
- still only option to switch and not to adjust brightness
- when using a smart switch like for example the Bush Jeager Friends of hue switch, the light doesn't switch confirm scene but when activating the scene in the homekit it does.

**Comment by 0x5e** [comment]
Schema transform is still under development. What does the second sentence mean, I'm not clearly understand.

**Comment by Almansio** [comment]
So for example when I activate the scene in Homekit that shuts down every light in the house, the “tuya light” does what its configured to do. But when I configure my smart switch(https://www.busch-jaeger.de/en/product/future-linear/friends-of-hue?_gl=1*1kfvg1c*_ga*MjAxMTc0Njc2MS4xNjcwMTY3MTM1*_ga_N40E6CV9ZN*MTY3MDE2NzEzNS4xLjAuMTY3MDE2NzEzNS42MC4wLjA.*_fplc*RjJuZmRzJTJGV1JscjJzTG9LZlA3WSUyRlZCNUVrdm1ZM3FtQiUyQlplMkRETFRxR3JQZ21CM2RhUmZPJTJGMzhOWFNzNWFVcE1kNDdQTyUyRmtoZXJmb3pKdFpJJTJGMDlmUGxta2haWU42N0xJVUFPeWNjRUJhaGFtd3ZtT1QlMkZuQm15ZTdTZ1ElM0QlM0Q) in Homekit to activate the same scene the “tuya light” doesn’t respond. These are Homekit compatibele switches. 



Op 4 dec. 2022, om 16:16 heeft gaosen ***@***.***> het volgende geschreven:


Schema transform is still under development. What does the second sentence mean, I'm not clearly understand.

**Comment by 0x5e** [comment]
Any error or warning logs about this no respond? I don't have homepod and apple tv to test this. I think there must have people using the scene but I didn't heard this issue before.

**Comment by Almansio** [comment]
No warning or error whatsoever :( 

Op 4 dec. 2022, om 16:36 heeft gaosen ***@***.***> het volgende geschreven:


Any error or warning logs about this no respond? I don't have homepod and apple tv to test this. I think there must have people using the scene but I didn't heard this issue before.

**Comment by 0x5e** [comment]
Device config override feature is submitted, please try if it can change your light fully functional.

**Comment by Almansio** [comment]
﻿Hi thanks! I will try it later. Should I re-add the device in the Tuya platform, restart homebridge or adjust the config of the device in the Tuya platform? Op 12 dec. 2022 om 11:40 heeft gaosen ***@***.***> het volgende geschreven:﻿
Device config override feature is submitted, please try if it can change your light fully functional.

**Comment by Almansio** [comment]
Nevermind! Hahaha I see there is an update! Thanks for the effort and will let you know if this resolves the issue.Again many thanks.Op 12 dec. 2022 om 11:40 heeft gaosen ***@***.***> het volgende geschreven:﻿
Closed #126 as completed.
