### ISSUE TITLE
Add support for xxj (Diffuser)

### ISSUE THREAD

**Issue by fadelguy** [0x5e/homebridge-tuya-platform#132]
Please add support for aroma diffuser xxj
I can debug and test for fast development.

Info:
{
"result": {
"active_time": 1669909612,
"category": "xxj",
"category_name": "Diffuser",
"create_time": 1669909612,
"gateway_id": "",
"icon": "smart/icon/ay1525833075368tsInS/d90b58d9cba10f1ae4a79badd27d8551.png",
"id": "bfdb5cf6ea52d73678vy5w",
"model": "",
"name": "YX316WIFI",
"online": true,
"owner_id": "9371705",
"product_id": "arkdxfhlkpdyof9x",
"product_name": "YX316WIFI",
"sub": false,
"time_zone": "+02:00",
"update_time": 1669933697,
},

Functions:

"result": {
"category": "xxj",
"functions": [
{
"code": "switch",
"lang_config": {
"false": "OFF",
"true": "ON"
},
"name": "Switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "switch_spray",
"lang_config": {
"false": "OFF",
"true": "ON"
},
"name": "Spray",
"type": "Boolean",
"values": "{}"
},
{
"code": "switch_sound",
"lang_config": {
"false": "OFF",
"true": "ON"
},
"name": "Sound",
"type": "Boolean",
"values": "{}"
},
{
"code": "switch_led",
"lang_config": {
"false": "OFF",
"true": "ON"
},
"name": "Led",
"type": "Boolean",
"values": "{}"
},
{
"code": "bright_value_v2",
"lang_config": {
"unit": ""
},
"name": "Brightness",
"type": "Integer",
"values": "{"unit":"","min":0,"max":1000,"scale":0,"step":1}"
},
{
"code": "work_mode",
"lang_config": {
"colour": "Colour",
"colourful1": "Colourful",
"white": "White"
},
"name": "Led Mode",
"type": "Enum",
"values": "{"range":["white","colour","colourful1"]}"
},
{
"code": "colour_data_hsv",
"lang_config": {
"unit": ""
},
"name": "Color",
"type": "Json",
"values": "{}"
}
],
"status": [
{
"code": "switch",
"lang_config": {
"false": "OFF",
"true": "ON"
},
"name": "Switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "switch_spray",
"lang_config": {
"false": "OFF",
"true": "ON"
},
"name": "Spray",
"type": "Boolean",
"values": "{}"
},
{
"code": "switch_sound",
"lang_config": {
"false": "OFF",
"true": "ON"
},
"name": "Sound",
"type": "Boolean",
"values": "{}"
},
{
"code": "switch_led",
"lang_config": {
"false": "OFF",
"true": "ON"
},
"name": "Led",
"type": "Boolean",
"values": "{}"
},
{
"code": "bright_value_v2",
"lang_config": {
"unit": ""
},
"name": "Brightness",
"type": "Integer",
"values": "{"unit":"","min":0,"max":1000,"scale":0,"step":1}"
},
{
"code": "work_mode",
"lang_config": {
"colour": "Colour",
"colourful1": "Colourful",
"white": "White"
},
"name": "Led Mode",
"type": "Enum",
"values": "{"range":["white","colour","colourful1"]}"
},
{
"code": "colour_data_hsv",
"lang_config": {
"unit": ""
},
"name": "Color",
"type": "Json",
"values": "{}"
}
]
},

**Comment by 0x5e** [comment]
Ok, I'm planning to do this.

**Comment by fadelguy** [comment]
Hi, 
Any news on this?

**Comment by 0x5e** [comment]
Sorry I'm a bit busy these days, when it's complete I will let you know :)

**Comment by fadelguy** [comment]
OK. Thank you very much!

**Comment by 0x5e** [comment]
Please have a try. main switch, light switch / brightness, spray switch / brightness is supported, but the color mode not yet, it need heavy code and I'm not prepared to migrate it.

**Comment by fadelguy** [comment]
Hi,
Thank you for this!

But the device not working.

26/12/2022, 19:39:09HomeTuyaPlatformAdding new accessory: Diffuser
26/12/2022, 19:39:09HomeTuyaPlatformWARNINGUnsupported device: Diffuser.

**Comment by 0x5e** [comment]
It's added in beta.15, can you confirm if you are using the latest version?

**Comment by fadelguy** [comment]
I only see on hoobs beta 14. I don't see beta 15. Maybe need to wait

**Comment by fadelguy** [comment]
It's working now on beta 15.

I don't see how to control the working mode
"10s,2h,4h"
Didn't see it in the api also

**Comment by fadelguy** [comment]
![Uploading 0E825ACD-481A-4C03-B430-C59BB29194B3.png…]()

**Comment by 0x5e** [comment]
unfortunately, I didn't found a way to support countdown feature. homebridge only have a characteristic of `SetDuration` with 0-3600s range, that's not enough for > 1 hour timer.
