### ISSUE TITLE
Wi-Fi IR Remote Control

### ISSUE THREAD

**Issue by Bob1979CAN** [0x5e/homebridge-tuya-platform#134]
Dear Dev Team.

I'm not able to get Devices configured through Wi-Fi IR Remote Control like this one
https://expo.tuya.com/product/402053

I have the following error message:
[12/5/2022, 2:23:13 PM] [TuyaPlatform] Adding new accessory: AC
[12/5/2022, 2:23:13 PM] [TuyaPlatform] Unsupported device: AC.

and

[TuyaDeviceManager] Get device specification failed. devId = eb1abeb3c60131aadxxxxugo, code = 2009, msg = not support this device

Could you help me with this one?

Thanks

**Comment by 0x5e** [comment]
Duplicated with this one: #88 .
IR device is not supported yet, it's a complicate one and need more time to develop :)

**Comment by 0x5e** [comment]
Yes I've seen this before, I will try to migrate it's code into my plugin later, when I have enough time.
And yes, device config is only needed for some advance features (in the future), or something that have to be configured through config.

**Comment by Bob1979CAN** [comment]
Hello There @0x5e is there any update on this one? many thanks in advance.

**Comment by 0x5e** [comment]
IR for air conditioner is not complete, other part is working now, I will merge the branch when all IR category is working.
