### ISSUE TITLE
Garage Door controller - no contact sensor update

### ISSUE THREAD

**Issue by 1aranzant** [0x5e/homebridge-tuya-platform#138]
Garage door controllers have a contact sensor that should display whether the door is in close or open position.
The issue is that the state of that sensor is not updated. 

Further more, nothing appears in the debug log when changing the open/close position of the sensor, but it does work well in the Tuya app.

**Comment by 0x5e** [comment]
If no messages received during open/close the door, but the door already has the position sensor, please see #111 .

**Comment by 1aranzant** [comment]
![image](https://user-images.githubusercontent.com/17981079/206469566-c712b098-48ad-4ca9-8346-44018015b270.png)
I changed to DP insutrctions, but still same issue. 
Here is the device info json:
 ```
{
    "active_time": 1670321049,
    "biz_type": 0,
    "category": "ckmkzq",
    "create_time": 1670321049,
    "icon": "smart/icon/ay1559113396016bSygG/9719ce2bebaeb6ccfadbe2c28d7d9df8.jpg",
    "id": "7061448370039f9086c6",
    "ip": "xxxxx",
    "lat": "xxxx",
    "local_key": "xxxxx",
    "lon": "xxxxx",
    "model": "WG-088",
    "name": "Contrôleur de portail",
    "online": true,
    "owner_id": "3466908",
    "product_id": "b1uk4ftduaqopxv1",
    "product_name": "Garage door opener",
    "status": [
      {
        "code": "doorcontact_state",
        "value": false
      },
      {
        "code": "switch_1",
        "value": false
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "xxxx",
    "update_time": 1670321064,
    "uuid": "7061448370039f9086c6",
    "schema": [
      {
        "code": "doorcontact_state",
        "mode": "ro",
        "type": "Boolean",
        "property": {}
      },
      {
        "code": "switch_1",
        "mode": "rw",
        "type": "Boolean",
        "property": {}
      }
    ]
  },
```

**Comment by 1aranzant** [comment]
I fixed the issue ! Very stupid of me... 
I did not have the "Device Status Notification" authorized in Tuya IOT Platform Service APIs. 
Thanks a lot for your time @0x5e
