### ISSUE TITLE
Add support for ir/rf

### ISSUE THREAD

**Issue by Konstix08** [0x5e/homebridge-tuya-platform#142]
If you would like to add support for ir/rf devices i can test it for you. It would be great because there isn't any plugin out there that supports rf.

**Comment by 0x5e** [comment]
I have ir device too, I can test air-condition and fan. I will try to migrate homebridge-tuya-ir at later time :)

**Comment by Konstix08** [comment]
Ok :) it would be great if you can also add support for rf devices. I try to learn typeScript that i can commit something too.

**Comment by 0x5e** [comment]
What's the category of rf device? I didn't seen it before.. I just thought they are the same.

**Comment by Konstix08** [comment]
They are the same category but i think the plugin is wrong. Because rf devices get not automatic discovered and i can't control them in homekit.

**Comment by 0x5e** [comment]
You mean the rf device didn't appear in the device list? Can you see the rf device in the website?

**Comment by Konstix08** [comment]
Yes i see rf devices in the list and the category is the same.

**Comment by Konstix08** [comment]
I need to add them manual (in the tuya-ir plugin)

**Comment by 0x5e** [comment]
Can it be seen in the tuya app's device list? do you have some device infos or photos to help me understand this device? Because I didn't heard of it before :)

**Comment by Konstix08** [comment]
I don't know which photos to attach because the rf devices look all the same but only are not discovered automatically and they are not controllable even though it appears a success message. (tuya-ir plugin)

**Comment by 0x5e** [comment]
I guess they are similar in software, just different hardware, so the plugin can treat them as the same.

**Comment by Konstix08** [comment]
I would like to add support for the ir_switch1 category by myself do i only need to fetch the codes or do i need ro fetch the ir/rf hub too.

**Comment by 0x5e** [comment]
I'm not sure, ir is a special category different with others, probably need additional setup steps...

**Comment by yk1n9** [comment]
Helllo i just read this thread. My IR device is getting pulled but i don't see it on homebridge interface but gets added to my homekit where i can see it. Is there some minor changes i can do to support it?

**Comment by 0x5e** [comment]
> Helllo i just read this thread. My IR device is getting pulled but i don't see it on homebridge interface but gets added to my homekit where i can see it. Is there some minor changes i can do to support it?
> 
> 

ir need big changes... you can search a tuya-ir plugin, I'm plan to migrate it.

**Comment by yk1n9** [comment]
Tuya ir plugin doesn work with your plugin. Any advice to make it work will be appreciated.

--
Kind Regards
Anand Bhalodi
***@***.***
+919099800006
Whatsapp: +919099800006

**Comment by Konstix08** [comment]
You need to run 2 child bridges. But the ir plugin itself is very bad.

**Comment by 0x5e** [comment]
tuya cloud api doesn't support multuple session, so any tuya homebridge or homeassistant plugin can't run at same time with same accesskey. If you really want, use different account..

**Comment by Konstix08** [comment]
For me it works with one account. Idk why but it seems to be working.

**Comment by yk1n9** [comment]
It worked when made tuya ir into a child bridge. But @0x5e is right it does bug out sometimes. Different account might be the best solution.
