### ISSUE TITLE
Setting HeatingThresholdTemperature to more than 25°C

### ISSUE THREAD

**Issue by hattabatatta** [0x5e/homebridge-tuya-platform#154]
Within the (no longer maintained) version 1.5.0 I was able to set my heaters to more than 25° for heating.
In the Tuya App it is also possible.

Using this version I am no longer able to set the max temp to more than 25° and I don´t see a very simple possibility to set it
How to fix that or set that (as it may work already)?

**Comment by 0x5e** [comment]
`Heating Threshold Temperature`'s max range is `0°C~25°C`, set range beyound it will cause failure. What's your device's category? Let me reivew the difference between 1.5.0 and now.

**Comment by hattabatatta** [comment]
Thx for your quick response.

The log says, the category of the heaters is "qn"

**Comment by 0x5e** [comment]
I have some test and seems 0~25 limitation does not exist, at least for iOS 16, I will remove it in the next version.

**Comment by 0x5e** [comment]
Please try beta.10, should be fixed now.
