### ISSUE TITLE
Dehumidifier not recognized

### ISSUE THREAD

**Issue by hattabatatta** [0x5e/homebridge-tuya-platform#155]
I have 2 dehumidifier devices from the same brand and type.
One of them is recognized by the homebridge plugin and so controlable within HomeKit, the other one not. Dunno what may be the problem.

Here you have the log from the plugin:

[12/17/2022, 5:10:01 AM] [@0x5e/homebridge-tuya-platform] Restoring existing accessory from cache: Luftentfeuchter Wohnzimmer 
[12/17/2022, 5:10:01 AM] [@0x5e/homebridge-tuya-platform] [Luftentfeuchter Wohnzimmer ] Set props for RelativeHumidityDehumidifierThreshold: { minValue: 0, maxValue: 100, minStep: 5 }
[12/17/2022, 5:10:01 AM] [@0x5e/homebridge-tuya-platform] [Luftentfeuchter Wohnzimmer ] Set props for RotationSpeed: { minValue: 0, maxValue: 100, minStep: 100 }
[12/17/2022, 5:10:01 AM] [@0x5e/homebridge-tuya-platform] [Luftentfeuchter Wohnzimmer ] CurrentTemperature not supported.
[12/17/2022, 5:10:01 AM] [@0x5e/homebridge-tuya-platform] Restoring existing accessory from cache: Luftentfeuchter Bad
[12/17/2022, 5:10:01 AM] [@0x5e/homebridge-tuya-platform] [Luftentfeuchter Bad] Missing one of the required schema: [ 'switch' ]
[12/17/2022, 5:10:01 AM] [@0x5e/homebridge-tuya-platform] [Luftentfeuchter Bad] Missing one of the required schema: [ 'humidity_indoor' ]
[12/17/2022, 5:10:01 AM] [@0x5e/homebridge-tuya-platform] [Luftentfeuchter Bad] Existing schema: [
  { code: 'anion', mode: 'rw', type: 'Boolean', property: {} },
  {
    code: 'countdown_left',
    mode: 'ro',
    type: 'Integer',
    property: { unit: 'min', min: 0, max: 1440, scale: 0, step: 1 }
  },
  {
    code: 'fault',
    mode: 'ro',
    type: 'Bitmap',
    property: { label: [ '0', '1', '2', '3', '4', '5', [length]: 6 ] }
  },
  [length]: 3
]

**Comment by 0x5e** [comment]
This phenomenon tells me, alghough these two device are same brand and same type, but they are in different product_id, and different schema. Please refer readme faq, troubleshooting , and provide device info list json file, then we can see the difference between them.

**Comment by hattabatatta** [comment]
There you go

`[
   
  {
    "active_time": 1667991268,
    "biz_type": 0,
    "category": "cs",
    "create_time": 1667991152,
    "icon": "smart/product_icon2/cs_1.png",
    "id": "",
    "ip": "178.113.120.175",
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "V2.0",
    "name": "Luftentfeuchter Wohnzimmer ",
    "online": true,
    "owner_id": "68893697",
    "product_id": "to4nyl9qxvkqmcmk",
    "product_name": "DryFy Connect",
    "status": [
      {
        "code": "anion",
        "value": false
      },
      {
        "code": "child_lock",
        "value": false
      },
      {
        "code": "dehumidify_set_value",
        "value": 50
      },
      {
        "code": "fan_speed_enum",
        "value": "low"
      },
      {
        "code": "fan_speed_enum",
        "value": "low"
      },
      {
        "code": "humidity_indoor",
        "value": 54
      },
      {
        "code": "mode",
        "value": "drying"
      },
      {
        "code": "swing",
        "value": false
      },
      {
        "code": "switch",
        "value": false
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "",
    "update_time": 1669885911,
    "uuid": "23376568a4e57c96eb9d",
    "schema": [
      {
        "code": "anion",
        "mode": "rw",
        "type": "Boolean",
        "property": {}
      },
      {
        "code": "child_lock",
        "mode": "rw",
        "type": "Boolean",
        "property": {}
      },
      {
        "code": "dehumidify_set_value",
        "mode": "rw",
        "type": "Integer",
        "property": {
          "unit": "%",
          "min": 35,
          "max": 80,
          "scale": 0,
          "step": 5
        }
      },
      {
        "code": "fan_speed_enum",
        "mode": "rw",
        "type": "Enum",
        "property": {
          "range": [
            "low",
            "high"
          ]
        }
      },
      {
        "code": "humidity_indoor",
        "mode": "ro",
        "type": "Integer",
        "property": {
          "unit": "%",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "mode",
        "mode": "rw",
        "type": "Enum",
        "property": {
          "range": [
            "drying",
            "continuous"
          ]
        }
      },
      {
        "code": "swing",
        "mode": "rw",
        "type": "Boolean",
        "property": {}
      },
      {
        "code": "switch",
        "mode": "rw",
        "type": "Boolean",
        "property": {}
      }
    ]
  },
  {
    "active_time": 1668509860,
    "biz_type": 0,
    "category": "cs",
    "create_time": 1668509860,
    "icon": "smart/product_icon2/cs_1.png",
    "id": "bf4cd6cd6bf38db1cewj91",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "",
    "name": "Luftentfeuchter Bad",
    "online": true,
    "owner_id": "68893697",
    "product_id": "5wqlv98zznc8objk",
    "product_name": "KLARSTEIN DryFy Connect",
    "status": [
      {
        "code": "anion",
        "value": false
      },
      {
        "code": "countdown_left",
        "value": 0
      },
      {
        "code": "fault",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "",
    "update_time": 1669230792,
    "uuid": "5c49fd3199c96b45",
    "schema": [
      {
        "code": "anion",
        "mode": "rw",
        "type": "Boolean",
        "property": {}
      },
      {
        "code": "countdown_left",
        "mode": "ro",
        "type": "Integer",
        "property": {
          "unit": "min",
          "min": 0,
          "max": 1440,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "fault",
        "mode": "ro",
        "type": "Bitmap",
        "property": {
          "label": [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5"
          ]
        }
      }
    ]
  },
]`

**Comment by 0x5e** [comment]
`to4nyl9qxvkqmcmk` is correct, `5wqlv98zznc8objk` is wrong configured by manufacturer, you need to switch control mode and try if it's working, if still not available, need to use `deviceOverrides` to remap schemas manually.

**Comment by hattabatatta** [comment]
Ok I´ll give it a try ... where can I switch the control mode? :D

**Comment by 0x5e** [comment]
Please read the faq and troubleshooting in readme.
https://github.com/0x5e/homebridge-tuya-platform#faq
