### ISSUE TITLE
Add support for 3 speed ceiling fan

### ISSUE THREAD

**Issue by RyanBang79** [0x5e/homebridge-tuya-platform#156]
DETA GRID CONNECTION SMART SWITCH
1Light Gang and Ceiling Fan

This device has 3speed fan. Level 1 ,2 and 3(fastest).
But only control with two level

**Device info**
Please refer to the troubleshooting section to get device list info. https://github.com/0x5e/homebridge-tuya-platform#troubleshooting

**Comment by 0x5e** [comment]
Please refer to the troubleshooting section to get device list info. https://github.com/0x5e/homebridge-tuya-platform#troubleshooting
