### ISSUE TITLE
Getting access token expired error. No issues with Tuya account.

### ISSUE THREAD

**Issue by rccsvt71** [0x5e/homebridge-tuya-platform#166]
In the past week, my tuya plugin is going down after a few hours. 

I receive this error twice in succession: 
"[TuyaOpenAPI] Refresh access_token failed. code = 1010, msg = token is expired" 

After this, no Tuya devices are available in HomeKit. 

A manual restart of the plugin temporarily resolves the problem, but it goes down again within a couple of hours. There was no issue with this plugin until the past week.

**Comment by 0x5e** [comment]
Do you have another homebridge/homeassistant/nodered instance running any tuya cloud based plugins? The tuya cloud api key/secret can't be used in multiple session.

**Comment by rccsvt71** [comment]
Thank you for the response. I do have Home Assistant running as well. Thanks for the heads up!
