### ISSUE TITLE
Random plugin restarts: Cannot read properties of undefined (reading "length")

### ISSUE THREAD

**Issue by Kositch** [0x5e/homebridge-tuya-platform#176]
**Describe the bug**
Randomly child bridge running this Tuya platform plugin restarts with errors as in screenshot. Got connected 1 camera (no other Tuya devices) and everything works as expected (video stream etc.).  Configurated using the guide in plugin description. Is it possible to do something to stop this happening OR decrease the log level? Plugin is quite flooding my homebridge log. Anyway thanks for the great plugin!

**Screenshots**
![2022-12-26_19-49-25](https://user-images.githubusercontent.com/86477937/209576417-e98fcad6-fbc7-4b54-a9ce-a5b8f1d0c1cb.png)

**Comment by 0x5e** [comment]
Seems the plugin is crashing, can you enable homebridge debug log and upload the full logs? It can help me solving this issue, no more restart then. from the non debug log I can locate the issue but I want to know why it happens.

**Comment by Kositch** [comment]
> Seems the plugin is crashing, can you enable homebridge debug log and upload the full logs? It can help me solving this issue, no more restart then. from the non debug log I can locate the issue but I want to know why it happens.

Can you please advise me how to do that? I have never done that before. Thanks!

**Comment by 0x5e** [comment]
Guides are here: https://github.com/0x5e/homebridge-tuya-platform#troubleshooting

**Comment by dmckillican** [comment]
I am also experiencing the same issue with 3 x ANKO (KMART) cameras. I'll send you the log with debug directly as it contains tokens.

Cheers, and good luck! best, Drew

**Comment by 0x5e** [comment]
> I am also experiencing the same issue with 3 x ANKO (KMART) cameras. I'll send you the log with debug directly as it contains tokens.
> 
> Cheers, and good luck! best, Drew

Thanks, I got the email and I will fix this today :)

**Comment by 0x5e** [comment]
Fixed in beta.16.

**Comment by Kositch** [comment]
> Fixed in beta.16.

I have also collected the debug log if you need it, where can I send it when it contains sensitive tokens etc.? Or you do not need it anymore? Thaks!

**Comment by 0x5e** [comment]
> > Fixed in beta.16.
> 
> I have also collected the debug log if you need it, where can I send it when it contains sensitive tokens etc.? Or you do not need it anymore? Thaks!

Yes no need anymore, please upgrade the plugin and confirm if it has been fixed, thanks :)

**Comment by Kositch** [comment]
> > > Fixed in beta.16.
> > 
> > 
> > I have also collected the debug log if you need it, where can I send it when it contains sensitive tokens etc.? Or you do not need it anymore? Thaks!
> 
> Yes no need anymore, please upgrade the plugin and confirm if it has been fixed, thanks :)

Upgraded and still when I open the stream, plugin gets restarted:

![2022-12-27_09-15-49](https://user-images.githubusercontent.com/86477937/209635307-5229d38f-8f1f-43df-b52c-6d5fa4a60916.png)

**Comment by 0x5e** [comment]
Weird... can you go to the tuya website and the device debugging page, take some photos about the standard instruct sets? can `doorbell_pic` been found there?

**Comment by dmckillican** [comment]
Looks as though it’s working for me now, awesome work buddy thank you!Generally the cam performance isn’t great but I think that’s the hardware. To save power they don’t return images often (even in the Tuya app). This seems to be persistent in HomeBridge. Essentially I think the camera stream sleeps until it’s needed or detects motion.Sent from my iPhoneOn 27 Dec 2022, at 19:37, gaosen ***@***.***> wrote:﻿
Weird... can you go to the tuya website and the device debugging page, take some photos about the standard instruct sets? can doorbell_pic been found there?

**Comment by Kositch** [comment]
> Weird... can you upload the `/var/lib/homebridge/persist/TuyaDeviceList.*.json`(manually remove the sensitive data, ip, token, localkey) or just send me email?

Here is the complete Standard Instruction Set from my device from Tuya website and how can I download that TyuaDeviceList.*.json files? I can login to shell of RPi where HB is running, but dont know the commands. Thanks.
![2022-12-27_09-51-36](https://user-images.githubusercontent.com/86477937/209640146-c335ba25-08ef-4df3-b361-56d7fbf5f0ef.png)

**Comment by Kositch** [comment]
Meanwhile I have sent you to you email directly homebridge debug log part where that error happens with plugin restarts (it is from previous version beta 15), but with beta 16 it does the same error.

**Comment by 0x5e** [comment]
can you send the beta 16 logs? as @dmckillican has been fixed, I want to confirm if the upgrade is success.

**Comment by 0x5e** [comment]
@dmckillican the preview of the camera in homekit app homepage is a snapshot, apple will fetch it every 15s.

**Comment by Kositch** [comment]
> can you send the beta 16 logs? as @dmckillican has been fixed, I want to confirm if the upgrade is success.

OK, so I have rebooted whole HB server and it seems the plugin is not crashing now - was not able to replicate it in -D mode. But when I try to open the stream in Home app, I get very often those error, but I suppose it is just a communication issue through the Tuya servers, right? Camera is near WiFi AP with excellent signal.
![Uploading 2022-12-27_10-37-29.png…]()

**Comment by 0x5e** [comment]
yes, upgrade plugin need to restart the homebridge.
do you have the latest firmware of the camera? mine didn't get snapshot until I uprgade the firmware (but my error is different with you).

**Comment by dmckillican** [comment]
Confirming everything is now working fine and consistently.Delays and slow responses were resolved by adjusting the setting within the camera itself via the Tuya App. I had PIR set to off on the camera subject to performance issues.After turning on PIR the camera became responsive.Thanks again for your help and fast turn around. The PIR “quirk” may be something worth noting.Sent from my iPhoneOn 27 Dec 2022, at 20:19, gaosen ***@***.***> wrote:﻿
can you send the beta 16 logs? as @dmckillican has been fixed, I want to confirm if the upgrade is success.

**Comment by Kositch** [comment]
Yes, I can also confirm, that my camera is now working without any issues or plugin reboots. It would be great to have a Homekit switch for night IR toggle, because I have turned it off to extend battery life of camera and would like only to switch it on when I need, I suppose it is not possible to have that? Thanks!

**Comment by 0x5e** [comment]
OK, switches will be added later.
