### ISSUE TITLE
Account has reached upper limit of 2

### ISSUE THREAD

**Issue by krozgrov** [0x5e/homebridge-tuya-platform#18]
Not an issue with the plugin, but does anyone know how to unlink an account from the Tuya IOT site to relink the app to the devices?

The number of projects linked with this Tuya Smart App account has reached the upper limit of 2. Unlink the account from existing projects and try again.

**Comment by 0x5e** [comment]
To be honest I'm not familiar with Tuya Platform too, but you can submit ticket in the platform, there' will answer the platform related things.

**Comment by 0x5e** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5144674/198187624-68c7a411-dce0-4a9f-9d86-e23b68691f01.png">
Try this.

**Comment by krozgrov** [comment]
That’s what I attempted now I receive this error when trying to register my app again.

[IMG_2025]



On Oct 26, 2022, at 11:56 PM, gaosen ***@***.***> wrote:

﻿

[image]<https://user-images.githubusercontent.com/5144674/198187624-68c7a411-dce0-4a9f-9d86-e23b68691f01.png>

Try this.

**Comment by krozgrov** [comment]
Tuya support was able to correct this issue with device registration!  Cheers!
