### ISSUE TITLE
Camera log

### ISSUE THREAD

**Issue by Magna66** [0x5e/homebridge-tuya-platform#182]
I am getting the below frequently from my camera, the camera works fine but no notification which is also fine, but why I am getting this in the logs, does the camera disconnects frequently from tuya server? thank you in advance for all your effort and support.

[12/29/2022, 12:08:54 PM] [@0x5e/homebridge-tuya-platform] [TuyaDeviceManager] Unhandled mqtt message: bizCode = p2pSignal, bizData = {
  msg: {
    candidate: 'a=candidate:1873371349 1 UDP 16777215 15.204.8.15 63246 typ relay\r\n'
  },
  header: {
    path: 'mqtt',
    trace_id: 'ipc_p2p_ios_eb8a7cd133b2676a49x6ue_1672286933333',
    sub_dev_id: '',
    from: 'eb8a7cd133b2676a49x6ue',
    moto_id: '',
    to: 'az1609558286626tznhy',
    sessionid: 'eb8a7cd133b2676a49x6ue1672286933jrn4YDeL',
    type: 'candidate'
  }
}
[12/29/2022, 12:09:26 PM] [@0x5e/homebridge-tuya-platform] [TuyaDeviceManager] Unhandled mqtt message: bizCode = p2pSignal, bizData = {
  msg: { close_reason_local: 0, close_reason: 6 },
  header: {
    path: 'mqtt',
    trace_id: 'ipc_p2p_ios_eb8a7cd133b2676a49x6ue_1672286933333',
    sub_dev_id: '',
    from: 'eb8a7cd133b2676a49x6ue',
    moto_id: '',
    to: 'az1609558286626tznhy',
    sessionid: 'eb8a7cd133b2676a49x6ue1672286933jrn4YDeL',
    type: 'disconnect'
  }

**Comment by 0x5e** [comment]
I guess that's because you are using tuya app watching the camera stream. there's no need for plugin to handle this, I will silent this warning log in the next version, thanks for the feedback :)

**Comment by Magna66** [comment]
> I guess that's because you are using tuya app watching the camera stream. there's no need for plugin to handle this, I will silent this warning log in the next version, thanks for the feedback :)

Yes I do sometimes use smartlife app to watch the stream, as sometimes the RTSP stop streaming in ispy camera software, so to ensure it is connected I check the app which solves the ispy problem too, dont know how as this is local onvif RTSP, while the app use online RTSP streaming. I also changed the control mode for the camera to DP instruction, as per your suggestion in case.
Thank you so much, and yes please silence this warning.
