### ISSUE TITLE
Support for fan light colour temperature

### ISSUE THREAD

**Issue by acal11** [0x5e/homebridge-tuya-platform#183]
It would be great if the FanAccessory could have support for COLOR_TEMP as the LightAccessory does.
The fan in question has `temp_value` as the DP for the colour temp.

**Comment by 0x5e** [comment]
Sure, I'm planning to modify the code of the lightbulb's part, make it reusable, then will be used in other categorys like fan, diffuser and so on.

**Comment by 0x5e** [comment]
added in beta.18, please have a try.

**Comment by Andre-InfoTrack** [comment]
That was quick!

Unfortunately I get this error in the logs now when it launches:

![image](https://user-images.githubusercontent.com/56006212/210015162-a72e2eb5-2d10-4d76-af28-8868486b8953.png)

**Comment by acal11** [comment]
That was quick!

Unfortunately I get this error in the logs now when it launches:
![7B9B6FA4-D3B1-4D15-9D25-E569AB6D166C](https://user-images.githubusercontent.com/49600937/210015342-7124188b-7048-41f1-aec8-6903e0eb0399.png)

**Comment by 0x5e** [comment]
Fixed in beta.19, I'm not at home and commit with other people's computer, please help me confirm if it's fixed, thanks.

**Comment by acal11** [comment]
Looks to be working now! Many thanks
