### ISSUE TITLE
I can't see accessories/devices on iphone13pro(16.3) and iwatch(9.3) but on iPad(15.7.1) yes :-/ Why?

### ISSUE THREAD

**Issue by lightingcze** [0x5e/homebridge-tuya-platform#189]
![image](https://user-images.githubusercontent.com/18398709/210120867-b9925d16-b06d-462c-86f8-657033370401.jpeg)

![image](https://user-images.githubusercontent.com/18398709/210120870-6ddc58c0-57f8-449a-9957-261121d14ee9.png)

**Comment by 0x5e** [comment]
I have no idea about this, at least one of the apple device see the accessory, means homebridge is working.maybe you can fire an issue on apple fourm.

**Comment by lightingcze** [comment]
Yesterday's ios update solved my problem , now i can see all devices from Tuya app ;-)

**Comment by 0x5e** [comment]
great :)
