### ISSUE TITLE
PIR Motion Detector - not working properly

### ISSUE THREAD

**Issue by fadelguy** [0x5e/homebridge-tuya-platform#192]
Hi,

I'm using the last beta.
I have the motion detector below.
I see it on homekit.

When I create automation on tuya app to turn on lights when motion detection it's working fine.

But when I create the same automation on home app nothing happens.

When I checked on home app I see the correct state but not in real time, I need to close home app and reopen to see the correct state.

There is no logs for this.

Please advise.

![image](https://user-images.githubusercontent.com/32434449/210180608-48e18536-d3ef-4ecf-8684-58f139b4acaf.jpeg)

**Comment by 0x5e** [comment]
I have a tuya contact sensor, which can get the correct state on homekit app in real time.
If you can reopen homekit app to see the correct state, no need to restart homebridge, seems latest state has already pushed to the homebridge.
Maybe there's connection issue between homebridge and homehub, or between homebridge and iphone? I'm not sure.

**Comment by fadelguy** [comment]
I just clear the cache and it's start to work on home app
