### ISSUE TITLE
when homebridge starts after few hours, tuya plug-in no responding(but sonoff & others works fine)

### ISSUE THREAD

**Issue by sansan333333** [0x5e/homebridge-tuya-platform#206]
- [ ] I've read the [Readme - FAQ](https://github.com/0x5e/homebridge-tuya-platform#faq) and [Readme - Troubleshooting](https://github.com/0x5e/homebridge-tuya-platform#troubleshooting) section.

**Describe the bug**
after a few hours running homebridge. only the tuya plugin is not working, (rest plug in all works fine, like sonoff miot)

**Device info**
Synology dva1622 package installed

**Comment by 0x5e** [comment]
May duplicated of #166

**Comment by sansan333333** [comment]
> May duplicated of #166

when creating a new project and add to my accout, I got error

"The number of projects linked with this Tuya Smart App account has reached the upper limit of 2. Unlink the account from existing projects and try again."

but i checked all projects, there is no 2nd place having my account.

how can i fix this?

thx

**Comment by 0x5e** [comment]
for the login issues, please contact tuya, open a ticket here: https://service.console.tuya.com/
