### ISSUE TITLE
Fan speed is not working

### ISSUE THREAD

**Issue by AadithyaU** [0x5e/homebridge-tuya-platform#211]
Seeing the following error log in the homebridge:

This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -20 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.

Whatever fan speed I give, that is not getting reflected in homekit but the fan speed does take effect. Speed doesnt get updated.

**Comment by 0x5e** [comment]
Might related to https://github.com/0x5e/homebridge-tuya-platform/releases/tag/v1.7.0-beta.14
- Change range and unit of RotationSpeedLevel, need clean accessory cache to take effect. by @0x5e in https://github.com/0x5e/homebridge-tuya-platform/pull/174

Have you tried clean accessory cache? If still not work, please post your device info json.
