### ISSUE TITLE
Add support for adaptive lighting

### ISSUE THREAD

**Issue by benwtf** [0x5e/homebridge-tuya-platform#212]
The main thing that keeps me on https://github.com/iRayanKhan/homebridge-tuya (aside from local control) is that the plugin implements Apple's adaptive lighting, which adjusts the color temperature based on time of day and brightness. It would be a useful feature in this plugin.

**Comment by felipehjcosta** [comment]
+1

**Comment by 0x5e** [comment]
sorry for the delay, I was over optimistic about my develop time. I hope I can start this at april. can anyone help me to find some guide of how to integrate adaptive lighting?

**Comment by 0x5e** [comment]
please try beta.34, I don't have home hub to test.

**Comment by felipehjcosta** [comment]
It took some minutes to change but it seems to be working! It's the sun icon!

![IMG_0989](https://user-images.githubusercontent.com/2865924/229545661-13c8dc77-1ffe-4d01-a89a-b13b61f85712.PNG)

**Comment by felipehjcosta** [comment]
@0x5e I have other bulbs with brightness control only. Is it possible to override them and use adaptive lighting to control them? it would be a nice feature :)

**Comment by felipehjcosta** [comment]
😢 
Ok than!

**Comment by felipehjcosta** [comment]
When I turn the light off with adaptive lighting enabled, the light turns on again after 2 seconds. Is this the expected behavior when enabling adaptive lighting on HomeKit?

**Comment by felipehjcosta** [comment]
Well, it seems to be a bug on HomeKit!

I have two scenes: One that turns the light on and another that turns it off.
If I turn the light with adaptive lighting enabled off, it turns on again after a few seconds. I found out a workaround which now   I disable adaptive lighting when turning the light off! :) 

Nevertheless, if I tap on Home app to turn the light off, it stays off. ¯\_(ツ)_/¯

**Comment by felipehjcosta** [comment]
@0x5e 
I've done more tests and the adaptive lighting is working well! :)

My light is connected on my Zemismart hub with HomeKit support and I found out that if a turn it off with Zemismart accessory it works! The problem seems to be on some state not synced between Homebridge and my hub.

An example of both accessories:
![IMG_AC61FCF871B1-1](https://user-images.githubusercontent.com/2865924/230202226-143e6769-781b-495a-840c-29fc9a125df7.jpeg)

**Comment by felipehjcosta** [comment]
When I turn the light off through a scene, this is the log:

```
path = /v1.0/devices/eb7223f24a5afdb744rcsg/commands
query = null
headers = {
  "t": "",
  "client_id": "",
  "nonce": "",
  "Signature-Headers": "client_id",
  "sign": "",
  "sign_method": "HMAC-SHA256",
  "access_token": "",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.36"
}
body = {
  "commands": [
    {
      "code": "switch_led",
      "value": false
    },
    {
      "code": "work_mode",
      "value": "white"
    },
    {
      "code": "temp_value_v2",
      "value": 2
    }
  ]
}
```

```
path = /v1.0/devices/eb7223f24a5afdb744rcsg/commands
data = {
  "result": true,
  "success": true,
  "t": 1681473762564,
  "tid": "42a0446fdabc11edaca32ec9655454eb"
}
```

```
topic = cloud/token/in/a3673ba3cb3908aee6b24312c1f69466
protocol = 4
message = {
  "dataId": "",
  "devId": "",
  "productKey": "e020aaaj",
  "status": [
    {
      "1": false,
      "code": "switch_led",
      "t": "1681473762",
      "value": false
    }
  ]
}
t = 1681473762
```

```
topic = cloud/token/in/a3673ba3cb3908aee6b24312c1f69466
protocol = 4
message = {
  "dataId": "",
  "devId": "",
  "productKey": "e020aaaj",
  "status": [
    {
      "1": true,
      "code": "switch_led",
      "t": "1681473762",
      "value": true
    }
  ]
}
t = 1681473762
```

```
topic = cloud/token/in/a3673ba3cb3908aee6b24312c1f69466
protocol = 4
message = {
  "dataId": "",
  "devId": "",
  "productKey": "e020aaaj",
  "status": [
    {
      "4": 2,
      "code": "temp_value_v2",
      "t": "1681473762",
      "value": 2
    }
  ]
}
t = 1681473762
```

When I turn the light off by tapping the icon, this is the log:

```
path = /v1.0/devices/eb7223f24a5afdb744rcsg/commands
query = null
headers = {
  "t": "1681473946651",
  "client_id": "",
  "nonce": "",
  "Signature-Headers": "client_id",
  "sign": "",
  "sign_method": "HMAC-SHA256",
  "access_token": "",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.36"
}
body = {
  "commands": [
    {
      "code": "switch_led",
      "value": false
    }
  ]
}
```

```
path = /v1.0/devices/eb7223f24a5afdb744rcsg/commands
data = {
  "result": true,
  "success": true,
  "t": 1681473947484,
  "tid": "b0dcf2c4dabc11edaca32ec9655454eb"
}
```

```
topic = cloud/token/in/a3673ba3cb3908aee6b24312c1f69466
protocol = 4
message = {
  "dataId": "",
  "devId": "",
  "productKey": "",
  "status": [
    {
      "1": false,
      "code": "switch_led",
      "t": "1681473947",
      "value": false
    }
  ]
}
t = 1681473947
```

And now the logs when it turn it self on automatically.

```
path = /v1.0/devices/eb7223f24a5afdb744rcsg/commands
query = null
headers = {
  "t": "1681474320694",
  "client_id": "",
  "nonce": "",
  "Signature-Headers": "client_id",
  "sign": "",
  "sign_method": "HMAC-SHA256",
  "access_token": "",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.36"
}
body = {
  "commands": [
    {
      "code": "work_mode",
      "value": "white"
    },
    {
      "code": "temp_value_v2",
      "value": 546
    }
  ]
}
```

```
path = /v1.0/devices/eb7223f24a5afdb744rcsg/commands
data = {
  "result": true,
  "success": true,
  "t": 1681474321519,
  "tid": "8fced55bdabd11edaca32ec9655454eb"
}
```

```
topic = cloud/token/in/a3673ba3cb3908aee6b24312c1f69466
protocol = 4
message = {
  "dataId": "",
  "devId": "",
  "productKey": "e020aaaj",
  "status": [
    {
      "1": true,
      "code": "switch_led",
      "t": "1681474320",
      "value": true
    }
  ]
}
```


```
topic = cloud/token/in/a3673ba3cb3908aee6b24312c1f69466
protocol = 4
message = {
  "dataId": "",
  "devId": "",
  "productKey": "e020aaaj",
  "status": [
    {
      "4": 546,
      "code": "temp_value_v2",
      "t": "1681474321",
      "value": 546
    }
  ]
}
t = 1681474321
```

**Comment by 0x5e** [comment]
@felipehjcosta I noticed there's difference between these, but I think I can't control it. the homebridge api only let's me implement how to turn on/off the light, set brightness, set temperature, separately... will this difference make things wrong?

**Comment by felipehjcosta** [comment]
Understood!

The issue is: the light is turn itself on alone. Below you can find the list of events in reverse order.

Time | Device Event | DP ID | Event Details | Source | Source Details
-- | -- | -- | -- | -- | --
2023-04-18 13:37:56 | publish by cloud api | publish by cloud api | success | open api | cloud2cloud
2023-04-18 13:37:56 | Publish | Mode | White | cloud2cloud |  
2023-04-18 13:37:56 | Publish | Color Temp | 685 | cloud2cloud |  
2023-04-18 13:36:58 | Report | ON/OFF | OFF | device itself |  
2023-04-18 13:36:57 | Report | ON/OFF | ON | device itself |  
2023-04-18 13:36:57 | Report | ON/OFF | OFF | device itself

**Comment by 0x5e** [comment]
@felipehjcosta So the issue is, when the lightbulb is off, send brightness/temp command without on command, should it be turned on, right? does anyone have the official supported homekit lightbulb to test it's behavior?
I'm able to add a filter to remove these command when lightbulb is off, but I'm not sure if it should be like this.

**Comment by felipehjcosta** [comment]
I will try to findo an official supported homekit lightbulb to test it out!

Meanwhile, can I customize this behavior via `deviceOverrides` from [ADVANCED_OPTIONS.](https://github.com/0x5e/homebridge-tuya-platform/blob/develop_1.7.0/ADVANCED_OPTIONS.md)?

**Comment by felipehjcosta** [comment]
I tested with another [lightbulb](https://pt.aliexpress.com/item/1005001993885393.html?spm=a2g0o.order_list.order_list_main.46.1279caa4M8TmQz&gatewayAdapt=glo2bra) and it's everything ok until now! :)

The [original ceiling light](https://pt.aliexpress.com/item/1005004732162990.html?spm=a2g0o.order_list.order_list_main.206.1279caa4M8TmQz&gatewayAdapt=glo2bra) I have posted before has the issue. The thing that stood me out is that the ceiling light has a `power-on behavior` which could be the original source of the problem: 

![IMG_39A1BC3A0B57-1](https://user-images.githubusercontent.com/2865924/234062916-aea788e7-e213-4573-8ba4-aa268e01de3a.jpeg)

Besides that, there is a documentation by Tuya called [Why does my light turn on by itself?](https://support.tuya.com/en/help/_detail/K9hw5sfh4hs0u) which called my attention about the power supply voltage of the device could be unstable. 

I will review the power stuff and if I find any new issue, I'll post here!

**Comment by 0x5e** [comment]
Adaptive Lighting are disabled by default since [v1.7.0-beta.42](https://github.com/0x5e/homebridge-tuya-platform/releases/tag/v1.7.0-beta.42).
It make some light device beep every minute (https://github.com/0x5e/homebridge-tuya-platform/issues/298), and some device not able to turn off :(

**Comment by ZooGuru** [comment]
I'm having trouble enabling adaptive lighting in this newest version. I've looked through what you have available on it and it isn't making much sense to me how to enable adaptive lighting. In the previous version, adaptive lighting worked fine on all the bulbs I have. Can you advise?
