### ISSUE TITLE
Energy usage for plugs returns always 0

### ISSUE THREAD

**Issue by arturlukosek** [0x5e/homebridge-tuya-platform#216]
First of all thank you for adding energy monitoring however I discovered that in my case energy usage returns always 0. I checked in Eve app as well as in Controller for Homekit and consumption doesn't show anything else than 0. Do I miss any additional setup? Screenshots attached from Tuya with current usage , Eve and Controller. 

![IMG_4036](https://user-images.githubusercontent.com/53251964/213921050-dfd56c4f-554d-41a6-9064-33af3c82acec.PNG)
![IMG_4035](https://user-images.githubusercontent.com/53251964/213921052-9c034523-e97e-437e-b58b-5b37ff9892a0.PNG)
![IMG_4034](https://user-images.githubusercontent.com/53251964/213921055-00de126b-dae1-441f-9298-1e57d824d5aa.PNG)

**Comment by 0x5e** [comment]
Can you post the device info json?

**Comment by arturlukosek** [comment]
Not sure if this is what you needed @0x5e. See the screenshot. 
![Screenshot 2023-01-22 at 16 10 46](https://user-images.githubusercontent.com/53251964/213923293-ec15350c-26f0-43cd-b917-c3106eb59cbe.png)

**Comment by 0x5e** [comment]
Thanks for the information. please try if 1.7.0-beta.23 fixes this issue. need to upgrade the plugin then clean accessory cache before testing.

**Comment by arturlukosek** [comment]
@0x5e I have installed the 1.7.0-beta.23 and cleaned cache on one plug. Didn't help unfortunately. 
Next I have added the brand new plug (same manufacture) and I was able to see consumption during the test. 
So I decided to clean caches again from all other plugs (except the new one) and restarted the homebridge. 
After the restart none plugs (including the new one) don't expose the consumption.

**Comment by arturlukosek** [comment]
I tried to remove the device and add again. This helps to show the usage for the moment and then again showing only 0.

**Comment by 0x5e** [comment]
> I tried to remove the device and add again. This helps to show the usage for the moment and then again showing only 0.

I don't know why this still happens. Are there any warning logs during restart homebridge?

**Comment by 0x5e** [comment]
@felipehjcosta energy usage is third-party homekit app (Eve) feature, it's not supported in home app.

**Comment by felipehjcosta** [comment]
Oh, I see.

I downloaded the Eve app and checked that the consumption is displaying 0:
![IMG_F5F78E68B47F-1](https://user-images.githubusercontent.com/2865924/220901050-1190c9bd-24d6-4050-aa90-096b611c6397.jpeg)

**Comment by 0x5e** [comment]
what's the value in homebridge web page? maybe it can be found in accessory page (I don't have device to test this). and what's the value in tuya app?

**Comment by felipehjcosta** [comment]
@0x5e 

These are the details in Homebridge:
![image](https://user-images.githubusercontent.com/2865924/220942558-7f4d8d44-2904-4d78-9511-c4158e38b81d.png)


These are the values in the Tuya app:

![IMG_3224159B5FCD-1](https://user-images.githubusercontent.com/2865924/220941102-10240f0b-3e5c-4b95-92e3-19cf841903e4.jpeg)
![IMG_3224159B5FCD-2](https://user-images.githubusercontent.com/2865924/220941128-fd23555f-3e41-4c40-ae1b-b5f19b9d1ca5.jpeg)

**Comment by 0x5e** [comment]
I know the reason now. There are 4 params, Volt (V), Ampere (A), Watt (W), Kilowatt-hour (kWh). Eve app display the Watt as 0W, which is correct. the Power in tuya app is also 0W. I guess what you actually want is Total Consumption (kWh). I will add this.

**Comment by felipehjcosta** [comment]
@0x5e 

I tested here and got this message below from my wi-fi device:

```
[Tomada Inteligente  TWBR] Unsupported total power unit %p {
  code: 'add_ele',
  mode: 'ro',
  type: 'Integer',
  property: { min: 0, max: 50000, scale: 3, step: 100 }
}
```

On another outlet, a zigbee one, it seemed to work now!
![IMG_B167349BE40B-1](https://user-images.githubusercontent.com/2865924/221165509-59cd04a9-6fc1-4153-8322-e2223dfb5948.jpeg)

**Comment by 0x5e** [comment]
@felipehjcosta I removed some validation so your wifi outlet should work now. It miss the unit `kwh` in the schema.
