### ISSUE TITLE
Please add water pump support 🙏

### ISSUE THREAD

**Issue by kinouzero** [0x5e/homebridge-tuya-platform#22]
Hi, 
I've bought a wifi-water pump but it's not yet supported either by you, the official repo or home assistant plugin, can you add this device type please ?

Thanks

{
      "active_time": 1623229189,
      "biz_type":0,
      "category":"ggq",
      "create_time": 1560491945,
      "icon":"smart/icon/ay15662905541765SKtA/473a410865ed1a3b8b4dce342f41a07d.png",
      "id": "aaaaaaaaaaa",
      "ip": "xxxxxxxxxxxxxxxx",
      "lat": "30.30286857361191",
      "local_key": "xxxxxxxxxxxxx",
      "lon": "120.0639743842656",
      "model":"106W",
      "name":"Wi-Fi Water Timer with Pump",
      "online":true,
      "owner_id": "34794909",
      "product_id": "yfemiswbgjhddhcf",
      "product_name":"Wi-Fi Water Timer with Pump",
	"status":[
		{
			"code":"switch",
			"value":false
		}
	],
      "sub": false,
      "time_zone": "+08:00",
      "uid": "xxxxxxxxxxxxxxxxxxx",
      "update_time": 1625101929,
      "uuid": "xxxxxxxxxxxxxxxxxx"
    }

{
   "category":"ggq",
    "devices":[
        "aaaaaaaaaaa"
    ],
   "functions":[
	{
		"code":"switch",
		"desc":"switch",
		"name":"switch",
		"type":"Boolean",
		"values":"{}"
	}
    ],
    "product_id":"xaabybja"
}

**Comment by 0x5e** [comment]
OK, I will add to my todos

**Comment by 0x5e** [comment]
Please confirm if it's working.

**Comment by kinouzero** [comment]
It's working !! Thanks

**Comment by kinouzero** [comment]
I have this message in homebrige logs

```
[TuyaPlatform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=ae13981e-8b54-4feb-9822-6f1f6b8d1038, t=1667129372, 1970-01-20T07:05:29.372Z
currentMessage: dataId=64dc7d95-c9a3-4f6b-a078-01cc65abd0fe, t=1667129371, 1970-01-20T07:05:29.371Z
```

**Comment by 0x5e** [comment]
This is a warning, MQTT message not very stable. I've already submit a ticket for this in Tuya Platform. It's not related to water pump.

**Comment by 0x5e** [comment]
#32
