### ISSUE TITLE
Add support for Lock Mechanism 

### ISSUE THREAD

**Issue by felipehjcosta** [0x5e/homebridge-tuya-platform#221]
Any plans to include an integration for Lock mechanism?

**Comment by 0x5e** [comment]
There's a incomplete branch: https://github.com/0x5e/homebridge-tuya-platform/tree/feature/lock
Need some device information and test, I don't have lock device.

**Comment by felipehjcosta** [comment]
How can I contribute?

**Comment by felipehjcosta** [comment]
Hey @0x5e I think I found an issue.

The door is closed on Tuya app:
![IMG_1024](https://user-images.githubusercontent.com/2865924/232221697-f0056d57-b7ac-4345-ad5b-1d5aca096745.PNG)

However on Home app is unlocked:
![image](https://user-images.githubusercontent.com/2865924/232221781-918fc578-2b50-46f9-a8dd-fb6bce054e7d.png)

This happens every time I use a manual switch on my Lock mechanism to open it. You can find some log below!

```
{
      "active_time": 1677331326,
      "biz_type": 0,
      "category": "jtmspro",
      "create_time": 1677331326,
      "icon": "smart/icon/ay1553088530507BVYGE/e1b807909ef374a163099cc44278b24c.png",
      "id": "eb752ad11f084e5f5egb0a",
      "ip": "",
      "lat": "",
      "lon": "",
      "model": "IFR 7000 / IFR 7001",
      "name": " IFR 7000 / IFR 7001",
      "online": true,
      "owner_id": "",
      "product_id": "snr3p274",
      "product_name": " IFR 7000 / IFR 7001",
      "status": [
        {
          "code": "unlock_fingerprint",
          "value": 1
        },
        {
          "code": "unlock_password",
          "value": 0
        },
        {
          "code": "unlock_temporary",
          "value": 0
        },
        {
          "code": "unlock_dynamic",
          "value": 0
        },
        {
          "code": "unlock_card",
          "value": 2
        },
        {
          "code": "unlock_key",
          "value": 0
        },
        {
          "code": "open_close",
          "value": false
        },
        {
          "code": "alarm_lock",
          "value": "wrong_finger"
        },
        {
          "code": "residual_electricity",
          "value": 65
        },
        {
          "code": "key_tone",
          "value": "mute"
        },
        {
          "code": "remote_result",
          "value": true
        },
        {
          "code": "hijack",
          "value": false
        },
        {
          "code": "door_opened",
          "value": false
        },
        {
          "code": "unlock_remote",
          "value": 1
        },
        {
          "code": "closed_opened",
          "value": "closed"
        },
        {
          "code": "remote_no_pd_setkey",
          "value": "AAAB"
        },
        {
          "code": "remote_no_dp_key",
          "value": "AAAB"
        },
        {
          "code": "unlock_method_create",
          "value": "Av8BAAEAAgEA"
        },
        {
          "code": "unlock_method_delete",
          "value": ""
        },
        {
          "code": "lock_motor_state",
          "value": true
        },
        {
          "code": "unlock_voice_remote",
          "value": 0
        }
      ],
      "sub": true,
      "time_zone": "-03:00",
      "uid": "",
      "update_time": 1677331326,
      "uuid": ""
    },
```


```
path = /v1.0/devices/eb752ad11f084e5f5egb0a/specifications
query = undefined
headers = {
  "t": "1681560946168",
  "client_id": "",
  "nonce": "",
  "Signature-Headers": "client_id",
  "sign": "",
  "sign_method": "",
  "access_token": "",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.36"
}
body = null
```


```
path = /v1.0/devices/eb752ad11f084e5f5egb0a/specifications
data = {
  "result": {
    "category": "jtmspro",
    "functions": [
      {
        "code": "key_tone",
        "type": "Enum",
        "values": "{\"range\":[\"mute\",\"low\",\"normal\",\"high\"]}"
      },
      {
        "code": "remote_no_pd_setkey",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "remote_no_dp_key",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "unlock_method_create",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "unlock_method_delete",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "lock_motor_state",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "unlock_fingerprint",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "unlock_password",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "unlock_temporary",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "unlock_dynamic",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "unlock_card",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "unlock_key",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "open_close",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_lock",
        "type": "Enum",
        "values": "{\"range\":[\"wrong_finger\",\"wrong_password\",\"wrong_card\",\"wrong_face\",\"tongue_bad\",\"too_hot\",\"tongue_not_out\",\"pry\",\"key_in\",\"power_off\",\"shock\",\"unclosed_time\",\"low_battery\",\"defense\"]}"
      },
      {
        "code": "residual_electricity",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "key_tone",
        "type": "Enum",
        "values": "{\"range\":[\"mute\",\"low\",\"normal\",\"high\"]}"
      },
      {
        "code": "remote_result",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "hijack",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "door_opened",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "unlock_remote",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "closed_opened",
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"closed\",\"unknown\"]}"
      },
      {
        "code": "remote_no_pd_setkey",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "remote_no_dp_key",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "unlock_method_create",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "unlock_method_delete",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "lock_motor_state",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "unlock_voice_remote",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1681560946936,
  "tid": ""
}
```

**Comment by 0x5e** [comment]
I'm still confused about the lock device, the document is not very clear and many status code seems duplicate. from [the docs](https://developer.tuya.com/en/docs/iot/s?id=Kb0o2xhlkxbet):

Standard code | Name | Type | Description
-- | -- | -- | --
door_opened | Door opened | Boolean | {}
open_close | Locking and unlocking event | Boolean | {}
lock_motor_state | Open and closed status of lock | Boolean | {}

do you know which one represents for the door opening status? you can see the status on tuya web debug tool.

**Comment by felipehjcosta** [comment]
DP ID | Event Details | status
-- | -- | -- 
Lock motor state | On | closing
Mechanical Unlock | 0 | opening
Door Status | Opened | opening 
Door Status | Closed | closing
Open Or Close | Closed | closing
Open Or Close | Opened | opening

**Comment by felipehjcosta** [comment]
Hey @0x5e , My door stopped working is this state now:

![image](https://user-images.githubusercontent.com/2865924/233112548-f6224ae4-b756-4624-a97e-f1f9b2ca927a.png)


Time | Device Event | DP ID | Event Details | Source | Source Details
-- | -- | -- | -- | -- | --
2023-04-19 13:18:12 | Report | Open Or Close | Closed | device itself |  
2023-04-19 13:18:08 | Report | Lock motor state | On | device itself |  
2023-04-19 13:18:08 | Report | Mechanical Unlock | 0 | device itself |  
2023-04-19 11:53:14 | Report | Battery | 70% | device itself |  
2023-04-19 11:53:14 | Report | Open Or Close | Opened | device itself |  
2023-04-19 11:53:08 | Report | Fingerprint Unlock | 2 | device itself

**Comment by 0x5e** [comment]
I made a mistake before. the lock/unlock status and door open/close status are different things.
https://developers.homebridge.io/#/service/LockMechanism
For the LockMechanism service, it need two Characteristics: `LockCurrentState` and `LockTargetState`. (forget about the door open/close state)

can you tell me which one DP ID accurately represents for the lock/unlock status?

**Comment by felipehjcosta** [comment]
Lock status
DP ID | Event Details | Source
-- | -- | -- 
Open Or Close | Closed | device itself
Door Status | Closed | device itself


Unlock status
DP ID | Event Details | Source
-- | -- | -- 
Mechanical Unlock | 0 | device itself
Fingerprint Unlock | 1 | device itself
Open Or Close | Opened | device itself
Door Status | Opened | device itself


I've noticed that when the door mechanism lock by itself after some time, it doesn't generate any event in the logs.

**Comment by 0x5e** [comment]
if no event, what about switch to dp instructions?

**Comment by felipehjcosta** [comment]
@0x5e 

Well, I've noticed that even on Tuya app the door was acting buggy... 🙃

So, I disconnected, wiped all data and set up again my lock mechanism. It's working again on Tuya app! After that, I've switched to dp instructions too and on Home app the accessory seems to be working very well now!

It's reacting according when unlock or lock.

![IMG_1041](https://user-images.githubusercontent.com/2865924/233795916-b49f39ea-544e-4592-aac7-44725542e281.jpg)

![IMG_1042](https://user-images.githubusercontent.com/2865924/233795959-1b108327-3700-4a7d-a05e-da1fbc24cb9f.jpg)

if I find any new issue, I'll post here! Thank you very much!

**Comment by felipehjcosta** [comment]
Hey @0x5e an update: I'm able to control the door at some point and set up some automations.

However, I realized that the state below is actually `unlocking` and not `unlocked`. 🫠
Can we find a fix for this?

![](https://user-images.githubusercontent.com/2865924/233795916-b49f39ea-544e-4592-aac7-44725542e281.jpg)

**Comment by felipehjcosta** [comment]
I've tried the [v1.7.0-beta.38](https://github.com/0x5e/homebridge-tuya-platform/releases/tag/v1.7.0-beta.38) version.

**Comment by felipehjcosta** [comment]
Here is the table of instructions

DP Instruction | Standard Instruction
-- | --
unlock_fingerprint | unlock_fingerprint
unlock_password | unlock_password
unlock_temporary | unlock_temporary
unlock_dynamic | unlock_dynamic
unlock_card | unlock_card
unlock_key | unlock_key
open_close | open_close
alarm_lock | alarm_lock
residual_electricity | residual_electricity
key_tone | key_tone
remote_result | remote_result
remote_unlock_switch | -
password_creat | -
password_delete | -
password_update | -
password_disable | -
password_enable | -
hijack | hijack
door_opened | door_opened
password_reset | -
unlock_remote | unlock_remote
closed_opened | closed_opened
remote_no_pd_setkey | remote_no_pd_setkey
remote_no_dp_key | remote_no_dp_key
unlock_method_create | unlock_method_create
unlock_method_delete | unlock_method_delete
lock_motor_state | lock_motor_state
single_use_password | -
unlock_voice_remote | unlock_voice_remote


We can use the following dp codes to represent `LockTargetState`: `open_close` and `closed_opened`.

**Comment by 0x5e** [comment]
@felipehjcosta could you help me test with this locally? in the `node_modules/@0x5e/homebridge-tuya-platform/dist/accessory/LockAccessory.js` line 8:
```
LOCK_CURRENT_STATE: ['door_opened', 'lock_motor_state'],
```
replace the array `['door_opened', 'lock_motor_state']` with `['open_close']`, `['closed_opened']` or others, find which one works well

**Comment by felipehjcosta** [comment]
@0x5e  👉  #297

**Comment by appvitor** [comment]
Hello, I also got a smart lock that shows like unsupported by the plugin.
My lock has a built in camera with flash to take pictures and send to the app when someone rings the door bell button.
And for whatever unknown reason, it shows the ability for "Facial unlock"... I haven't switched to DP Instructions yet, really afraid that the device stops working if changed...

[7/24/2023, 12:30:15 PM] [Tuya] [Door] Product Category: jtmspro
[7/24/2023, 12:30:15 PM] [Tuya] [Door] Missing one of the required schema: [ 'open_close', 'closed_opened', 'lock_motor_state' ]
[7/24/2023, 12:30:15 PM] [Tuya] [Door] Please switch device control mode to "DP Insctrution", and set `deviceOverrides` manually.
[7/24/2023, 12:30:15 PM] [Tuya] [Door] Detail information: https://github.com/0x5e/homebridge-tuya-platform#faq
[7/24/2023, 12:30:15 PM] [Tuya] [Door] Existing schema: [
  {
    code: 'alarm_lock',
    mode: 'ro',
    type: 'Enum',
    property: {
      range: [
        'wrong_finger',  'wrong_password',
        'wrong_card',    'wrong_face',
        'tongue_bad',    'too_hot',
        'unclosed_time', 'tongue_not_out',
        'pry',           'key_in',
        'low_battery',   'power_off',
        'shock',         'defense',
        [length]: 14
      ]
    }
  },
  {
    code: 'battery_state',
    mode: 'ro',
    type: 'Enum',
    property: { range: [ 'high', 'medium', 'low', 'poweroff', [length]: 4 ] }
  },
  { code: 'doorbell', mode: 'ro', type: 'Boolean', property: {} },
  { code: 'hijack', mode: 'ro', type: 'Boolean', property: {} },
  { code: 'initiative_message', mode: 'ro', type: 'Raw', property: {} },
  { code: 'photo_again', mode: 'rw', type: 'Boolean', property: {} },
  { code: 'remote_no_dp_key', mode: 'rw', type: 'Raw', property: {} },
  {
    code: 'remote_no_pd_setkey',
    mode: 'rw',
    type: 'Raw',
    property: {}
  },
  {
    code: 'unlock_app',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_card',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_face',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_fingerprint',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_password',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_request',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  {
    code: 'unlock_temporary',
    mode: 'ro',
    type: 'Integer',
    property: { min: 0, max: 999, scale: 0, step: 1 }
  },
  [length]: 15
]
[7/24/2023, 12:30:15 PM] [Tuya] Unsupported device: Door.

**Comment by 0x5e** [comment]
@appvitor control mode only changes the way that tuya platform controls device, you can change back at any time.

**Comment by appvitor** [comment]
I just changed to DP Instructions, before there was always a tile created for the lock on the Home app saying that the device is not compatible, after changing it, it's gone.

There has also been a change in the table of instructions, with two more been added: remote_no_pd_setkey and remote_no_dp_key

**Comment by matiasfa** [comment]
@appvitor did you fix the issue Missing one of the required schema: [ 'open_close', 'closed_opened', 'lock_motor_state' ]?
I am having same issue cant fix it

**Comment by nevirous** [comment]
do you fix this already? @matiasfa @appvitor @0x5e  , i facing the same error

**Comment by titeet** [comment]
Hello guys,

i have a k1 pro max wifi smart lock which support tuya app, but the thing is that the cartoon box showing is also showing its support ttlock app, but i am unable to add the smart lock through the ttlock app, and other thing i cant unlock remotely without ringing the bell, so i have tried to build home assistant and was successfully add extend tuya and was able to control the smart lights only and couldn’t still control the smart lock, and the lock showing its online.
is there a way to unlock it remotely without ringing the bell on tuya app.

note that i have tested to ring the bell and unlock it from home assistant but it didn’t unlock.

thanks in advance.
