### ISSUE TITLE
Login failed. code=1106, msg=permission deny

### ISSUE THREAD

**Issue by Lukas13kiko** [0x5e/homebridge-tuya-platform#224]
- [ ] I've read the [Readme - FAQ](https://github.com/0x5e/homebridge-tuya-platform#faq) and [Readme - Troubleshooting](https://github.com/0x5e/homebridge-tuya-platform#troubleshooting) section.

**Describe the bug**
Following Error: Login failed. code=1106, msg=permission deny

Im sure everything is correct 

Changed PW to a simpler one.

**Expected behavior**
Login

**Screenshots**
![image](https://user-images.githubusercontent.com/123885631/215336042-1be7193d-2f38-4d82-91fd-03a3e2d25dae.png)

**Device info**
Raspberry Pi 3

**Comment by 0x5e** [comment]
Can it be reproduced by revert original password? If can, might be plugin side issue, if not, might be server side issue.
