### ISSUE TITLE
Add support for BRILLIANT SMART UNIVERSAL DOOR CONTROL

### ISSUE THREAD

**Issue by markywarky** [0x5e/homebridge-tuya-platform#228]
This device is mostly working nicely in DP Instruction mode. However, it appears in the Home app as a window instead of a door, and therefore doesn't get displayed automatically in CarPlay like a garage door is supposed to.

Any and all help appreciated.

MQTT log:

[1/20/2023, 9:19:20 PM] [TuyaPlatform] [Garage Door] [AccessoryInformation/undefined/StatusActive] Update value: false => true
[1/20/2023, 9:19:20 PM] [TuyaPlatform] [Garage Door] Unknown CurrentPosition: fclose
[1/20/2023, 9:19:20 PM] [TuyaPlatform] [Garage Door] [Window/undefined/CurrentPosition] Update value: 0 => 50
[1/20/2023, 9:19:20 PM] [TuyaPlatform] [Garage Door] [Window/undefined/PositionState] Update value: 0 => 2
[1/20/2023, 9:19:20 PM] [TuyaPlatform] [Garage Door] Unknown TargetPosition: fclose
[1/20/2023, 9:19:20 PM] [TuyaPlatform] [Garage Door] [Window/undefined/TargetPosition] Update value: 0 => 50
[1/20/2023, 9:19:20 PM] [TuyaPlatform] [Garage Door] [Window/undefined/StatusActive] Update value: false => true
[1/20/2023, 9:19:23 PM] [TuyaPlatform] [Garage Door] Unknown CurrentPosition: fclose
[1/20/2023, 9:19:23 PM] [TuyaPlatform] [Garage Door] Unknown TargetPosition: fclose
[1/20/2023, 9:19:27 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/f49cea3658ed812f801dde3dbeaae9f9
protocol = 4
message = {
  "dataId": "xxx",
  "devId": "xxx",
  "productKey": "xxx",
  "status": [
    {
      "104": 2346,
      "code": "cur_voltage",
      "t": "1674213566",
      "value": 2346
    }
  ]
}
t = 1674213566
[1/20/2023, 9:19:28 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/f49cea3658ed812f801dde3dbeaae9f9
protocol = 4
message = {
  "dataId": "xxx",
  "devId": "xxx",
  "productKey": "xxx",
  "status": [
    {
      "22": 2332,
      "code": "cur_voltage",
      "t": "1674213567",
      "value": 2332
    }
  ]
}
t = 1674213567
[1/20/2023, 9:19:36 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/f49cea3658ed812f801dde3dbeaae9f9
protocol = 4
message = {
  "dataId": "xxx",
  "devId": "xxx",
  "productKey": "xxx",
  "status": [
    {
      "104": 2329,
      "code": "cur_voltage",
      "t": "1674213575",
      "value": 2329
    }
  ]
}
t = 1674213575

**Comment by 0x5e** [comment]
It can be changed in home app, in the setting page, click the icon.

**Comment by markywarky** [comment]
> It can be changed in home app, in the accessory setting page, click the icon.

Nice! I didn't realise the icon could be changed, although I should have by the orange box around it.

Unfortunately, changing the icon does not seem to change the functionality, i.e. the garage door still does not appear in CarPlay.

I used to have this working as a [garage-door-kogan accessory](https://github.com/iRayanKhan/homebridge-tuya/pull/198) in [iRayanKhan](https://github.com/iRayanKhan) / [homebridge-tuya](https://github.com/iRayanKhan/homebridge-tuya), although configuring that plugin is a lot more work.

Here's my device schema [that I listed back then](https://github.com/iRayanKhan/homebridge-tuya/issues/169):
```
[TuyaAccessory] Sending first query to Garage door (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Garage door (ECONNRESET)
[TuyaAccessory] Sending first query to Garage door (3.3)
[[TuyaAccessory] Heard back from Garage door with command 10
[12/29/2020, 2:04:23 PM] [TuyaLan] Ready to handle Garage door (GarageDoor:3.3) with signature {"101":"fclose","102":"closed","104":100,"105":false,"110":"invalid","112":100,"113":true,"118":"invalid","120":100,"121":false,"125":"GD811"}

[TuyaAccessory] Heard back from Garage door with command 8
[TuyaAccessory] GarageDoor changed: {"101":"fclose","102":"closing","104":100,"105":false,"110":"invalid","112":100,"113":true,"118":"invalid","120":100,"121":false,"125":"GD811"}

[TuyaAccessory] Heard back from Garage door with command 8
[TuyaAccessory] GarageDoor changed: {"101":"fclose","102":"closed","104":100,"105":false,"110":"invalid","112":100,"113":true,"118":"invalid","120":100,"121":false,"125":"GD811"}

[TuyaAccessory] Sending Garage door {"1":true}

```

**Comment by 0x5e** [comment]
the device schema looks more like a "window/window covering" rather than "garage door", but it doesn't matter.
changing icon is only change the icon, doesn't change the behavior.
the problem is because, from tuya product documentation of window: https://developer.tuya.com/en/docs/iot/f?id=K9gf46syrs2tr
the control schema should have enum of "open/stop/close", but your's are "fclose". you can use advanced options to override them, then it should work.

**Comment by 0x5e** [comment]
I didn't use homekit in carplay before, and haven't seen it, does it requires the accessory type? if it must be the "garage door opener", you need a complete override with category code, and each schema into the real "garade door" product in tuya, and onGet/onSet handler in one-line javascript code, it need a lot of work..

**Comment by markywarky** [comment]
> I didn't use homekit in carplay before, and haven't seen it, does it requires the accessory type?

No idea. Garage door Open/Close button comes up automatically in CarPlay Dashboard view when you come within approximately 1 km of home. It's a really nice feature, very handy.

![](https://2672686a4cf38e8c2458-2712e00ea34e3076747650c92426bbb5.ssl.cf1.rackcdn.com/2019-06-04-08-43-39.jpeg)

> if it must be the "garage door opener", you need a complete override with category code, and each schema into the real "garade door" product in tuya, and onGet/onSet handler in one-line javascript code, it need a lot of work..

I think this is beyond me :(

**Comment by 0x5e** [comment]
It looks like a siri shortcut, special prepared for the garage door, looks cool :)
It's sad that the manufactor of "BRILLIANT SMART UNIVERSAL DOOR CONTROL" mark the product with the wrong category, causing this trouble :(

**Comment by markywarky** [comment]
Thanks @0x5e. Appreciate your help and quick responses.
