### ISSUE TITLE
No repsonse outlet and switches

### ISSUE THREAD

**Issue by yk1n9** [0x5e/homebridge-tuya-platform#230]
I have 5 cameras that connected and about 10 outlet and 2 swtiches connected to homebridge. Cameras are streaming live and sharing screenshot whereas outlets and switches are not showing no reponse at all any advice to fix this would be appreciated.

**Comment by bFollon** [comment]
Do you have logs from the homebridge-tuya-platform?
Is any error displayed?

Please take a look at the [troubleshooting](https://github.com/0x5e/homebridge-tuya-platform#troubleshooting) section of the documentation to try and get more information about your outlets and switches.

**Comment by yk1n9** [comment]
This fixed itself. No clue how
