### ISSUE TITLE
Add support for SGW03  WiFi单路阀门

### ISSUE THREAD

**Issue by 852tomhk** [0x5e/homebridge-tuya-platform#231]
**Device info**
Please refer to the troubleshooting section to get device list info. https://github.com/0x5e/homebridge-tuya-platform#troubleshooting
[TuyaDeviceList.az1666270578723iKRja.json.txt](https://github.com/0x5e/homebridge-tuya-platform/files/10569391/TuyaDeviceList.az1666270578723iKRja.json.txt)

MQTT logs
 {
      "active_time": 1667356295,
      "biz_type": 18,
      "category": "sfkzq",
      "create_time": 1667279878,
      "icon": "smart/icon/ay1501578980436KOuNc/16530111267450959024b.png",
      "id": "eb59778165c72ec8daukxn",
      "ip": "218.102.188.125",
      "lat": "22.2925",
      "local_key": "09a8df1818f766a8",
      "lon": "114.2694",
      "model": "SGW03",
      "name": "SGW03  WiFi单路阀门",
      "online": false,
      "owner_id": "86004188",
      "product_id": "rzklytdei8i8vo37",
      "product_name": "SGW03  WiFi单路阀门",
      "status": [
        {
          "code": "switch",
          "value": false
        },
        {
          "code": "battery_percentage",
          "value": 64
        },
        {
          "code": "weather_delay",
          "value": "cancel"
        },
        {
          "code": "countdown",
          "value": 0
        },
        {
          "code": "work_state",
          "value": "idle"
        },
        {
          "code": "use_time_one",
          "value": 180
        }
      ],

**Comment by 0x5e** [comment]
committed at f00d006c8869ff4114d2bb55dda8bfa1737032b8. please try.
