### ISSUE TITLE
Unable to control fan speed in fan switch (fskg). 

### ISSUE THREAD

**Issue by pratikparmar24292** [0x5e/homebridge-tuya-platform#233]
I am unable to control fan speed in fan switch(fskg). it shows slider but can't control from it.

**Comment by 0x5e** [comment]
need some detail information. please post some device info and logs according to readme.

**Comment by pratikparmar24292** [comment]
[2/12/2023, 10:50:18 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/d7e7edea79e03bf056eaog/commands
data = {
  "result": true,
  "success": true,
  "t": 1676222418271,
  "tid": "858a6a48aaf911edbb72fab769b65350"
}
[2/12/2023, 10:50:18 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/508429e5071b0dd7aec366cdc04e3ade
protocol = 4
message = {
  "dataId": "349de8a8-c65a-4e10-a6cd-7af60a8db7b7",
  "devId": "d7e7edea79e03bf056eaog",
  "productKey": "ewdmma4uccqydpmj",
  "status": [
    {
      "1": false,
      "code": "switch",
      "t": "1676222417",
      "value": false
    }
  ]
}


and can't even control speed slider. above is the log.

**Comment by 0x5e** [comment]
https://github.com/0x5e/homebridge-tuya-platform#troubleshooting

need `TuyaDeviceList.{uid}.json` file. and also you can check if the device exist speed level schema.

**Comment by pratikparmar24292** [comment]
where can I find this .json file? can you tell me exact location? also where to check speed level schema? 
Thanks in advance.

**Comment by pratikparmar24292** [comment]
> https://github.com/0x5e/homebridge-tuya-platform#troubleshooting
> 
> need `TuyaDeviceList.{uid}.json` file. and also you can check if the device exist speed level schema.

[Archive.zip](https://github.com/0x5e/homebridge-tuya-platform/files/10830443/Archive.zip)

there are two files I have attached in zip folder.  also where can I find speed level schema?

Thanks in advance.

**Comment by 0x5e** [comment]
schema is in json file's `schema` section. I see yours don't have them, you can try change control mode to see if it appears.

**Comment by pratikparmar24292** [comment]
> schema is in json file's `schema` section. I see yours don't have them, you can try change control mode to see if it appears.

how to change control mode?

**Comment by mattwelch-toast** [comment]
I also cannot control my fan speed. Whatever I set it to in the Home it, the fan itself is at 100%. (The home app indicates the speed I asked for on the other hand.)
 
 Looking at my device list (attached), I do see the fan_speed and fan_speed enum in the schema, and they look right. Those same enums in the status section look a little odd though?

[TuyaDeviceList.json.gz](https://github.com/0x5e/homebridge-tuya-platform/files/10951650/TuyaDeviceList.json.gz)

**Comment by 0x5e** [comment]
@mattwelch-toast a device should have only one fan speed related schema, I see your device have two, I guess one of those is a fake schema, the plugin can't differ them. you can use tuya web debug tool to confirm which one is useful and which one is not, then hide the not using one, with plugin config. then clean accessory cache & restart.

@pratikparmar24292 please see readme completely, or maybe you two have the same case.

**Comment by 0x5e** [comment]
@mattwelch-toast at the beginning tuya didn't have the strict control of unified product definition, with products number grow up, it faced the problem like google's android system: fragmentation (I'm not sure if the translation is correct). so, many products like this... have odd schema...

**Comment by rdurfee** [comment]
I also have an issue controlling the fan speed. The slider only lets you choose on or off. There are supposed to be 6 speeds, and I see my json file set up is different than the ones previously reported.

In the IoT API devices page, I can send settings and it works as expected, with the fan_speed_percent setting 1-6, which seems to be how the json file describes it.

[TuyaDeviceList.az1680296355207WOkF9.json.zip](https://github.com/0x5e/homebridge-tuya-platform/files/11127274/TuyaDeviceList.az1680296355207WOkF9.json.zip)

**Comment by 0x5e** [comment]
@rdurfee got it. thanks, I will support it.
