### ISSUE TITLE
Add support for Air Conditioner IR controller

### ISSUE THREAD

**Issue by felipehjcosta** [0x5e/homebridge-tuya-platform#234]
**Device info**
I have a [air conditioner IR controller](https://pt.aliexpress.com/item/1005004862669768.html?pdp_npi=2%40dis%21BRL%21R%24%20328%2C71%21R%24%20147%2C91%21%21%21%21%21%402101d1b116762107034296071ebcba%2112000031431791555%21btf&_t=pvid%3A02df20c7-2ee1-463c-8817-c4190c0f6df2&afTraceInfo=1005004862669768__pc__pcBridgePPC__xxxxxx__1676210703&spm=a2g0o.ppclist.product.mainProduct&gatewayAdapt=glo2bra) that is not supported by the plugin. I installed the beta version which introduced support to [Air Conditioner](https://github.com/0x5e/homebridge-tuya-platform/pull/160) hoping to try it out. You can check HomeBridge log below .

![image](https://user-images.githubusercontent.com/2865924/218315871-62944fc9-2eab-4629-b0a0-ee972c1cbf6d.png)

Is there any way I can help to integrate this device?

**Comment by 0x5e** [comment]
IR/RF device is not supported yet. I will continue to work when I'm free, this month or next month. Sorry I'm busy these days.

**Comment by felipehjcosta** [comment]
Thanks!

**Comment by 0x5e** [comment]
Added in 1.7.0-beta.26, not fully tested, please let me know if it's not working, thanks :)

**Comment by felipehjcosta** [comment]
I have tested here and it's still not working 😢 
![image](https://user-images.githubusercontent.com/2865924/218916058-5a1cac04-5bec-4fc2-9873-e7dfd1792598.png)

**Comment by 0x5e** [comment]
See: https://github.com/0x5e/homebridge-tuya-platform/issues/218
