### ISSUE TITLE
Clkg not supported, although in list

### ISSUE THREAD

**Issue by lars05** [0x5e/homebridge-tuya-platform#24]
Hi, 

I have 3 curtain switches (CLKG). They appear in HomeKit shown as "not supported".

**Comment by 0x5e** [comment]
> Hi, 
> 
> 
> 
> I have 3 curtain switches (CLKG). They appear in HomeKit shown as "not supported". 
> 
> 

Hi, can you try to clean homebridge accessory cache from web gui settings? I'm not sure if it is cache issue or something. If problem still happen, please provide your device's detail info.

**Comment by lars05** [comment]
I can confirm this didn't help. 

https://www.amazon.de/gp/product/B07MXT9Y2D/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1
According to Tuba IoT platform the category is "clkg". Smart Curtain Switch

**Comment by 0x5e** [comment]
Can you take a picture of `Standard Instruction Set` and `Standard Status Set` page ? So I can see what difference between your device and my virtual device.

**Comment by 0x5e** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5144674/198835411-7dd10d46-bb57-424e-8271-e0cf83bcb3db.png">

**Comment by lars05** [comment]
Status and instruction page look the same

<img width="1426" alt="Bildschirm­foto 2022-10-29 um 16 00 40" src="https://user-images.githubusercontent.com/45712888/198835727-0a2892b0-d085-4c51-a9ce-af0ef915d28c.png">

**Comment by 0x5e** [comment]
Ok, all juse one `control` ?

**Comment by lars05** [comment]
Yes there seems to be no calibration or percentage control

**Comment by 0x5e** [comment]
Homebridge requires `Window Covering` must have `Current Position`, `Position State`, `Target Position`.
If only `control` exist, do you have any ideas of how to handling position issue? Or maybe we should treat it as a dual-switch ?

**Comment by lars05** [comment]
Yes maybe that would solve it, but as a dual switch I think it would only provide "open" and "close", not "stop", right?

**Comment by 0x5e** [comment]
Yes, swicth is not the perfect solution, some plugin will treate device fan's level (low/medium/high) as three switches, if low is open, other two will be closed. But if all closed...

**Comment by 0x5e** [comment]
For the curtain switches:

One way:
Set the slider with step 50, so it only can be 0%, 50%, 100%, and 0 means close, 50 stop, 100 open.

Another:
as described before, add 3 switches represents close, stop and open, If the `on` switch was changed to off, let it back to on again.

**Comment by lars05** [comment]
I think the slider option would be the best applicable, this way it could also display the correct status wether its opened or closed

**Comment by 0x5e** [comment]
Yes, but 50% means stop may confuse users. But I can't think way better than this. I will update later.

**Comment by 0x5e** [comment]
When you close the curtain, will it be stoped by device it self and change state to `stop`?

**Comment by lars05** [comment]
![Bildschirm­foto 2022-10-29 um 18 34 00](https://user-images.githubusercontent.com/45712888/198842827-2dddb7c3-757a-4737-ac29-e7039ab62fa2.png)

**Comment by lars05** [comment]
Yes, changes to stop all by itself

**Comment by 0x5e** [comment]
Please try the latest version

**Comment by lars05** [comment]
Unfortunately devices don't appear in HomeKit at all, although they are recognized by protocol 
![BDC56EDA-0CF7-473E-9DCF-675CCB579335](https://user-images.githubusercontent.com/45712888/198868936-5f8c39b0-0a84-4b92-a237-fab1f7733c74.png)

**Comment by 0x5e** [comment]
Try clean accessory cache and restart, I have experienced too during the develop, and not sure why.

**Comment by lars05** [comment]
Works pretty well. 
Only downside is that although opened or fully closed it shows as "50% opened" as the system sets itself to "stop". 
But guess we gonna have to live with that :)

**Comment by 0x5e** [comment]
Yes :)

**Comment by lars05** [comment]
Thanks for your support
