### ISSUE TITLE
Add support for overriding device types

### ISSUE THREAD

**Issue by AxelDreemurr** [0x5e/homebridge-tuya-platform#25]
It would be awesome to have, say, a 3 gang switch show up as three individual Lightbulbs in HomeKit instead of a Switch with 3 buttons (as it does now) as that would allow for assigning each Lightbulb to a different room in the same way that the plugin [https://github.com/milo526/homebridge-tuya-web](Url) does.

It'd be much appreciated if you can implement this on this new version of the official plugin. Thanks in advance.

**Comment by 0x5e** [comment]
Thanks for the feedback. The Home App has already support to change switch's type and icon into light/fan/switch. You can change it in the setting.

the second one I may consider later, this version aims to fix issue and add basic function support for as much devices as I can, advance functions may in low piority.

**Comment by 0x5e** [comment]
Thanks for the feedback, however change the device type is not just so easy like changing an icon. It may not be compatible with your "kg" door opener when it was treated as door opener. Maybe your case it works, but not 100% case it can work. Then It will cause alot of trouble then.

**Comment by Fabi3n31** [comment]
I used @milo526/homebridge-tuya-web v1.1.2 plugin that allows a nice overriding for several type of devices (plugin has other limitations). It worked maybe not with 100% of the regular door opener but still it was much better than having a switch in home app.

**Comment by 0x5e** [comment]
I've read the @milo526/homebridge-tuya-web readme of [overruling-device-types](https://github.com/milo526/homebridge-tuya-web/#overruling-device-types)
It says 2 examples of using this feature.
1. dimmers reported as `light` but don't support hue and saturation.
2. outlets reported as `switch`.

Now beta version can correctly process lights and if the specific light such as dimmer, which don't support hue, saturation, or color temperature, it won't show on the HomeKit. And the second has been fixed, now outlets will be shown as `outlet`.

@Fabi3n31 I'm sorry currently It can't be supported with a small modification. After releasing current 1.6.0 version, we can discuss how to complete this without large modification and influence other devices code readability and stability.

**Comment by 0x5e** [comment]
I've come up an idea. The difficult for me is how to transform an unknown device into a known device. For example, a normal light have `switch` as power, `bright` as brightness. 

For the unknown device who wants to be treated as light, if the user configures a status code map in the config, it can be done then.

**Comment by 0x5e** [comment]
I've submit the 1.7.0-beta.5 with device override feature, please see readme and advance configs if it can suport your requirements.
