### ISSUE TITLE
Cant refresh Authorization Token Management

### ISSUE THREAD

**Issue by Thijsjuh92** [0x5e/homebridge-tuya-platform#250]
### Prerequisite

- [X] Yes

### Version

1.7.0 beta

### Device Control Mode

Standard Instruction

### Other Infomations

In Tuya IoT can’t refresh the free trial. It expired on the 27 of February

**Comment by 0x5e** [comment]
What does can't mean? Found nowhere to extend the trial or no response for trial?

**Comment by Thijsjuh92** [comment]
Had contact with Tuya Support Engineer.

Don't know what he changed but it works again..

Strange thing is, Authorization Token Management is still expired.. see attached picture.

![image](https://user-images.githubusercontent.com/34923899/222885996-4887d7f9-2179-4b18-9e09-8265ca46c53e.jpeg)

![image](https://user-images.githubusercontent.com/34923899/222886000-69ac1ff7-4146-4c4e-9e3f-87b0987dd0dc.jpeg)

**Comment by 0x5e** [comment]
I can't help with tuya platform issues :( you can submit the ticket on the platform.
