### ISSUE TITLE
Security System unsupported

### ISSUE THREAD

**Issue by githubnavigator** [0x5e/homebridge-tuya-platform#256]
### Prerequisite

- [X] Yes

### Version

1.7.0-beta.32

### Device Infomation JSON File

```json
"active_time": 1628476015,
    "biz_type": 18,
    "category": "wfcon",
    "create_time": 1628476015,
    "icon": "smart/icon/ay1524194438166Zg2hZ/8aef12f2f551213109d9e2d54f2d0354.jpg",
    "id": "",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "DP-W2.1",
    "name": "Security System",
    "online": true,
    "owner_id": "",
    "product_id": "bsck4bhwubkpggmb",
    "product_name": "Alarm Security System",
    "status": [],
    "sub": false,
    "time_zone": "-07:00",
    "uid": "",
    "update_time": 1654019479,
    "uuid": "baa29f26f32a64e1",
    "schema": []
```

### Device Control Mode

None

### Other Infomations

I have a security system (https://www.amazon.com/gp/product/B08YYD28L1) which is recognized correctly by the Smart Life app. In the Tuya developer interface, this device appears as the following:

Product Name
RF 防区版网关
Product Category
wfcon

However, Homebridge produces these errors on attempting to load the device:

[3/9/2023, 10:05:20 PM] [TuyaPlatform] [TuyaDeviceManager] Get device specification failed. devId = ***********, code = 2009, msg = not support this device
[3/9/2023, 10:05:21 PM] [TuyaPlatform] Unsupported device: Security System.

I have enabled debug mode and see MQTT messages from other devices, but none from this one. 

In Apple Home, a "Security System" device gets loaded, but it says "Not Supported" and I'm unable to turn it on or off (which makes sense, as this device doesn't come up under Accessories list in Homebridge).

Does anyone have any advice on how I could get this working? Thank you!

**Comment by githubnavigator** [comment]
Thank you, yes...in the Tuya Developer site's product details section, I see that the "Product Type" is "Connector". I set the Control Instruction Mode to "DP Instruction" and see a long list of "DP Instructions" on the left and matching "Standard Instructions" to the right, but after I read the Advanced Options page on overrides (https://github.com/0x5e/homebridge-tuya-platform/blob/develop_1.7.0/ADVANCED_OPTIONS.md) I couldn't figure out how to proceed. These are the codes that appear in the DP Instructions (the exact same list appears on the "Standard Instructions" side):

true
bj
kg
bjsc
bjy
yl
xxpj
ykqts
cgqts
cmys
hjys
y1
pjts
c1
pjls

When I hover over the instruction "bj", I get a pop up withe following, and I'm not sure what I should be typing into the overrides dialog:

Code:bj 
Function Name:Alarm 
Data Transfer Type:Send & report 
Data Type:Boolean 
Remarks:bj

I'm sorry -- clearly I'm new to this and don't know what I am doing...I'm trying! :)

**Comment by 0x5e** [comment]
It's like a guess game.. first you can see the security system document to see what schema it has, then you can use tuya web debug tool to try your device schema one by one, to test each one's feature. then add plugin configs to overwrite their code. good luck :)

**Comment by githubnavigator** [comment]
Hello again. Thanks for pointing me in the right direction. I set the device type to "mal" (Alarm Host - [Tuya documentation here](https://developer.tuya.com/en/docs/iot/alarm-hosts?id=K9gf48r87hyjk)). 

I then added the two required overrides -- "sos_state" (Boolean) and "master_mode". Adding the sos_state override was straightforward, and it works correctly, with my iPhone alerting me immediately when the alarm is tripped. Excellent! However, I'm not sure what to do with the master_mode control code. In the Tuya app, the enum options are "1", "2", and "3", which correspond with "arm", "disarmed", and "home". 

Can you please let me know how to set up the override to remap between "1" "2" and "3" to "arm" "disarmed" and "home"?

Thanks!

----------------------

Tuya mal documentation for "master_mode" has {“range”:[“disarmed”, “arm”, “home”, “sos”, “work”, “play”]}

What I have entered in my overrides is the following:

"code": "true",
"newCode": "master_mode",
"type": "Enum",
"property": {
      "range": [
           "1",
           "2",
           "3"
      ]

**Comment by 0x5e** [comment]
the map between 1/2/3 and arm/disarmed/home can be like this:
```json
"deviceOverrides": [{
        "id": "your_device_id",
        "schema": [{
          "code": "master_mode",
          "onGet": "{'1': 'arm', '2': 'disarmed', '3': 'home'}[value] || 'default_value'",
          "onSet": "{'arm': '1', 'disarmed': '2', 'home': '3'}[value] || 'default_value'",
        }]
      }
```

Not tested, the `default_value` on `onGet` can be `arm/disarmed/home`, on `onSet` can be `1/2/3`, as I'm not familar with the security system logic, you can determine it.

**Comment by githubnavigator** [comment]
Ah, I see where you're going with this. Very helpful. I've tried several variations of this, but I get a syntax error, and I'm not sure whether it's because of the syntax in the override snippet I'm using or if there's something off in SecuritySystemState.ts or one of the other files :
```
[3/25/2023, 10:24:22 AM] SyntaxError: Unexpected token ':'
    at SecuritySystemAccessory.OverridedBaseAccessory.eval (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/BaseAccessory.ts:238:58)
    at SecuritySystemAccessory.getOverridedStatus (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/BaseAccessory.ts:294:27)
    at SecuritySystemAccessory.getStatus (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/BaseAccessory.ts:305:17)
    at /var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/characteristic/SecuritySystemState.ts:64:38
    at SecuritySystemAccessory.updateAllValues (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/BaseAccessory.ts:113:46)
```

Currently what I have is this:

```json
        "deviceOverrides": [
            {
                "id": "xxxxxxxxxxxxxxxx",
                "category": "mal",
                "schema": [
                    {
                        "code": "true",
                        "newCode": "master_mode",
                        "onGet": "{1: 'arm', 2: 'disarmed', 3: 'home'}[value] || 'home'",
                        "onSet": "{'arm': 1, 'disarmed': 2, 'home': 3}[value] || '3'"
                    },
                    {
                        "code": "bj",
                        "newCode": "sos_state",
                        "type": "Boolean"
                    }
                ]
            }
        ]
``` 
The bj > sos_state override works, but the true > master_mode override does not. (Also, as a sidenote, the DP code for master_mode *really is* actually called "true" for whatever reason. I don't understand why they didn't choose something else, but that's just what they decided to call it.)

Is the onGet JSON logic you have here something like, "If you get '1', then return 'arm' as the [value], otherwise return the default_value (which could be "arm", "home", or "disarmed")? I do see a number of examples at https://github.com/0x5e/homebridge-tuya-platform/blob/develop_1.7.0/ADVANCED_OPTIONS.md, but none that reflect the syntax in the example you created above. 

Your thoughts?

**Comment by githubnavigator** [comment]
Ah, I see where you're going with this. Very helpful. I've tried several variations of this, but I get a syntax error, and I'm not sure whether it's because of the syntax in the override snippet I'm using or if there's something off in SecuritySystemState.ts or one of the other files :
```
[3/25/2023, 10:24:22 AM] SyntaxError: Unexpected token ':'
    at SecuritySystemAccessory.OverridedBaseAccessory.eval (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/BaseAccessory.ts:238:58)
    at SecuritySystemAccessory.getOverridedStatus (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/BaseAccessory.ts:294:27)
    at SecuritySystemAccessory.getStatus (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/BaseAccessory.ts:305:17)
    at /var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/characteristic/SecuritySystemState.ts:64:38
    at SecuritySystemAccessory.updateAllValues (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/BaseAccessory.ts:113:46)
```

Currently what I have is this:

```json
        "deviceOverrides": [
            {
                "id": "xxxxxxxxxxxxxxxx",
                "category": "mal",
                "schema": [
                    {
                        "code": "true",
                        "newCode": "master_mode",
                        "onGet": "{'1': 'arm', '2': 'disarmed', '3': 'home'}[value] || 'home'",
                        "onSet": "{'arm': '1', 'disarmed': '2', 'home': '3'}[value] || '3'"
                    },
                    {
                        "code": "bj",
                        "newCode": "sos_state",
                        "type": "Boolean"
                    }
                ]
            }
        ]
``` 
The bj > sos_state override works, but the true > master_mode override does not. Is the onGet JSON logic you have here something like, "If you get '1', then return 'arm' as the [value], otherwise return the default_value (which could be "arm", "home", or "disarmed")? 

I do see a number of examples at https://github.com/0x5e/homebridge-tuya-platform/blob/develop_1.7.0/ADVANCED_OPTIONS.md, but none that reflect the syntax in the example you created above. 

It is interesting that DP code for master_mode *really is* actually called "true" for whatever reason. I don't understand why they didn't choose something else, but that's just what they decided to call it. Here's what I get in my log if I don't add the master_mode override:

```
  {
    code: 'true',
    mode: 'rw',
    type: 'Enum',
    property: { range: [ '1', '2', '3', [length]: 3 ] }
  },
```
And here's what I get in the log when I use the Smart Life app to set the system to "Home":
```
[3/25/2023, 3:04:11 PM] [TuyaPlatform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/xxxxxxxxxxxxxxxxxxxxx
protocol = 4
message = {
  "dataId": "xxxxxxxxxxxxxxxxxxx",
  "devId": "xxxxxxxxxxxxxxxx",
  "productKey": "xxxxxxxxxxxxxxxxxx",
  "status": [
    {
      "101": "3",
      "code": "true",
      "t": "1679781851",
      "value": "3"
    }
  ]
}
```

**Comment by 0x5e** [comment]
Yes, you've completely understand what I'm trying to do, I'm not JS expert and don't know why it failed. We can change a way to do this:
```
"onGet": "['', 'arm', 'disarmed', 'home'][parseInt(value)]",
"onSet": "['', 'arm', 'disarmed', 'home'].indexOf(value).toString()"
```
the index of an array is started from 0, so I add an empty string to hold the first index.

Yeah the schema code named `true` is funny...

**Comment by githubnavigator** [comment]
That worked! Well done, and thank you!

For future reference for others who may have this system, I am including the configuration for this device below. Apparently, HomeKit only supports alarm triggers and mode configuration. The system has other features (e.g., built-in light settings), but it the iOS interface doesn't seem to surface any of those in the user interface, such as the switch_alarm_light setting that I added to the overrides below. Apparently the iOS app only works with sos_state and master_mode.
```json
{
    "options": {
        "projectType": "2",
        "accessId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "accessKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "countryCode": 44,
        "username": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "appSchema": "smartlife",
        "deviceOverrides": [
            {
                "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "category": "mal",
                "schema": [
                    {
                        "code": "bj",
                        "newCode": "sos_state",
                        "type": "Boolean"
                    },
                    {
                        "code": "kg",
                        "newCode": "switch_alarm_light",
                        "type": "Boolean"
                    },
                    {
                        "code": "true",
                        "newCode": "master_mode",
                        "onGet": "['', 'arm', 'disarmed', 'home'][parseInt(value)]",
                        "onSet": "['', 'arm', 'disarmed', 'home'].indexOf(value).toString()"
                    }
                ]
            }
        ]
    },
    "platform": "TuyaPlatform"
}
```

**Comment by githubnavigator** [comment]
Just out of curiosity (and for anyone else reading this thread), let me make sure I understand the syntax you're using here. 

Based on http://jibbering.com/faq/notes/square-brackets, in onSet--are you taking the array enclosed in the brackets and looking up the index number of the set value (e.g., "arm", which would be 1), then passing that index number (1) along as a string to Tuya in order (effectively setting the true to 1)?

And for the onGet, is Tuya supplying a string version of "1" that is then parsed as an integer instead which is then used to identify the element within the array that is meant to be selected (e.g., 1 = 'arm')?

**Comment by 0x5e** [comment]
Yes, because your enum are 1/2/3 so can be easily use `parseInt()`/`toString()` to convert. But not all device are lucky like this, so a generic solution should use an map to convert like this (multiline version):

```
var map = {
  '1': 'arm',
  '2': 'disarmed',
  '3': 'home',
};
return map[value];
```

But don't know why there's an syntax error when using with `eval()`...

**Comment by 0x5e** [comment]
Yes, because your enum are 1/2/3 so can be easily use `parseInt()`/`toString()` to convert. But not all device are lucky like this, so a generic solution should use an map to convert like this (multiline version):

```
var map = {
  '1': 'arm',
  '2': 'disarmed',
  '3': 'home',
};
return map[value];
```

But don't know why there's an syntax error when using with `eval()`...

**Comment by githubnavigator** [comment]
Okay. Well, interesting case. Thank you for your help!

**Comment by dustball62** [comment]
For anyone else that runs across this and is looking for a solution- I loaded Tuya Local on Home Assistant and modified the existing security system yaml code to work with my system just like this one DP-W2.1. I really like this security system as it watches my barn-remotely- now integrated with Home Assistant its even more powerful.  Not familiar with HomeBridge so not sure if it will work for everyone.
