### ISSUE TITLE
Please add the Doorbell device to the plugin (category 'wxml')

### ISSUE THREAD

**Issue by megadimich** [0x5e/homebridge-tuya-platform#257]
### Device Infomation JSON File

```json
{
"result": {
"active_time": 1678379561,
"biz_type": 0,
"category": "wxml",
"create_time": 1678379561,
"icon": "smart/icon/ay1541129189848tRH06/35acdd39aaead0bfb1b84f729be92f8d.png",
"id": "XXX",
"ip": "XXX",
"lat": "50.4733",
"local_key": "XXX",
"lon": "30.5975",
"model": "G6L",
"name": "Doorbell",
"online": true,
"owner_id": "82840616",
"product_id": "XXX",
"product_name": "Self-powered wireless doorbell G6L",
"status": [
{
"code": "doorbell_list_data",
"value": "AgQBAQwgCAD/EABEAG8AbwByAEIAZQBsAGw="
},
{
"code": "doorbell_ring_value",
"value": 1
},
{
"code": "doorbell_volume_value",
"value": 8
},
{
"code": "alarm_message",
"value": "AEQAbwBvAHIAQgBlAGwAbA=="
},
{
"code": "alarm_propel_switch",
"value": true
},
{
"code": "disturb_time_set",
"value": "AAAFZAFo"
},
{
"code": "doorbell_call",
"value": 1
}
],
"sub": false,
"time_zone": "+02:00",
"uid": "XXX",
"update_time": 1678472171,
"uuid": "XXX"
},
"success": true,
"t": 1678472821239,
"tid": "XXX"
}
```

### Detail Informations

{
"result": {
"category": "wxml",
"functions": [
{
"code": "doorbell_list_data",
"desc": "{}",
"name": "门铃列表数据",
"type": "Raw",
"values": "{}"
},
{
"code": "doorbell_ring_value",
"desc": "{"unit":"","min":1,"max":40,"scale":0,"step":1}",
"name": "门铃铃声",
"type": "Integer",
"values": "{"unit":"","min":1,"max":40,"scale":0,"step":1}"
},
{
"code": "doorbell_volume_value",
"desc": "{"unit":"","min":0,"max":8,"scale":0,"step":1}",
"name": "门铃音量",
"type": "Integer",
"values": "{"unit":"","min":0,"max":8,"scale":0,"step":1}"
},
{
"code": "alarm_message",
"desc": "{}",
"name": "告警消息",
"type": "Raw",
"values": "{}"
},
{
"code": "alarm_propel_switch",
"desc": "{}",
"name": "告警推送开关",
"type": "Boolean",
"values": "{}"
},
{
"code": "disturb_time_set",
"desc": "{}",
"name": "勿扰时段",
"type": "Raw",
"values": "{}"
}
],
"status": [
{
"code": "doorbell_list_data",
"name": "门铃列表数据",
"type": "Raw",
"values": "{}"
},
{
"code": "doorbell_ring_value",
"name": "门铃铃声",
"type": "Integer",
"values": "{"unit":"","min":1,"max":40,"scale":0,"step":1}"
},
{
"code": "doorbell_volume_value",
"name": "门铃音量",
"type": "Integer",
"values": "{"unit":"","min":0,"max":8,"scale":0,"step":1}"
},
{
"code": "alarm_message",
"name": "告警消息",
"type": "Raw",
"values": "{}"
},
{
"code": "alarm_propel_switch",
"name": "告警推送开关",
"type": "Boolean",
"values": "{}"
},
{
"code": "disturb_time_set",
"name": "勿扰时段",
"type": "Raw",
"values": "{}"
},
{
"code": "doorbell_call",
"name": "门铃呼叫",
"type": "Integer",
"values": "{"min":1,"max":255,"scale":0,"step":1}"
}
]
},
"success": true,
"t": 1678487976574,
"tid": "XXX"
}

**Comment by 0x5e** [comment]
Does it have camera on it? or just a single button just like an wireless switch with alarm sound?

**Comment by megadimich** [comment]
No camera. Just one button like a wireless switch with alarm sound

**Comment by 0x5e** [comment]
not very familiar with homekit doorbell, I will see it in the next. information is enough.

**Comment by megadimich** [comment]
Thank you. I'll be waiting.

**Comment by 0x5e** [comment]
https://github.com/Samfox2/homebridge-doorbell/issues/7
Start from iOS 10 or iOS 11 maybe, doorbell without video is not working anymore :(

**Comment by megadimich** [comment]
Is this accessory supposed to work or not? It's not working for me.
The button has been added to the homebridge. In the HOME app, I set it to one-degree action to turn on the light (for example), but it doesn't work.
Here is the information from the log file:
1) When this device is connected:
[15.04.2023, 21:17:15] [@0x5e/homebridge-tuya-platform] [Doorbell] HomeKit Doorbell service does not work without camera anymore.
[15.04.2023, 21:17:15] [@0x5e/homebridge-tuya-platform] [Doorbell] Downgrade to StatelessProgrammableSwitch. "Mute" and "Volume" not available.
2) When DEBUG when pressing call button:
[15.04.2023, 21:19:18] [@0x5e/homebridge-tuya-platform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/d3222de2c0a022306963986aaf28c344
protocol = 4
message = {
  "dataId": "b9c18181-4d7d-4bd0-aec8-9c97cebbe228",
  "devId": "bfd316663c2c14324dzvqb",
  "productKey": "gznianheex1wcv5b",
  { "status": [
    {
      "10": 1,
      { "code": "doorbell_call",
      "t": "1681582740",
      { "value": 1
    }
  ]
}
t = 1681582740

**Comment by 0x5e** [comment]
I was thought the doorbell trigger would use `alarm_message` because camera doorbell use this. but seems your's are using `doorbell_call` instead. Will update later.

**Comment by megadimich** [comment]
Thank you. I'll be waiting. Good for you for doing this work!

**Comment by 0x5e** [comment]
please confirm if it's working now.

**Comment by megadimich** [comment]
It works! Thank you so much! Well done!!!
