### ISSUE TITLE
Air Conditioner remote splitted to 3 devices: AC, Dehumidifier, Fan

### ISSUE THREAD

**Issue by romacv** [0x5e/homebridge-tuya-platform#260]
### Prerequisite

- [X] Yes

### Version

v1.7.0-beta.32

### Device Control Mode

Standard Instruction

### Other Infomations

Hello. There's an issue with implemented way to split AC to 3 devices: AC, Dehumidifier, Fan. 
1. It's interferes with information about humidity values, dehumidifier broadcast 0% humidity.
2. It doesn't work correctly and conflicted with ac modes. For example it's not possible to turn on Dehumid mode, need to turn on AC first, then Dehumid, but sometimes it's send "Turn Off" command
![IMG_BAE78A5E07BD-1](https://user-images.githubusercontent.com/3684453/224974736-3cbe4443-f697-4766-a9c4-1f68ac3e3866.jpeg)

My offer to design AC device same way like in original app: One device with modes (Cold, Fan, Dehumidify, Auto, Off)

![IMG_0735](https://user-images.githubusercontent.com/3684453/224977047-3c126d77-c39a-4459-8495-6d92cb4681b7.jpg)

p.s. it will be perfectly if possible to add sub accessory "Swing" switch.

**Comment by 0x5e** [comment]
1. HomeKit AC don't support fan and dehumidifier mode, so it has to be 3 accessories.
2. HomeKit dehumidifier requires humidity value, but IR sub device don't have this value, so zero instead...
3. In my test, I can turn AC/dehumidifier/fan correctly, one is on, then others will be turned off. can you post some logs and device infos? need to enable debug mode.
4. I will see if swing mode can be enabled later.

**Comment by romacv** [comment]
Thank you for quick response. Is it possible to fetch humidity value from sub device? Because it looks like IR sub device have this value and respond correctly: 
![IMG_0737](https://user-images.githubusercontent.com/3684453/224997111-b87b5f52-8ab3-4aba-9e45-63aa3f4130f8.jpg)
![IMG_0738](https://user-images.githubusercontent.com/3684453/224997122-ca554f2a-3d32-4262-b8e3-e77b50d78a8c.jpg)

**Comment by 0x5e** [comment]
there no solution to display another device's humidity yet, and I guess it will be hard for user to config this feature. unfortunately swing mode are not supported from tuya api documentation :(
