### ISSUE TITLE
Mass hiding TUYA devices

### ISSUE THREAD

**Issue by mrmaximas** [0x5e/homebridge-tuya-platform#269]
It's possible to add this feature? 
For example, i need to hide all tuya devices in HK instead of TH sensors, now i have to do 70+ "deviceOverrides" sections with  "category": "hidden" ;)
Maybe it would be easier to add one long list?
Thanks!

**Comment by mrmaximas** [comment]
It's possible to add this feature? 
For example, i need to hide all tuya devices in HK instead of TH sensors, now i have to do 70+ "deviceOverrides" sections ;)
Maybe it would be easier to add one long list?
Thanks!

**Comment by 0x5e** [comment]
you can use product id as `id` if they are the same product, can it solve you problem?

**Comment by 0x5e** [comment]
It can't be like this. {} is a key-value pair, the key is unique. have you tried using product id? I think that's enough to do so.
