### ISSUE TITLE
Temperature Sensor is not updating anymore

### ISSUE THREAD

**Issue by costingheonea** [0x5e/homebridge-tuya-platform#274]
### Prerequisite

- [X] Yes

### Version

1.7.0-beta.34

### Device Control Mode

Standard Instruction

### Other Infomations

Hi. I dont understand what happened suddenly.
All my 3 temperature sensors are not updating anymore the values in Homebridge.
They work normally in Tuya app, but in Homebrige they dont updated unless I restart the child bridge or the homebridge itself.
I uninstalled completly tuya plugin, reinstalled it and configured again all the sensors in Homekit, but still the same issue.
In the logs nothing is reported.
PLease help.

**Comment by randymassey** [comment]
Of interest, since this latest update of beta 34. The motion sensing driveway lights, which have been operating flawlessly ever since I’ve been using the plug-in. It now seems to turn itself on (the lights), and then remain on, & is not following the dusk & time rules from the Tuya app now, even when it’s set in motion sensing mode. I did, of course observe, that adaptive lighting activated for it with the most recent plug-in update.  I’m not sure if that has something to do with this.But I did want to chime in as well, that with this latest update, I am having this problem persistently now, no matter how many times I set the settings back.Thoughts?RandySent from my iPhoneOn Apr 6, 2023, at 11:20 AM, costingheonea ***@***.***> wrote:﻿
Prerequisite

 Yes

Version
1.7.0-beta.34
Device Infomation JSON File
No response
Device Control Mode
Standard Instruction
Logs
No response
Other Infomations
Hi. I dont understand what happened suddenly.
All my 3 temperature sensors are not updating anymore the values in Homebridge.
They work normally in Tuya app, but in Homebrige they dont updated unless I restart the child bridge or the homebridge itself.
I uninstalled completly tuya plugin, reinstalled it and configured again all the sensors in Homekit, but still the same issue.
In the logs nothing is reported.
PLease help.

**Comment by costingheonea** [comment]
How can I downgrade to previous version to check if this is the problem?

**Comment by 0x5e** [comment]
@costingheonea try this: `npm install @0x5e/homebridge-tuya-platform@1.7.0-beta.xx`.
@randymassey I don't have home hub to test adaptive lighting, is it a global-level setting or device-level setting?

**Comment by costingheonea** [comment]
Unfortunetly, the sensors are not updating. I downgraded to beta 1.7.0-beta.29. They work and update well in Smartthings fo example, so definetly there is something with IOT Tuya servers?
I cant understand why sudenlly they stopped updating.
Other devices from Tuya app are updating in Homebridge, with no issues.

**Comment by 0x5e** [comment]
If downgrade plugin still not work, you can submit the ticket on https://service.console.tuya.com/, maybe there's something changed on tuya cloud server, or your subscribe is expired.

**Comment by mrmaximas** [comment]
i have same issue with all my HT sensors ;(
after plugin restarts HT sensor values update only once.

**Comment by 0x5e** [comment]
@costingheonea @mrmaximas try enable homebridge debug mode and restart, when sensor value changed, are there any logs of `TuyaOpenMQ`?

**Comment by costingheonea** [comment]
> @costingheonea @mrmaximas try enable homebridge debug mode and restart, when sensor value changed, are there any logs of `TuyaOpenMQ`?

I don't see any TuyaOpenMQ logs. Only [TuyaOpenAPI] Requests
Maybe these can help you. This is one of the sensors.

`[07/04/2023, 19:33:46] [@0x5e/homebridge-tuya-platform] [TuyaOpenAPI] Request:
method = get
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf6bb8932c61c86536avmh/specifications
query = undefined
headers = {
  "t": "1680885226997",
  "client_id": "4qqvhatfppytqr3kpyxe",
  "nonce": "c8199f76-8f0c-4688-afa4-7242b0c7bc55",
  "Signature-Headers": "client_id",
  "sign": "FBE88FBB965A0510AA803439149BBB6A116E7CB5412D309FACF18B5BF92D3064",
  "sign_method": "HMAC-SHA256",
  "access_token": "cb3e41761ad8ebf667621216a0d357d1",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.29"
}
body = null
[07/04/2023, 19:33:47] [@0x5e/homebridge-tuya-platform] [TuyaOpenAPI] Response:
path = /v1.0/devices/bf6bb8932c61c86536avmh/specifications
data = {
  "result": {
    "category": "wsdcg",
    "functions": [
      {
        "code": "temp_unit_convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "maxtemp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-399,\"max\":1000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "minitemp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-399,\"max\":1000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "maxhum_set",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "minihum_set",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_periodic_report",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":1,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "va_temperature",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-399,\"max\":1000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "va_humidity",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "battery_percentage",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "charge_state",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_unit_convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "maxtemp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-399,\"max\":1000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "minitemp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-399,\"max\":1000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "maxhum_set",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "minihum_set",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_alarm",
        "type": "Enum",
        "values": "{\"range\":[\"loweralarm\",\"upperalarm\",\"cancel\"]}"
      },
      {
        "code": "hum_alarm",
        "type": "Enum",
        "values": "{\"range\":[\"loweralarm\",\"upperalarm\",\"cancel\"]}"
      },
      {
        "code": "temp_periodic_report",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":1,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1680885227252,
  "tid": "f83a3445d56111ed99d6ea1895c2a2b1"
}`

**Comment by mrmaximas** [comment]
i see HT sensors update packets. for example

[4/8/2023, 1:35:55 AM] [@0x5e/homebridge-tuya-platform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/cdaa8b03ef873ff192dc1634c21cdc
protocol = 4
message = {
  "dataId": "e274890a-59e3-493d-9224-d17e576f708e",
  "devId": "bf846a7e1710a0f39dg1vi",
  "productKey": "0s1izerx",
  "status": [
    {
      "1": 79,
      "code": "va_temperature",
      "t": "1680906958",
      "value": 79
    }
  ]
}
t = 1680906958
==

[4/8/2023, 1:45:56 AM] [@0x5e/homebridge-tuya-platform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/cdaa8b03ef873f56f192dc1634c21cdc
protocol = 4
message = {
  "dataId": "6a48c9be-27aa-4665-821d-02fa0d11150b",
  "devId": "bf7dd157c193c8def21ezu",
  "productKey": "yg5dcbfu",
  "status": [
    {
      "103": 891,
      "code": "va_temperature",
      "t": "1680907559",
      "value": 891
    }
  ]
}
t = 1680907559

**Comment by mrmaximas** [comment]
After debug log watching, I see that the plugin most likely falls off tuya mqtt.
That is, after a while, I see that messages from the plugin stop coming when I do something in the smart life application, for example, I turn something off or on.
Restarting the plugin temporarily helps.

**Comment by mrmaximas** [comment]
I see that there are more events in tuya logs
for example - 2 events in plugin and 4 in tuya log.


[37m[4/8/2023, 5:47:18 PM] [39m[36m[@0x5e/homebridge-tuya-platform][39m [90m[TuyaOpenMQ] onMessage:[39m
[90mtopic = cloud/token/in/cdaa8b03ef873f56f192dc1634c21cdc[39m
[90mprotocol = 4[39m
[90mmessage = {[39m
[90m  "dataId": "6038ea3f-306d-41f7-8167-442346e2eba2",[39m
[90m  "devId": "bf777e03f4fa1aa175ovoo",[39m
[90m  "productKey": "yg5dcbfu",[39m
[90m  "status": [[39m
[90m    {[39m
[90m      "101": 6133,[39m
[90m      "code": "va_humidity",[39m
[90m      "t": "1680965241",[39m
[90m      "value": 6133[39m
[90m    }[39m
[90m  ][39m
[90m}[39m
[90mt = 1680965241[39m

37m[4/8/2023, 6:02:23 PM] [39m[36m[@0x5e/homebridge-tuya-platform][39m [90m[TuyaOpenMQ] onMessage:[39m
[90mtopic = cloud/token/in/cdaa8b03ef873f56f192dc1634c21cdc[39m
[90mprotocol = 4[39m
[90mmessage = {[39m
[90m  "dataId": "55863fc5-65bd-4f4a-bc6a-5331c58270dd",[39m
[90m  "devId": "bf777e03f4fa1aa175ovoo",[39m
[90m  "productKey": "yg5dcbfu",[39m
[90m  "status": [[39m
[90m    {[39m
[90m      "101": 6847,[39m
[90m      "code": "va_humidity",[39m
[90m      "t": "1680966147",[39m
[90m      "value": 6847[39m
[90m    }[39m
[90m  ][39m
[90m}[39m
[90mt = 1680966147[39m

=
![Screenshot 2023-04-08 at 18 36 20](https://user-images.githubusercontent.com/61165387/230730196-54866ae0-4d30-4509-bcd0-6b07d74c74bf.png)

**Comment by 0x5e** [comment]
@costingheonea if no mqtt message, need to check if your subscribe has expired on website, and if you are using the same api key & account in another service (homeassistant, etc.)

@mrmaximas looks like a cloud side issue? try contact https://service.console.tuya.com/.

**Comment by costingheonea** [comment]
> @costingheonea if no mqtt message, need to check if your subscribe has expired on website, and if you are using the same api key & account in another service (homeassistant, etc.)
> 

Hi. The subscription is not expired and I am not using the keys in another service.
This is very odd. This happened suddenly, over the night, without making any changes. I was quite pleased with the setup and all was working fine.
I opened a ticket on tuya platform, but they can't manage to help me.

**Comment by mrmaximas** [comment]
> @costingheonea if no mqtt message, need to check if your subscribe has expired on website, and if you are using the same api key & account in another service (homeassistant, etc.)
> 
> @mrmaximas looks like a cloud side issue? try contact https://service.console.tuya.com/.

I noticed that at the same time as missing tuya events in the debug log there are many other events from other plugins not related to tuya

**Comment by costingheonea** [comment]
Correct me if I am wrong. I reched the logs and notices that some values are not correct or I read them wrong.
I am looking for device id **bf6bb8932c61c86536avmh** witch is one of the temperature sensors that is not updating and is named "Sensor Temperatura Parter".

Usually every hour the values are updating in Tuya app, so they should be updated also in the Homebridge.

`[4/9/2023, 9:01:25 AM] [@0x5e/homebridge-tuya-platform] [TuyaOpenMQ] onMessage:
topic = cloud/token/in/c26863767c00f90138ec2afdfc9bb0b2
protocol = 20
message = {
  "bizCode": "online",
  "bizData": {
    "time": 1681020085
  },
  "devId": "bf6bb8932c61c86536avmh",
  "productKey": "keverit2hdu6sbo0",
  "ts": 0
}
t = 1681020085
[4/9/2023, 9:01:25 AM] [@0x5e/homebridge-tuya-platform] [Senzor temperatura parter] [TemperatureSensor/undefined/CurrentTemperature] Update value: 20.900000000000006 => 20.9`

In Accessories tab, this sensor is showing 20.6 >> https://ibb.co/7SG7MyQ

Something I am missing.

**Comment by 0x5e** [comment]
tuya app is using private, encrypted api, which is different with tuya platform. if the mqtt message is completely missing, I think the problem might from account/project. if not, might be network issue, or ... tuya add the rate limit on it recently? just a guess.

the mqtt connection expired every 2 hours, plugin will reconnect then. please notice, from plugin start, the first 2 hours, and the second 2 hours, will they be different?

**Comment by costingheonea** [comment]
I created a new project from scratch, tuya developer also sugested this. Same issue.
I tried with another homebridge instance on a macbook. No luck.
Tried with smart life app and added only a temp sensor, and logged with a new user.
So, no matter what, the values are not beeing updated in the homebridge.

**Comment by childledj** [comment]
The same issue here. No updates in HK until restarts child bridge in homebridge. Fresh installation of the plugin and fresh project (1 day) so no token expired

**Comment by BenL-AU** [comment]
Same problem here, Wi-Fi contact sensors on doors all of a sudden stopped updating, lucky to get update on restart of homebridge.Doesn’t seem related to beta 34, have rolled back and problem persists….

**Comment by costingheonea** [comment]
I see multiple reports on reddit also. So there is an issue with Tuya servers or something has been changed there and the plugin has to be updated too.

**Comment by costingheonea** [comment]
Can you check if its working for you now? I got a confirmation from Tuya Support Service that they fixed the issue. I am monitoring mines now, and they seem to update.

**Comment by mrmaximas** [comment]
> Can you check if its working for you now? I got a confirmation from Tuya Support Service that they fixed the issue. I am monitoring mines now, and they seem to update.

It seems to be working. I'll keep an eye on it.

**Comment by mrmaximas** [comment]
everything is working at the moment. I think the ticket can be closed. it is only unclear when the situation will repeat itself ))

**Comment by mrmaximas** [comment]
> Can you check if its working for you now? I got a confirmation from Tuya Support Service that they fixed the issue. I am monitoring mines now, and they seem to update.

Unfortunately the problem has reoccurred...

**Comment by costingheonea** [comment]
My sensors are working since then.

**Comment by 0x5e** [comment]
if anyone still exist the problem, submit ticket to tuya again. the more ticket created, the more they pay attention to.
I understand tuya is adding the rate limit because some sensor upload the state too frequently, but the sensor like @mrmaximas  is reported every 10 min, I think it's not a frequently interval.

**Comment by felipehjcosta** [comment]
I had some problems yesterday... It's normal now.

**Comment by himan7991** [comment]
I was having an issue where the Contact Sensor wouldn't update when it was opened or closed, and it would only get the state when Homebridge was restarted.
### Here's how I fixed it

I updated the trial for the Tuya API, and that didn't do anything. Then I went to Tuya website > Cloud > Devices > There are these rectangles that mention the type of device [see image below]. The door sensor was on Standard Instruction, like the other two devices, so I changed it to DP Instructions and it works perfectly now.

![image](https://github.com/0x5e/homebridge-tuya-platform/assets/20800493/ec42ec78-8087-4566-8fa8-8e9008b19d57)

**Comment by mrmaximas** [comment]
@0x5e some days devices like 0s1izerx type (temperature and humidity sensor) not refresh data online, only once after plugin restart, but another type like yg5dcbfu works fine.
