### ISSUE TITLE
Temperature sensor stops updating 

### ISSUE THREAD

**Issue by domre77** [0x5e/homebridge-tuya-platform#280]
### Prerequisite

- [X] Yes

### Version

1.7.0 beta 36

### Device Control Mode

None

### Other Infomations

I have a single temperature sensor. After a few hours the temp value stops updating and HB/HK shows the wrong temp, stuck on old value. When I go into the smart life app it shows the  correct temp. Unable to debug as the HB log has no errors or entries that suggest any problems. When I restart HB it starts to update again for a few hours.

**Comment by 0x5e** [comment]
probably same as #274

**Comment by 0x5e** [comment]
going to close this now. If the problem still exists, please submit ticket to tuya website.

**Comment by domre77** [comment]
Issue is back in 1.7.0 beta 41

**Comment by domre77** [comment]
Apologies, looks like I’m getting the issue 1.6 also.
