### ISSUE TITLE
MiBoxer - WL-Box1 2.4GHz Gateway

### ISSUE THREAD

**Issue by ANDiiikk** [0x5e/homebridge-tuya-platform#288]
### Prerequisite

- [X] Yes

### Version

v1.7.0-beta.39

### Device Control Mode

Standard Instruction

### Other Infomations

Hello, I have Miboxer lights at home which I control via a MiBoxer - WL-Box1 2.4GHz Gateway, I paired it with the smartlife / tuya app and via the tuya platform and control via your plugin via homebridge on a raspberry pi4.

Unfortunately, the problem is that when I turn off the lights via homekit or in the tuya / smartlife app, they turn on by themselves in less than 1 minute.

Is there a way to set it so that the device does not turn on by itself?

**Comment by 0x5e** [comment]
is it related to adaptive lighting?

**Comment by felipehjcosta** [comment]
It seems to be same behavior for me!

**Comment by ANDiiikk** [comment]
Yes, probably yes, if I leave the adaptive function on, the lights come on. If I select any color and turn off the lights they don't turn on by themselves. So it's really a very adaptive feature and it's annoying. :(

**Comment by randymassey** [comment]
I’m not sure if this relates to the problem I was having previously. I decided to recently rebuild homebridge from scratch, and when I began adding items back in, I did decided to not enable adaptive lighting against that motion sensing outdoor driveway light, I’m not sure if that really was tied to my original  issue (of that motion light remaining on), but I’m now, no longer having the problem of that light remaining always on once triggered.I know this is not directly related to this issue, but I saw reference to adaptive lighting, so I did want to follow up.  I stayed frozen in a prior plug-in version (v33) for a while, but as I rebuilt homebridge, when I added everything back, this time I chose not to enable adaptive lighting for the Tuya driveway lights & so far so good.My best guess, is that with adaptive lighting against the pir light, whenever the motion sensor detected motion, the light would continue to remain on afterwards. It seemed to no longer follow the rules set in the Tuya app as far as the number of minutes to switch off.I have not fully tested that supposition, so it is a best guess, but that is my best guess based on observations to present…RandySent from my iPhoneOn Apr 20, 2023, at 8:18 AM, gaosen ***@***.***> wrote:﻿
haven't decided yet how to solve this issue properly. different lights(with tuya module) may have different behavior, that's the most trouble part for me, if a solution solves lights A, but make lights B failed, that's not perfect. so... annoying. :(

**Comment by felipehjcosta** [comment]
Thanks for the update @randymassey!

@ANDiiikk you can check out below some findings on my original issue. Does `MiBoxer - WL-Box1 2.4GHz Gateway` have the same below feature?

https://github.com/0x5e/homebridge-tuya-platform/issues/212#issuecomment-1520513346

> I tested with another [lightbulb](https://pt.aliexpress.com/item/1005001993885393.html?spm=a2g0o.order_list.order_list_main.46.1279caa4M8TmQz&gatewayAdapt=glo2bra) and it's everything ok until now! :)
> 
> The [original ceiling light](https://pt.aliexpress.com/item/1005004732162990.html?spm=a2g0o.order_list.order_list_main.206.1279caa4M8TmQz&gatewayAdapt=glo2bra) I have posted before has the issue. The thing that stood me out is that the ceiling light has a `power-on behavior` which could be the original source of the problem:
> 
> ![IMG_39A1BC3A0B57-1](https://user-images.githubusercontent.com/2865924/234062916-aea788e7-e213-4573-8ba4-aa268e01de3a.jpeg)
> 
> Besides that, there is a documentation by Tuya called [Why does my light turn on by itself?](https://support.tuya.com/en/help/_detail/K9hw5sfh4hs0u) which called my attention about the power supply voltage of the device could be unstable.
> 
> I will review the power stuff and if I find any new issue, I'll post here!

**Comment by ANDiiikk** [comment]
I don't know that miboxer Wl-box has any such function. so far I'm solving it by not using the adaptive lighting function. I'm not an expert and I don't understand much. :(
