### ISSUE TITLE
After update beta 39. Fan light keeps turning on 1%

### ISSUE THREAD

**Issue by merv2k4** [0x5e/homebridge-tuya-platform#291]
### Prerequisite

- [X] Yes

### Version

1.7.0-beta.40

### Device Infomation JSON File

```json
Hi 

Starting from update 39 and now update 40, the light of the ceiling fan keeps turning on by itself at 1 pct.
```

### Device Control Mode

None

### Other Infomations

Normally if i switch the light off, it will stay off. On the non beta version, it was working as it should.

**Comment by merv2k4** [comment]
![Uploading IMG_2902.jpeg…]()

**Comment by merv2k4** [comment]
![IMG_2901](https://user-images.githubusercontent.com/78693962/233796942-4939f42c-ea99-4b57-a3a1-b1def7390114.jpeg)

**Comment by merv2k4** [comment]
![IMG_2902](https://user-images.githubusercontent.com/78693962/233796955-b9d4994b-2bd0-4e91-9067-655b697cf891.jpeg)

**Comment by merv2k4** [comment]
I changed the instruction from Standard to DP. Still same results. The Fan light keeps turning on 2 percent from homekit.

![JST-WYfan](https://user-images.githubusercontent.com/78693962/233797886-6935848d-3c28-40b2-bc24-35f825ead7e8.png)

**Comment by 0x5e** [comment]
Might related to https://github.com/0x5e/homebridge-tuya-platform/releases/tag/v1.7.0-beta.14
- Change range and unit of RotationSpeedLevel, need clean accessory cache to take effect. by @0x5e in https://github.com/0x5e/homebridge-tuya-platform/pull/174

**Comment by merv2k4** [comment]
thanks, its the light of the fan though always turning on at 1 %, not the fan speed itself

**Comment by 0x5e** [comment]
apologize for the mistake. 
the issue might caused by adaptive lighting, some lights seems not working with it.
https://github.com/0x5e/homebridge-tuya-platform/issues/212#issuecomment-1520513346
