### ISSUE TITLE
No Update of Contactsensors

### ISSUE THREAD

**Issue by RudiSeitz** [0x5e/homebridge-tuya-platform#293]
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

v1.7.0-beta.40

### Device Control Mode

None

### Other Infomations

Status of Contact Sensors read correct only when the plugin restarts.
When plugin is running, there is no change of Contact Sensor recognized.

**Comment by 0x5e** [comment]
See #274 , please submit ticket to https://service.console.tuya.com/
