### ISSUE TITLE
PIR Sensor Light Unsupported

### ISSUE THREAD

**Issue by hotbird1970** [0x5e/homebridge-tuya-platform#30]
Thank you for the excellent plugin, all devices seem to be working except for PIR motion sensor

The motion sensor is USB powered PIR motion sensor, with build in night light which is exposed to homekit as unsupported device.

I have updated homebridge and Node JS to the latest versions

Log shows the following:-
Create accessory using legacy mode: PIR Sensor light
Unsupported device: PIR Sensor light

Please see below link to Amazon website for product description
https://www.amazon.ca/gp/product/B07VF43BG1/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

{
  "result": {
    "category": "qjdcz",
    "functions": [
      {
        "code": "switch_1",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "PIR Motion Sensor",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":1,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_led",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Smart night light",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "lang_config": {
          "colour": "Colour Mode",
          "scene": "Scene Mode"
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"colour\",\"scene\"]}"
      },
      {
        "code": "countdown_led",
        "lang_config": {
          "unit": "s"
        },
        "name": "Led Countdown",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "PIR Motion Sensor",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":1,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_led",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Smart night light",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "lang_config": {
          "colour": "Colour Mode",
          "scene": "Scene Mode"
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"colour\",\"scene\"]}"
      },
      {
        "code": "countdown_led",
        "lang_config": {
          "unit": "s"
        },
        "name": "Led Countdown",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"

**Comment by 0x5e** [comment]
It's a light with pir feature, but it doesn't have `presence_state` represents for the state of pir. Maybe we should add it into light accessory or switch accessory?

**Comment by 0x5e** [comment]
I can't find documentation for `qjdcz` on Tuya website, the category code can be get from API with Chinese name `情景灯插座` means `Scene Light Socket`. From your infomation it has two switches, `switch_1` named as "PIR Motion Sensor", `switch_led` named as "Smart night light", I think I may add it into SwitchAccessory in the next version.

**Comment by hotbird1970** [comment]
Updated to beta.18 the motion sensor and led lights both appear as switches in homekit they work well as motion sensor and LED light respectively. 
Many thanks for the quick response and update.
