### ISSUE TITLE
Device Category Change

### ISSUE THREAD

**Issue by RichW02** [0x5e/homebridge-tuya-platform#300]
### Detail Informations

I have a Festoon light  that is running in this plugin and is working except when added to the Tuya account it added it as a Category dj (n colors) but it seems to be a Category dc (colors).   The Tuya config has no colors, but the App has lots of color controls.

The last plugin update also now adds another switch that it never has had before.(without me making any changes)

Is there a way to change the category so it can be re-entered it with the correct DP's? 

How to remove the extra switch?

(It's a steep learning curve for me...........)
Thanks for any help.

**Comment by 0x5e** [comment]
category and schema code are able to override via plugin config. please see readme. I guess your device missed some dp code, need to change control mode on the website.

the extra switch you need to know where it comes from (represents for a tuya switch, or part of the tuya device's feature), then choose to hide a device or hide a DP.

**Comment by RichW02** [comment]
Thanks for the quick response, I'll check it out as see what happens.....
