### ISSUE TITLE
Adaptive Lighting missing since update.

### ISSUE THREAD

**Issue by dswarne** [0x5e/homebridge-tuya-platform#301]
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

1.7.0. Beta 44

### Device Infomation JSON File

```json
Since beta updates, the adaptive lighting settings are not available.
```

### Device Control Mode

None

### Other Infomations

All else functioning correctly

**Comment by 0x5e** [comment]
It was disabled by default since [v1.7.0-beta.42](https://github.com/0x5e/homebridge-tuya-platform/releases/tag/v1.7.0-beta.42) please see docs to enable.

**Comment by dswarne** [comment]
Thanks,
However can you walk me through enabling it, as it worked well with me.

**Comment by 0x5e** [comment]
https://github.com/0x5e/homebridge-tuya-platform/blob/develop_1.7.0/ADVANCED_OPTIONS.md#configuration
