### ISSUE TITLE
updated to newest version 10 minutes ago

### ISSUE THREAD

**Issue by pad81** [0x5e/homebridge-tuya-platform#335]
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

v1.7.0-beta.47

### Device Control Mode

None

### Other Infomations

after updated to newest beta i cant no longer hit the preferences button insight of HB. iam getting a failed to load plugins schema. i already uninstalled plugin (with removing config), restarted HB and installed plugin again, but still same issue.

using HB in a docker container.

**Comment by 0x5e** [comment]
thanks @pad81 , should be fixed in beta.48.
