### ISSUE TITLE
Option to hide unsupported device

### ISSUE THREAD

**Issue by guylopes71** [0x5e/homebridge-tuya-platform#34]
Hi.  I setup Tuya iot.  I linked 3 devices out of 8.  In Homebridge, it gathers all 8…
Do you have a hint on how to « not » see the unwanted devices in Homebridge?
Thank you in advance

**Comment by 0x5e** [comment]
I would add an option to hide the unsupported device, sometimes it is useful to showing them. thanks for the feedback.

**Comment by guylopes71** [comment]
Thanks, but not only hide unsopported but also hide unliked 
Thanks

**Comment by 0x5e** [comment]
OK

**Comment by JulianLepinski** [comment]
I'd love to +1 this, but also suggest that the feature allows for hiding any arbitrary device, including supported devices a user doesn't want to show up in Homekit.
