### ISSUE TITLE
Status not updating

### ISSUE THREAD

**Issue by TrailBlazinPDX** [0x5e/homebridge-tuya-platform#356]
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

v1.7.0-beta.49 

### Device Control Mode

None

### Other Infomations

I have a 3 way light switch and if it is turned off at the source, it does not update on the home app.  I can see the device updated on the smart life app.  I also have another switch (normal 1 switch) and the same thing will occur if the item is turned on (or off) at the source.  The new status does not push to the home app.  The new status is however present in the smart life app.

**Comment by TrailBlazinPDX** [comment]
renewed api subscription on tuya cloud

**Comment by ARMarchetti** [comment]
Still not updating status. Device shows as Opening but the door is closed. 
![IMG_1625](https://github.com/0x5e/homebridge-tuya-platform/assets/133385078/d087a613-6eb7-47e9-96a6-cebd3668d980)
![IMG_1626](https://github.com/0x5e/homebridge-tuya-platform/assets/133385078/68520265-133b-4804-8688-a394631f68f4)
