### ISSUE TITLE
login issue with v1.7 beta 51, cannot roll back to beta 50

### ISSUE THREAD

**Issue by DolmensDude** [0x5e/homebridge-tuya-platform#386]
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

1.7.0-beta51

### Device Control Mode

None

### Logs

```shell
[10/7/2023, 12:11:54 PM] [@0x5e/homebridge-tuya-platform] Login failed. code=1013, msg=request time is invalid
```

### Other Infomations

this seems to be new to this version. all prev 1.7 betas were fine.

only option was to rollback to v1.6 for now

**Comment by DolmensDude** [comment]
can we close this?  I retried a few hours later and it logged in. no changes in the VM where this runs... odd... but it consistently failed on this when I made the report.

fun stuff.

**Comment by DolmensDude** [comment]
close

**Comment by DolmensDude** [comment]
thanks

**Comment by 0x5e** [comment]
the tuya api request requires correct system time, if your system time is wrong then it will failed.

**Comment by DolmensDude** [comment]
Yeah, of course I checked that first, as well as the time zone offset displayed in the homebridge status page first. These were fine.So I don’t really know what the cause was, or the fix to be honest.On Oct 8, 2023, at 06:18, gaosen ***@***.***> wrote:﻿
the tuya api request requires correct system time, if your system time is wrong then it will failed.

**Comment by 0x5e** [comment]
well, that's weird... if you can reproduce it, please enable homgbridge debug mode, copy the whole tuya network request & response, paste here and also submit a ticket on tuya platform.
