### ISSUE TITLE
Add support of Thermostat Valve (category=wkf)

### ISSUE THREAD

**Issue by Fabi3n31** [0x5e/homebridge-tuya-platform#40]
Hello,

I have a Thermostat Valve (category=wkf) which is not properly supported. Only the battery percentage is exposed in home app.
I hope I will provide all the needed information, let me know if you need more.

Thanks for the future support!

**Data reported in Homebridge log:**
TuyaOpenAPI response: path = /v1.0/devices/bfa***************38g/specifications,
data = {"result":{"category":"wkf","functions":[
{"code":"mode","type":"Enum","values":"{\"range\":[\"auto\",\"manual\"]}"},
{"code":"temp_set","type":"Integer","values":"{\"unit\":\"℃\",\"min\":5,\"max\":45,\"scale\":0,\"step\":1}"},{"code":"switch_rapid","type":"Boolean","values":"{}"},
{"code":"countdown_rapid","type":"Integer","values":"{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":15}"},{"code":"window_check","type":"Boolean","values":"{}"},
{"code":"child_lock","type":"Boolean","values":"{}"}],

"status":[
{"code":"mode","type":"Enum","values":"{\"range\":[\"auto\",\"manual\"]}"},
{"code":"temp_set","type":"Integer","values":"{\"unit\":\"℃\",\"min\":5,\"max\":45,\"scale\":0,\"step\":1}"},{"code":"temp_current","type":"Integer","values":"{\"unit\":\"℃\",\"min\":-100,\"max\":500,\"scale\":1,\"step\":5}"},{"code":"switch_rapid","type":"Boolean","values":"{}"},
{"code":"countdown_rapid","type":"Integer","values":"{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":15}"},
{"code":"work_state","type":"Enum","values":"{\"range\":[\"opened\",\"closed\"]}"},
{"code":"window_check","type":"Boolean","values":"{}"},
{"code":"window_state","type":"Enum","values":"{\"range\":[\"opened\",\"closed\"]}"},
{"code":"child_lock","type":"Boolean","values":"{}"},
{"code":"battery_percentage","type":"Integer","values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"}]},

"success":true,"t":16**********************738,"tid":"1012c*****************66e75"}

**Data reported in Tuya platform API explorer: "Get specification and properties of the device**

{
  "result": {
    "category": "wkf",
    "functions": [
      {
        "code": "mode",
        "desc": "{\"range\":[\"auto\",\"manual\"]}",
        "name": "模式",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "temp_set",
        "desc": "{\"unit\":\"℃\",\"min\":5,\"max\":45,\"scale\":0,\"step\":1}",
        "name": "温度设置",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":5,\"max\":45,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_rapid",
        "desc": "{}",
        "name": "快速开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_rapid",
        "desc": "{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":15}",
        "name": "快速升温倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":15}"
      },
      {
        "code": "window_check",
        "desc": "{}",
        "name": "开窗检测",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "child_lock",
        "desc": "{}",
        "name": "童锁开关",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "mode",
        "name": "模式",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "temp_set",
        "name": "温度设置",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":5,\"max\":45,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "name": "当前温度",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-100,\"max\":500,\"scale\":1,\"step\":5}"
      },
      {
        "code": "switch_rapid",
        "name": "快速开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_rapid",
        "name": "快速升温倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":15}"
      },
      {
        "code": "work_state",
        "name": "工作状态",
        "type": "Enum",
        "values": "{\"range\":[\"opened\",\"closed\"]}"
      },
      {
        "code": "window_check",
        "name": "开窗检测",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "window_state",
        "name": "窗户状态",
        "type": "Enum",
        "values": "{\"range\":[\"opened\",\"closed\"]}"
      },
      {
        "code": "child_lock",
        "name": "童锁开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_percentage",
        "name": "电池电量",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 16***********************738,
  "tid": "1012c****************************66e75"

}

**Data reported in Tuya platform API explorer: "Get status of a single device**

{
  "result": [
    {
      "code": "mode",
      "value": "manual"
    },
    {
      "code": "temp_set",
      "value": 15
    },
    {
      "code": "temp_current",
      "value": 200
    },
    {
      "code": "switch_rapid",
      "value": false
    },
    {
      "code": "countdown_rapid",
      "value": 0
    },
    {
      "code": "work_state",
      "value": "opened"
    },
    {
      "code": "window_check",
      "value": true
    },
    {
      "code": "window_state",
      "value": "closed"
    },

**Comment by 0x5e** [comment]
Seems `wkf` is similar to `wk`, however it is missing `switch`. what's the usage of`switch_rapid`? Is it the power on/off switch? If so, it can be added with almost the same logic as `wk` does.

**Comment by Fabi3n31** [comment]
I think switch_rapid corresponds to a function to enable a rapid heating (kind of boost) during a time predefined (countdown rapid I think)

**Comment by 0x5e** [comment]
If so, where's the power on/off？

**Comment by Fabi3n31** [comment]
I don't think a power on/off switch is needed. This a thermostat valve for water radiators. So once you have added the batteries it is always on. Depending of the temperature set and temperature sensor value, a motor control the water flow of the valve to control the heating of the radiator.

Here is a link to the device:
https://www.aliexpress.us/item/3256802247259692.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US

**Comment by 0x5e** [comment]
OK, so we can just display the power state as on forever, and ignore the on/off command.

**Comment by 0x5e** [comment]
Please try beta.25.

**Comment by Fabi3n31** [comment]
Yes it works, thanks !

I think it would be nice if you can control the power on/off switch based on the "work_state".
It would allow to see rapidly in home app, if the radiator is heating or not.

work_state = opened => heating displayed in smartlife, so switch should be on
work_state = closed=> pause displayed in smartlife, so switch should be off

Thanks.

**Comment by 0x5e** [comment]
Your `work_state` is a readonly state. I've already used in the `onGet` method, when it's 'opened' display `HEAT` state, 'closed' display `OFF` state. I can't use it in `onSet` method because it's not writable.
What you've see displayed in the center of the home app is target temperature, it will always displayed. On the top left there's status about 'closed, heating, cooling'.
