### ISSUE TITLE
Add support for Feit WiFi RGBW Strip Lights

### ISSUE THREAD

**Issue by ekobres** [0x5e/homebridge-tuya-platform#42]
This is a Feit BRGWW Strip light from Costco.

It's a little weird because of the brightness ranges - so there are repeated warnings in the HK logs:

`[11/4/2022, 11:34:15 AM] [@0x5e/homebridge-tuya-platform] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 101 exceeded maximum of 100. See https://homebridge.io/w/JtMGR for more info.`

Also, there is no way to get the light to go into white mode from the Home App with the way the plugin maps colors. It tries to create white from RGB - which is awful.

It would be great if there is a color (or color range) that turns the work_mode to white like most RGBW HomeKit bulbs do.

 ```
 {
    "active_time": 1653152515,
    "biz_type": 0,
    "category": "dd",
    "create_time": 1653152515,
    "icon": "smart/icon/ay1547266640143rRUIA/0271de0733c59e73f6c041a51db81511.jpg",
    "id": "ebe8eba5a29d260e2efnrj",
    "ip": "99…",
    "lat": "34…",
    "local_key": "bfa4b9…",
    "lon": "-84...",
    "model": "LST04-F",
    "name": "Bar Window 3",
    "online": true,
    "owner_id": "51….",
    "product_id": "s4z3nskgoy958zut",
    "product_name": "Strip Light ",
    "status": [
      {
        "code": "switch_led",
        "value": false
      },
      {
        "code": "work_mode",
        "value": "colour"
      },
      {
        "code": "bright_value",
        "value": 1000
      },
      {
        "code": "colour_data",
        "value": "{\"h\":240,\"s\":1000,\"v\":1010}"
      },
      {
        "code": "scene_data",
        "value": "{\"scene_num\":1,\"scene_units\":[{\"bright\":200,\"h\":0,\"s\":0,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":13,\"unit_switch_duration\":14,\"v\":0}]}"
      },
      {
        "code": "countdown",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "-04:00",
    "uid": "az…",
    "update_time": 1665241766,
    "uuid": "c2…",
    "schema": [
      {
        "code": "switch_led",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "work_mode",
        "mode": "rw",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}",
        "property": {
          "range": [
            "white",
            "colour",
            "scene",
            "music"
          ]
        }
      },
      {
        "code": "bright_value",
        "mode": "rw",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":1000,\"scale\":0,\"step\":1}",
        "property": {
          "unit": "",
          "min": 1,
          "max": 1000,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "colour_data",
        "mode": "rw",
        "type": "Json",
        "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}",
        "property": {
          "h": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 360,
            "step": 1
          },
          "s": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 1000,
            "step": 1
          },
          "v": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 1000,
            "step": 1
          }
        }
      },
      {
        "code": "scene_data",
        "mode": "rw",
        "type": "Json",
        "values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}",
        "property": {
          "scene_num": {
            "min": 1,
            "scale": 0,
            "max": 8,
            "step": 1
          },
          "scene_units": {
            "unit_change_mode": {
              "range": [
                "static",
                "jump",
                "gradient"
              ]
            },
            "unit_switch_duration": {
              "min": 0,
              "scale": 0,
              "max": 100,
              "step": 1
            },
            "unit_gradient_duration": {
              "min": 0,
              "scale": 0,
              "max": 100,
              "step": 1
            },
            "bright": {
              "min": 0,
              "scale": 0,
              "max": 1000,
              "step": 1
            },
            "temperature": {
              "min": 0,
              "scale": 0,
              "max": 1000,
              "step": 1
            },
            "h": {
              "min": 0,
              "scale": 0,
              "unit": "",
              "max": 360,
              "step": 1
            },
            "s": {
              "min": 0,
              "scale": 0,
              "unit": "",
              "max": 1000,
              "step": 1
            },
            "v": {
              "min": 0,
              "scale": 0,
              "unit": "",
              "max": 1000,
              "step": 1
            }
          }
        }
      },
      {
        "code": "countdown",
        "mode": "rw",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "property": {
          "min": 0,
          "max": 86400,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "music_data",
        "mode": "wo",
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}",
        "property": {
          "change_mode": {
            "range": [
              "direct",
              "gradient"
            ]
          },
          "bright": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 1000,
            "step": 1
          },
          "temperature": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 1000,
            "step": 1
          },
          "h": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 360,
            "step": 1
          },
          "s": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 255,
            "step": 1
          },
          "v": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 255,
            "step": 1
          }
        }
      },
      {
        "code": "control_data",
        "mode": "wo",
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}",
        "property": {
          "change_mode": {
            "range": [
              "direct",
              "gradient"
            ]
          },
          "bright": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 1000,
            "step": 1
          },
          "temperature": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 1000,
            "step": 1
          },
          "h": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 360,
            "step": 1
          },
          "s": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 255,
            "step": 1
          },
          "v": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 255,
            "step": 1
          }
        }
      }
    ]
  }
```

**Comment by 0x5e** [comment]
Do you mean `RGBCW`? There's no `RGBWW` light I think. If so, your light support color temperature, you can go to the color temperature panel and pick a white color then it will change to white mode.
HomeKit Light Accessory doesn't have the 'switch mode' feature, I think apple wants to make things simple.

**Comment by 0x5e** [comment]
Should fixed. Please try the latest version.

**Comment by ekobres** [comment]
I am not seeing the brightness warnings now - so that’s fantastic.As for the white - yes this is RGBW - single temp (2700 K/370 mired) white light strip. I know Apple makes this hard - but what other lights do is detect white on the color wheel and then put the light into white mode, and set a color temp. For this light, the minimum and maximum are the same - 2700 K or 370 mired. So if the user chooses the color temperature wheel to set a color - the range will lock them into the allowable range for the bulb, but it should also trigger the light to switch to white mode. Only when color is set again should the light change back to color mode.Otherwise we only have “mixed” RGB whites (dim and poor white color fidelity) and the nice looking bright white LEDs in the strip are never used.I hope this makes sense.On Nov 5, 2022, at 12:16 AM, gaosen ***@***.***> wrote:﻿
Should fixed. Please try the latest version.

**Comment by 0x5e** [comment]
The light logic is really complicated :)

For the `RGB`, `C` or `CW` light, they don't have the mode switching issue.
For the `RGBCW` light, we can change mode by switching the color and color temperature panel in HomeKit.
For the `RGBW` light, or `RGBC` whatever, which don't support change color temperature, but support color/white mode change, I didn't considered very clearly before.

You say other light will detect the 'white range' on the color wheel and switching color/white mode, which plugin it is? I think is an acceptable solution. If there's any code I can refer, I will add into this plugin.
If we show the color temperature panel for `RGBW`/`RGBC` light, the problem is, I have no chance to know what color temperature it is. I can't get it from the device information, So I can't limit it into an specific range of the color temperature.

And, in the 1.7.0 I may add a config options to enable & disable `mode` switch for all device.

**Comment by ekobres** [comment]
If you consider an RGBW light as an RGBCW light with a narrow range, that logic should all work, correct?

HomeKit has properties for the color temperature service to set a minimum and maximum color temperature.

Every color tunable light has a range - some are 2000k-8000k - some are 2700k-6500k, etc. If you set this light as tunable from 2700-2700 range (range of a single value) don’t you think that would work?

The other option is more of a hack - and that would be to use a switch to switch the light from color mode to white mode - which os sort of how the Tuya app deals with it. Personally I think it would be better to just treat it like a tunable white light with a really narrow range.

**Comment by 0x5e** [comment]
Ok let me have a try. I mean I can't know what specific value is (for yours is 2700k, others maybe 6000k). I can only set one constant value for all different `RGBW` light.

**Comment by ekobres** [comment]
Yes - but it won’t matter since each light only has one temperature to give! :^)Erick Kobres On Nov 6, 2022, at 6:55 PM, gaosen ***@***.***> wrote:﻿
Ok let me have a try. I mean I can't know what specific value is (for yours is 2700k, others maybe 6000k). I can only set one constant value for all different RGBW light.

**Comment by 0x5e** [comment]
Yes :) not a big problem. I will try.

**Comment by 0x5e** [comment]
If we set the `minValue = maxValue = 200`, the color temperature is still a circle, with a faded color temperature like this.
Wherever i clicked, homebridge returns the value 200 for me and I just switch the mode to white. Is it good for you?

<img width="901" alt="image" src="https://user-images.githubusercontent.com/5144674/200233404-635be9ec-73bc-461e-bbfa-8ad66e658230.png">

**Comment by ekobres** [comment]
Need to see if it sticks for scenes and what Siri command is. 370 mired would be my choice. Not sure what color name 200 is.On Nov 7, 2022, at 12:35 AM, gaosen ***@***.***> wrote:﻿
If we set the minValue = maxValue = 200, the color temperature is still a circle, with a faded color temperature like this.
Wherever i clicked, homebridge returns the value 200 for me and I just switch the mode to white. Is it good for you?

**Comment by 0x5e** [comment]
How did you say in siri?

**Comment by ekobres** [comment]
“Set lights to white”On Nov 7, 2022, at 5:01 AM, gaosen ***@***.***> wrote:﻿
How did you say in siri?

**Comment by 0x5e** [comment]
You say "Set lights to white", and then siri will select a color temperature instead of color?
That is enough, as long as color temperature is successfully picked by siri, the temperature value for `RGBC/RGBW` is not important, we just send the mode switching command.

**Comment by ekobres** [comment]
That’s what I would like to have happen - what actually happens is dependent on the accessory. Tunable white bulbs respond differently to different white light colors. Presumably if the bulb is tunable white, she will only respond to names of colors that fit. Thinking more about it, it may actually be better to make it a range from min to max possible mired temps so that any white temp will result in white mode.That would be the most flexible way to handle it even if it’s technically “wrong” because there is no way to know or change the non-tunable color.Erick Kobres On Nov 7, 2022, at 5:30 AM, gaosen ***@***.***> wrote:﻿
You say "Set lights to white", and then siri will select a color temperature instead of color?
That is enough, as long as color temperature is successfully picked by siri, the temperature value for RGBC/RGBW is not important, we just send the mode switching command.

**Comment by 0x5e** [comment]
So we use the default range 140~500 mired instead?

**Comment by ekobres** [comment]
I think that will probably be the best behavior for Siri and scenes. I don’t know if you keep any state data about the accessory - if so you should keep whatever temp was set as the value. If you can’t store any state data, then we will have to test and see what happens to figure out the best fake value to return.I would start with 370 mired as the “fake” value if you cannot keep state.On Nov 7, 2022, at 8:32 AM, gaosen ***@***.***> wrote:﻿
So we use the default range 140~500 mired instead?

**Comment by 0x5e** [comment]
There's no best solution for `RGBW` when displaying color temperature panel, the users can click every part of the circle but no temperature switching function, and every different `RGBW` may have different temperatures.

The sure thing is we can solve the "can't switch to white mode in homekit" issue and "can't switch to white mode in siri", for the others, I suggest put it aside, there's still many other devices not supported yet.

**Comment by 0x5e** [comment]
I will submit a new version these days, wait for me :)

**Comment by 0x5e** [comment]
Please try beta.27

**Comment by ekobres** [comment]
It does not set white work mode.It mixes RGB colors to create a range of fake white temperatures which is pretty much the same as before.This is Home App bright white:This is Tuya app bright white.On Nov 7, 2022, at 11:22 PM, gaosen ***@***.***> wrote:﻿
Please try beta.27

**Comment by 0x5e** [comment]
Can you upload the debug logs?

**Comment by 0x5e** [comment]
After you pick a color temperature, did you choose save or cancel?

**Comment by ekobres** [comment]
SaveOn Nov 8, 2022, at 8:21 AM, gaosen ***@***.***> wrote:﻿
After you pick a color temperature, did you choose save or cancel?

**Comment by ekobres** [comment]
Which logs? Put HB in debug mode - or is there a debug log file from somewhere else you need?On Nov 8, 2022, at 8:17 AM, gaosen ***@***.***> wrote:﻿
Can you upload the debug logs?

**Comment by 0x5e** [comment]
Put HB in debug mode.

**Comment by ekobres** [comment]
It looks like I was partially wrong. Once things are synched with the lights, using the temp wheel seems to work now! But Siri still does not work. When I ask Siri to set to bright white (or any white) it gets set to a mixed RGB color of white.

If I set to white with temp wheel, which does work, and ask her the color - she always says it is "bright white" - which is great. But when I ask Siri to set a light to bright white, the color goes to an RGB white.

Here you go with the log file:

I use the color picker to set the light to blue and also to pick a temperature. (both worked!)
I asked Siri to set the color to bright white - and she did not set a color mode - she made a weak RGB color.

[homebridge.log-3.txt](https://github.com/0x5e/homebridge-tuya-platform/files/9961963/homebridge.log-3.txt)

**Comment by 0x5e** [comment]
When your light's color mode is white, I will return a fake hsv color of white, because homekit will still use the rgb color to fill in the brightness slider. That's a little tweak. If I don't do this, and return the hsv color stored in the device, you will see an green/red/blue brightness slider when the light is actually white.

**Comment by ekobres** [comment]
Yes - It looks like the fake value is “bright white” and the fake color temp is 140 mired.For some reason Siri forces HSV when setting to bright white. That might be because bright white does not match 140 mired.According to my Hue bulbs - bright white is 153 mired (6535k)HSB for that color is 35/0/100%Can we change the fake values to those?On Nov 8, 2022, at 9:35 AM, gaosen ***@***.***> wrote:﻿
When your light's color mode is white, I will return a fake hsv color of white, because homekit will still use the rgb color to fill in the brightness slider. That's a little tweak. If I don't do this, and return the hsv color stored in the device, you will see an green/red/blue brightness slider when the light is actually white.

**Comment by 0x5e** [comment]
I will change default value to 153 mired, If anyone needs another value, then in 1.7.0 will add an options to override this.

Whese warnings is known issue #32, we have a workaround in plugin side, the server side issue they are still working on it.

**Comment by ekobres** [comment]
Changing to 153 seems to help a lot. When it was 140 it would float between 140 and 153 which was causing problems. I believe that whatever mired value you choose, you should also lock the H/S values to match - 153 mired is not 0/0 H/S you are returning. 153 mired is closer to 60/1 H/S. 

The ultimate would be to do what the Hue and other HK certified bulbs seem to do: They have a map of the color temperatures and when the H/S falls within a white range, they set the color mode to white (and of course set the actual temp which we can't do.) So they will never use the RGB LED when a white is detected - when a white is detected they set the appropriate H/S properties, but also the temperature with the white LED(s).

**Comment by 0x5e** [comment]
I'd like to do temperature -> hsv convertion too, do you know any documents or plugins about it? the convertion seems not simple.

**Comment by ekobres** [comment]
I’ve seen this: https://andi-siess.de/rgb-to-color-temperature/

Should be fairly easy to create an HSV version from this RGB table.

**Comment by 0x5e** [comment]
OK, thanks.

**Comment by 0x5e** [comment]
The map from https://andi-siess.de/rgb-to-color-temperature/ seems not correct, 6500K convert into a very red color.
I find some tools in npm and the result is different with you.
6500K -> 153mired -> rgb(255, 254, 250) -> hsv(48, 2, 100)

**Comment by ekobres** [comment]
> The map from https://andi-siess.de/rgb-to-color-temperature/ seems not correct, 6500K convert into a very red color.
> I find some tools in npm and the result is different with you.
> 6500K -> 153mired -> rgb(255, 254, 250) -> hsv(48, 2, 100)

There is no official standard that I know of. Both the one from the table and the npm tool give you an almost complete white. 

I know there are some curves that have been defined to constrain the Kelvin white space to within a region of HSV space which may work better. They are approximations, but at least they capture the values in the gaps.

**Comment by ekobres** [comment]
I learned another thing about the Apple Home app temperature picker. The range is driven from the minimum and maximum color temperatures of the characteristic - so we should set that to match the default white (153) that you return. Otherwise, someone can pick a color in the temp wheel, and yes the light will go to white mode, but if that temperatures is used in a scene, the scene will fail because the colors don’t match. Things will work much better when tempRange == targetTemp == defaultTemp == targetHS == actualTemp == actualHS

**Comment by 0x5e** [comment]
So the problem come back again: the plugin doesn't know the device's actual color temperature. I know your's is 6500k, 153 mired, but it is a variable actually, not a constant. Or did you mean just set a fixed value whatever it is, and all `RGBW` lights (6500k, 6700k, 6900k, ...) can work with scene?

**Comment by ekobres** [comment]
It is better, but there is still a trap for users if they use the temperature picker with the range. 

1: User pick any temp that is not the default.
2: Plugin sets white mode and default temp/color (153/H,S)
3: Home app chooses wrong H/S to match user choice - not default.
4: Use palette in a scene.
5: Scene will fail because scene palette color does not match default color. 

Fix: Only allow default color to be chosen in temp picker. (Temp characteristic min=max=default)

I know this because I can manually select color temp with 3rd party scene editor and if I select 153 mired, the scene will succeed. Any other value the scene will fail even though the white mode is set.

**Comment by ekobres** [comment]
Almost. Now the light will only accept 153 - but the temp wheel range is still 140-500. That min/max range should be 153-153 so any touch of the wheel will always be 153. As it is now, if you miss, the white will not set.

I can see the valid range with the Controller app - see screenshot:

![C542EA41-FA0F-4866-B85B-8DE74EC33921](https://user-images.githubusercontent.com/11447445/202865359-720eb4f1-ce35-4043-8e8b-70234ed708dd.png)

**Comment by 0x5e** [comment]
whats your color temperature panel look like? Mine's aready becames a single color tempertaure panel.

![image](https://user-images.githubusercontent.com/5144674/202875580-464e0ca5-c05e-4b44-9c94-4a1bbd8f238d.png)

Other characteristic like `CurrentTemperature` won't allow me set the maxValue less or equal to minValue, the error will appear and the hombridge stop running, but `ColorTemperature` won't when I'm setting, I don't know why.

**Comment by 0x5e** [comment]
#102 changes are here, can you help review the code?

**Comment by ekobres** [comment]
Okay, I’m stupid. Needed to clear the cached accessory data which I guess includes the characteristic metadata. Now the temperature picker shows one color.
