### ISSUE TITLE
Add support for tap-to-run scenes from Tuya Smart app.

### ISSUE THREAD

**Issue by ekobres** [0x5e/homebridge-tuya-platform#43]
**Is your feature request related to a problem? Please describe:**

I have scenes in the Tuya Smart app that can do things that HomeKit cannot. For example set white mode or set a smart scene.

**Describe the solution you'd like:**

I would like for the plugin to expose Tuya Smart App scenes as switches in HomeKit so they can be incorporated into HomeKit scenes. It would also be nice if the switches could remain triggered after they are set so that HomeKit can recognize that the scene has been set. If they quickly revert back to "off" after the scene is set, HomeKit will think the scene set has failed.

**Describe alternatives you've considered:**

Trying to create scenes in HomeKit is not practical for features that are not explore to HomeKit, such as white light and Tuya Smart Scenes.

**Additional context:**

There is an [old Tuya Web plugin](https://github.com/milo526/homebridge-tuya-web) that exposes scenes, which works well, but it has numerous other problems.

**Comment by 0x5e** [comment]
Already have plans to add scene support, maybe after 1.6.0 release, depends on how much spare time I have. Thanks for the feedback.

**Comment by 0x5e** [comment]
Remain switch triggered may not possible because the scene doesn't have status, it's just an action. It is like a wireless button, or tv remote. Techinally I can keep the switch on but I will never know when should I change it to off.

**Comment by 0x5e** [comment]
Supported on 1.7.0-beta.1, please try :)

**Comment by darkaeden** [comment]
Is there any way to hide scenes available in Tuya app, to avoid having them exposed into Homebridge and Homekit?7
Thanks!
