### ISSUE TITLE
Typo "Netrork" in Error Message

### ISSUE THREAD

**Issue by shanemcw** [0x5e/homebridge-tuya-platform#446]
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

v1.7.0-beta.53

### Device Control Mode

None

### Other Infomations

Typo in error message:

`[Tuya] [TuyaOpenAPI] Netrork error: read ETIMEDOUT. Retrying...`

**Comment by 0x5e** [comment]
Thanks! upteded :)
