### ISSUE TITLE
Hombli smart bulb only works in color mode

### ISSUE THREAD

**Issue by PrimaveraNL** [0x5e/homebridge-tuya-platform#5]
Added a hombli smart bulb to my home.
It appears in homekit only as color bulb. In the Tuya Smart app, it has more options amongst which the option for different white colors.

**Comment by 0x5e** [comment]
Did you mean this bulb should be able to set color temperature, but can't be set in the HomeKit?

**Comment by PrimaveraNL** [comment]
Yes. In the Tuya app it has 4 panels, "white" for white color and brightness, "color" for color setting and brightness, "Scene" and "Music" of which the latter two probably are not supported by homekit.

**Comment by 0x5e** [comment]
Could you please provide some device info? Enable the homebridge in debug mode, and upload some logs of the device functions, status, product_id.

**Comment by PrimaveraNL** [comment]
How do I set the homebridge to debug? I do know where to find debugging options in the tuya iot platform but not in the homebridge itself?

**Comment by 0x5e** [comment]
If you start Homebridge with Web GUI, it can be found in Setting page. If started by cli, just add `-D` option. For example: `homebridge -D`

**Comment by PrimaveraNL** [comment]
So here are the properties and instruction set. See the 'white' mode, this is what I'm missing in homebridge currently for this device.

[20221023T2308 smart bulb properties.txt](https://github.com/0x5e/homebridge-tuya-platform/files/9847556/20221023T2308.smart.bulb.properties.txt)
[20221023T2308 smart bulb instruction set.txt](https://github.com/0x5e/homebridge-tuya-platform/files/9847557/20221023T2308.smart.bulb.instruction.set.txt)

**Comment by 0x5e** [comment]
The lightbulb is complicated, it has C, CW, RGB, RGBC, RGBCW 5 types. Some RGB light don't have white mode. Let me figure out how to handle this.

**Comment by PrimaveraNL** [comment]
Great.
Let me know if I can help with additional data?

**Comment by 0x5e** [comment]
That's enough, just I don't know how to handle 5 types of light with 1 code.

**Comment by 0x5e** [comment]
#12 should fix this. Please try 1.6.0-beta.12

**Comment by PrimaveraNL** [comment]
I pulled it and tried. I don't see any difference in homekit app. Should I remove the accessory and add it again or should it function on basis of the old install?

**Comment by 0x5e** [comment]
No need to remove, just upgrade to the beta version. Can you record a video about the issue？Maybe I didn't fully understand the text, or maybe your operation is not correct

**Comment by PrimaveraNL** [comment]
The Tuya app shows 4 tabs, of which the first two are White and Color
White tab:
![IMG_2A09B52873D6-1](https://user-images.githubusercontent.com/116505818/197796978-e02a4799-ef96-407b-8171-3a627eb5aaa3.jpeg)

Color tab:
![IMG_4127B0C0A3A3-1](https://user-images.githubusercontent.com/116505818/197797003-de1083ca-0646-4154-add4-56ac61ec846e.jpeg)

The Apple homekit app. through the Tuya bridge, only shows this panel:
![IMG_30C250867237-1](https://user-images.githubusercontent.com/116505818/197797313-73081744-7bb4-4e4c-8334-8097c92399e8.jpeg)

... which is the same as it was before the update. So I don't see anything different after the update.

I removed the device from the app and added it because the status log says it was 'loaded from cache' and I wanted to make sure older settings would not conflict.

**Comment by 0x5e** [comment]
In the Home App, double click one of the six panel, then you can see the color setting or color temperature setting, switch to temperature panel and pick one temperature, then save. That's how it works. 

![IMG_8244](https://user-images.githubusercontent.com/5144674/197803089-6fa0d2cf-fb69-494b-9bdf-9443e78f395c.PNG)
![IMG_8245](https://user-images.githubusercontent.com/5144674/197803105-f48cf2f2-4117-4c3f-875b-56eb959e9f67.PNG)

**Comment by PrimaveraNL** [comment]
Allright then.
That doesn't really solve my problem, as the bulb remains in color mode that way. It seems to operate differently in color and white mode, which can also be seen in the instruction set. It never gets into white mode like this, which it does through the Tuya app.
 
Thank you for your effort trying to solve this; I guess this bulb is just not compatible enough.

**Comment by 0x5e** [comment]
Okay, one last try, can you open the homebridge debug mode and upload the full log during your lightbulb operation？

**Comment by 0x5e** [comment]
I know where the problem is. I will submit a new version.

**Comment by 0x5e** [comment]
Please try 1.6.0-beta.13

**Comment by PrimaveraNL** [comment]
Pulled this and this works better than before. Thank you.
