### ISSUE TITLE
Feature : Offline as off.

### ISSUE THREAD

**Issue by bonxz** [0x5e/homebridge-tuya-platform#52]
![image](https://user-images.githubusercontent.com/61289944/168468781-6ce4ac08-3940-4c54-8895-441aeb089e8e.png)

Something like this would be cool. I use a lot of lamps that only turn on in the evening and then 
I have otherwise over the day 10 devices that update themselves again and again and get no feedback.

Same feature here for checking: https://github.com/bwp91/homebridge-govee/search?q=offline

**Comment by 0x5e** [comment]
Ok, after 1.6.0 release I will add more config options for advance features.

**Comment by 0x5e** [comment]
I've found the way of display online status, support all of the devices. Might be different with your expect, I prefer the smaller config, tuya has nearly 200+ categories, if every category's offline have different behavior, I can't imagine how to maintain the huge code and configs...

**Comment by bonxz** [comment]
Okay, so it's not workable like that?
Is there no other option?

**Comment by 0x5e** [comment]
Technically it can be done, iPhone also can use three buttons like android, but it only use one, I don' want to add too much options on the plugin... just like the device on the tuya app with zero config too. Does it really necessary to display the offline state as off? Some light is offline but still power on.

**Comment by bonxz** [comment]
So for me it would make a lot of sense. I use 5 lamps in my hallway that always show me as online and of course I don't always have the hallway light on. And I only use the rgb in the evening. 

![A57E9909-2182-4D20-8930-331D39B66ECF](https://user-images.githubusercontent.com/61289944/209482650-cd1709c4-ddc0-4a33-bebf-26ec23b98d5b.jpeg)

**Comment by 0x5e** [comment]
With the online/offline information provide to the homekit, I think it's better to implement the offline UI feature by Apple. Now the fan icon will have rotation animation when device online, and stops rotate when offline.

If you really need this, I will update the `deviceOverrides` feature, passing the additional `device` object then you can fully decide how to display all the device status from `device`, including `online`.

**Comment by 0x5e** [comment]
The document is updated, config example here:
https://github.com/0x5e/homebridge-tuya-platform/blob/develop_1.7.0/ADVANCED_OPTIONS.md#offline-as-off

I will release the beta vesion later today.

**Comment by bonxz** [comment]
Okay nice. I will then test and report back here. :)

**Comment by bonxz** [comment]
I have now read through all of this a bit. What exactly goes into the dp code? Do not fully understand
        "oldCode": "{dp_code}",
        "code": "{dp_code}",

and could not you just read the status of the lamps from tuya iot? There is also when the lamps are offline and online.
![image](https://user-images.githubusercontent.com/61289944/209571830-4603aa9a-1c7c-4975-858b-1c47ac6ca0f0.png)

**Comment by 0x5e** [comment]
`dp code` is the code of your datapoint, it can be found from the log or website device debug page. for the light switch it's usually `switch_led` or `switch`.

The reason why I'm not instead directly read the online status is because: I have the finite time to contribute and maintain this project, but the user's requirement is infinite, I have to consider the ROI of each requirement. If a requirement can be done for all of the device categories, it's good. Meanwhile, if the config is flexable and can be used by many situations, I think it will be even better (for me, save the develop time).
With the `device` argument added in the `onGet/onSet` handler, all of the category now support "offline as off" feature, and I don't need to develop this feature for switch, air purifier, valve, window, door, over and over again.
And, it can do more than this, for multiple switch, it can display main switch as off, using sub switch's status, or turn on the fan with a fixed speed level, there's a lot of room for imaginations.

**Comment by bonxz** [comment]
Okay, I understand that.

Is that right now as I have this here?
    "deviceOverrides": [{
      "id": "{bfdb77a421e3013c1enbgq}",
      "schema": [{
        "oldCode": "{switch_led}",
        "code": "{switch_led}",
        "onGet": "(device.online && value)"
      }]
    }]

I'll just add that to the config,.

**Comment by 0x5e** [comment]
```
"deviceOverrides": [{
"id": "bfdb77a421e3013c1enbgq",
"schema": [{
"oldCode": "switch_led",
"code": "switch_led",
"onGet": "(device.online && value)"
}]
}]
```

no need to add {} between your value, `{dp_code}` just repesents for a variable.

**Comment by bonxz** [comment]
Okay got it running now :)
Thanks for the help.

**Comment by 0x5e** [comment]
Great. If the `{}` is confusing, I will update the document later.

**Comment by michalw2-alt** [comment]
Can you please advise what kind of debug needs to be enabled and where in order to find out dp code of each device?
I tried both switch and switch_led for smart bulb and plug switches but I cannot see any difference for disconnected devices in Honekit.
Perhaps this can be explained by using wrong dp code.

**Comment by 0x5e** [comment]
@michalw2-alt please see readme - faq and troubleshooting section. if the problem still exists, please post the debug log and your configs.

**Comment by michalw2-alt** [comment]
I have performed some troubleshooting and managed to find that I was using wrong DP code.
However now that config appears to be correct - I'm able to see "Status Active 0" for disconnected device in Accessories.

![Screenshot 2023-01-02 at 14 18 23](https://user-images.githubusercontent.com/74453829/210238459-bd9791c6-3d43-4c30-9c27-fcde06948c78.jpg)

Nonetheless I'm still able to operate device even though it's disconnected.
Also nowhere I can see Offline status of the device (HomeKit and Homebridge accessories).

Please find configuration of particular device in question below:

        {
            "id": "80040667bcddcxxxxxx",
            "schema": [
                {
                    "oldCode": "switch",
                    "code": "switch",
                    "onGet": "(device.online && value)"
                }
            ]
        },
Logs:

[1/2/2023, 2:15:55 PM] [TuyaPlatform] [Smart Socket 2] Override status { code: 'switch', value: true } => { code: 'switch', value: false }

Example of request:
[1/2/2023, 2:15:52 PM] [TuyaPlatform] [TuyaOpenAPI] Request:
method = post
endpoint = https://openapi.tuyaeu.com/
path = /v1.0/devices/80040667bcddc20xxxx/commands
query = null
headers = {
"t": "167266535xxxx",
"client_id": "hgs3jw35d8rxxxx",
"nonce": "9cca4350-6b01-4f39-8e23-cxxxx",
"Signature-Headers": "client_id",
"sign": "3C654EE736B43F3A5BC375ED15418F11D182Axxxxxxx",
"sign_method": "HMAC-SHA256",
"access_token": "4fb5ce5f6e86a03183ea34xxxx",
"lang": "en",
"dev_lang": "javascript",
"dev_channel": "homebridge",
"devVersion": "1.7.0-beta.20"
}
body = {
"commands": [
{
"code": "switch",
"value": true
}
]
}
[1/2/2023, 2:15:52 PM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/80040667bcddxxxxx/commands
data = {
"code": 2001,
"msg": "device is offline",
"success": false,
"t": 1672665xxxxx,
"tid": "955601518a9f11edbdcf7681xxxxx"
}

Thank you in advance!

**Comment by bonxz** [comment]
The id is wrong. Serial number is not id. 
you need to look up in the debug mode from tuya panel.

**Comment by michalw2-alt** [comment]
> The id is wrong. Serial number is not id.
> you need to look up in the debug mode from tuya panel.

Thank You.
In case if id is wrong how come correct device name (Smart Socket 2) was resolved in log entry below?
It says Smart Socket 2 which is name of device (apparently identified based on serial number id).

[1/2/2023, 2:15:55 PM] [TuyaPlatform] [Smart Socket 2] Override status { code: 'switch', value: true } => { code: 'switch', value: false }

But anyway I get it - serial number as device id should not be used. 
Interestingly this id was found in Tuya app where it is called virtual id.

**Comment by michalw2-alt** [comment]
I have just verified in Tuya panel - it appears that all devices id are serial numbers.
After clicking "Debug Device" option - there is no difference - Device ID is serial number for all devices.
Therefore it looks like DP codes that I have used are correct.

Please refer to screenshot below:
![Screenshot 2023-01-02 at 19 40 48](https://user-images.githubusercontent.com/74453829/210268776-79950cd9-d198-40a5-b723-4ccfb10f80c3.jpg)

**Comment by bonxz** [comment]
> I have just verified in Tuya panel - it appears that all devices id are serial numbers. After clicking "Debug Device" option - there is no difference - Device ID is serial number for all devices. Therefore it looks like DP codes that I have used are correct.
> 
> Please refer to screenshot below: ![Screenshot 2023-01-02 at 19 40 48](https://user-images.githubusercontent.com/74453829/210268776-79950cd9-d198-40a5-b723-4ccfb10f80c3.jpg)
> 
> ![Screenshot 2023-01-02 at 19 42 34](https://user-images.githubusercontent.com/74453829/210268876-c2009998-8c48-44cf-9920-a4b98bbac825.jpg)
> 
> If I'm looking at wrong place - could you please correct me?

Youre wrong. Still no debug mode. Click on the right side debug device. there is the right number for id

**Comment by michalw2-alt** [comment]
No not all numbers begin with b - please also lok for 800... - this is exactly how it's configured for override devices.
I have also checked all 3 tabs in Debug Device - but could find no other device id :-(
I'm sorry for producing this much of spam here.
![Screenshot 2023-01-02 at 19 51 05](https://user-images.githubusercontent.com/74453829/210269878-ce32b56e-b915-4f9e-9758-b5f8acc96566.jpg)
![Screenshot 2023-01-02 at 19 51 29](https://user-images.githubusercontent.com/74453829/210269900-8a6f0963-6fb2-4e6f-a8ee-6d3a0ed136b8.jpg)
![Screenshot 2023-01-02 at 19 51 37](https://user-images.githubusercontent.com/74453829/210269908-86dc40bb-d8fd-4a30-b558-d704cfd70601.jpg)

**Comment by michalw2-alt** [comment]
@0x5e this thread is already closed - do you think it would be better to post this issue under new thread?

https://github.com/0x5e/homebridge-tuya-platform/issues/52#issuecomment-1368952910

**Comment by michalw2-alt** [comment]
I think I got this working now but I'm not sure if it's suppose to be working this way.
When disconnected device is set to On in HomeKit - status is not refreshed on its own as long as Home app is opened.

In order to refresh status of device I have to close Home app (or move it to background and then to front-end), re-open again or open Tuya app.
Afterwards following logs are generated:

[1/3/2023, 9:44:57 PM] [TuyaPlatform] [Lamp] Override status { code: 'switch_led', value: true } => { code: 'switch_led', value: false }

**Comment by 0x5e** [comment]
@michalw2-alt  Have you tried clean the accessory cache? the status should get updated in real time. The issue looks similar with https://github.com/0x5e/homebridge-tuya-platform/issues/192

And tuya device have two id: `device.id` and `device.uuid`. the former may changed after device paired, the latter won't. Seems it will make user confusing, I will add both id support in the config later.

**Comment by 0x5e** [comment]
And, "Status Active" can be seen in the homekit device setting page.

**Comment by michalw2-alt** [comment]
> @michalw2-alt Have you tried clean the accessory cache? the status should get updated in real time. The issue looks similar with #192
> 
> And tuya device have two id: `device.id` and `device.uuid`. the former may changed after device paired, the latter won't. Seems it will make user confusing, I will add both id support in the config later.

Thank you for reply.
Sorry for silly question but how to clear cache?
Is this available in Settings?
- Remove Single Cached Accessory
Or
- Remove All Cached Accessories

**Comment by 0x5e** [comment]
@michalw2-alt  Yes, I think remove single cache is enough, if the issue is caused by cache.

**Comment by michalw2-alt** [comment]
Unfortunately after clearing cach for affected device - issue is still present.
I can see 'override status' logs being generated upon restarting Homebridge or after manually trigger them (or as described previously even if I leave iPhone unintended and it gets locked - after unlocking and Home app is on display - log is generated) - but not on its own.

Enabling device:

[1/4/2023, 10:39:51 AM] [TuyaPlatform] [TuyaOpenAPI] Request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/80040667bcddc200d292/commands
query = null
headers = {
  "t": "1672825191541",
  "client_id": "hgs3jw35d8rrvuswragf",
  "nonce": "4407530f-b90c-43f3-8c04-02ae97907a7d",
  "Signature-Headers": "client_id",
  "sign": "99C83D03F0AEBD3288BAFADE49DC7065A553A69D6D9D147E174CEF1FB012AB94",
  "sign_method": "HMAC-SHA256",
  "access_token": "764b3a59aac9f1ac64f733bc4937ca86",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.7.0-beta.20"
}
body = {
  "commands": [
    {
      "code": "switch",
      "value": true
    }
  ]
}
[1/4/2023, 10:39:51 AM] [TuyaPlatform] [TuyaOpenAPI] Response:
path = /v1.0/devices/80040667bcddc200d292/commands
data = {
  "code": 2001,
  "msg": "device is offline",
  "success": false,
  "t": 1672825191867,
  "tid": "bcc3e5618c1311ed9155f6a8c25a9394"
}


But this log is generated on its own and device remains On (event though its disconnected):
[1/4/2023, 10:39:50 AM] [TuyaPlatform] [Smart Socket 2] Override status { code: 'switch', value: true } => { code: 'switch', value: false }

Do you think it would be worth to clear all cache ? If, so are there any downsides ? I read warning message that this could be dangerous and some things might get reset.

**Comment by 0x5e** [comment]
@michalw2-alt I understand what you mean now. when device is already offline, then you do an operation on the homekit, then it goes to an wrong state, and you expect to see it change back right? I can stop change the state when device is offline.

**Comment by michalw2-alt** [comment]
Is there any ETA for this to be implemented?
Thanks a lot.

**Comment by 0x5e** [comment]
@michalw2-alt  maybe today. I'm getting covid last week, just recovered my mind to coding.

**Comment by michalw2-alt** [comment]
Sorry to hear that but I’m glad you’re ok

**Comment by michalw2-alt** [comment]
It works great now.
Thank you. Much appreciated.

**Comment by Tom5640** [comment]
**@0x5e Really silly one here I am sorry, but my bog standard configuration is the below:**
{
  "platform": "TuyaPlatform",
    "name": "TuyaPlatform",
    "options": {
        "lang": "en",
        "countryCode": 44,
        "accessId": "xxxxxxx",
        "username": "tom@xxxxxxxxell.co.uk",
        "password": "xxxxxx",
        "accessKey": "3ff8a8a9b88b4xxxxxxxxxxx26c2",
        "projectType": "2",
        "appSchema": "smartlife",
        "debug": true
    }
}

**and then I would be trying to integrate the following into this:**

{
  "options": {
    // ...
    "deviceOverrides": [{
      "id": "773072238cce4ecbd3c3",
      "schema": [{
        "code": "switch_led",
        "onGet": "(device.online && value)"
      }]
    }]
  }
}

But in .json editor I keep receiving schema errors under the "deviceOverrides" section - I'd expect it to be:

{
  "platform": "TuyaPlatform",
    "name": "TuyaPlatform",
    "options": {
        "lang": "en",
        "countryCode": 44,
        "accessId": "xxxxxxx",
        "username": "tom@xxxxxxxxell.co.uk",
        "password": "xxxxxx",
        "accessKey": "3ff8a8a9b88b4xxxxxxxxxxx26c2",
        "projectType": "2",
        "appSchema": "smartlife",
        "debug": true
"deviceOverrides": [{
      "id": "773072238cce4ecbd3c3",
      "schema": [{
        "code": "switch_led",
        "onGet": "(device.online && value)"
    }
}

**is my formatting correct? Thanks, Tom.**

**Comment by 0x5e** [comment]
@Tom5640 missing a `]` in `schema`. keep the indent will be better to find the problem.
```
{
  "platform": "TuyaPlatform",
  "name": "TuyaPlatform",
  "options": {
    "lang": "en",
    "countryCode": 44,
    "accessId": "xxxxxxx",
    "username": "tom@xxxxxxxxell.co.uk",
    "password": "xxxxxx",
    "accessKey": "3ff8a8a9b88b4xxxxxxxxxxx26c2",
    "projectType": "2",
    "appSchema": "smartlife",
    "deviceOverrides": [{
      "id": "773072238cce4ecbd3c3",
      "schema": [{
        "code": "switch_led",
        "onGet": "(device.online && value)"
    }]
}
```

**Comment by Tom5640** [comment]
@0x5e  Thank you below works and I am sorry that knowledge is so basic -  I have to apply to 3 devices, so where would I include the second device override?

```
"deviceOverrides": [
            {
                "id": "7730722384cca8888c49",
                "schema": [
                    {
                        "oldCode": "switch_led",
                        "code": "switch_led",
                        "onGet": "(device.online && value)"
                    }
                ]
            }
        ]
    }
}
```

**Comment by 0x5e** [comment]
@Tom5640 I'm not good at explain this in english. you can try homebridge web gui.

```
{
  "platform": "TuyaPlatform",
  "name": "TuyaPlatform",
  "options": {
    "lang": "en",
    "countryCode": 44,
    "accessId": "xxxxxxx",
    "username": "tom@xxxxxxxxell.co.uk",
    "password": "xxxxxx",
    "accessKey": "3ff8a8a9b88b4xxxxxxxxxxx26c2",
    "projectType": "2",
    "appSchema": "smartlife",
    "deviceOverrides": [{
      "id": "device_id_1",
      "schema": [{
        "code": "switch_led",
        "onGet": "(device.online && value)"
    }, {
      "id": "device_id_2",
      "schema": [{
        "code": "switch_led",
        "onGet": "(device.online && value)"
    }, {
      "id": "device_id_3",
      "schema": [{
        "code": "switch_led",
        "onGet": "(device.online && value)"
    }]
}
```

**Comment by Tom5640** [comment]
Thanks so much @0x5e .  The json is now accepted it but looks as though it's still picking up the schema for the first device only and not applying to the 2nd & 3rd devices.  Maybe someone else here could help me, such as @bonxz . It's not too important, it was just a bonus feature of using your plugin rather than the tuya developed one, and I am already getting lots of bonus features so thank you very much!
