### ISSUE TITLE
Error 28841001 No permissions

### ISSUE THREAD

**Issue by weyemar** [0x5e/homebridge-tuya-platform#54]
Receiving the error "28841001, msg=No permissions". I have read the instructions over several times and think I did everything correctly. I see my devices on iot.tuya.com. Any suggestions?

> [11/6/2022, 8:24:05 PM] [@0x5e/homebridge-tuya-platform] Launched child bridge with PID 3340
> [11/6/2022, 8:24:05 PM] Registering platform '@0x5e/homebridge-tuya-platform.TuyaPlatform'
> [11/6/2022, 8:24:05 PM] [@0x5e/homebridge-tuya-platform] Loaded @0x5e/homebridge-tuya-platform v1.6.0-beta.26 child bridge successfully
> [11/6/2022, 8:24:05 PM] [@0x5e/homebridge-tuya-platform] Log in to Tuya Cloud.
> [11/6/2022, 8:24:05 PM] Homebridge v1.5.1 (HAP v0.10.4) (@0x5e/> [11/6/2022, 8:24:05 PM] [@0x5e/homebridge-tuya-platform] Launched child bridge with PID 3340
> [11/6/2022, 8:24:05 PM] Registering platform '@0x5e/homebridge-tuya-platform.TuyaPlatform'
> [11/6/2022, 8:24:05 PM] [@0x5e/homebridge-tuya-platform] Loaded @0x5e/homebridge-tuya-platform v1.6.0-beta.26 child bridge successfully
> [11/6/2022, 8:24:05 PM] [@0x5e/homebridge-tuya-platform] Log in to Tuya Cloud.
> [11/6/2022, 8:24:05 PM] Homebridge v1.5.1 (HAP v0.10.4) (@0x5e/homebridge-tuya-platform) is running on port 42864.
> [11/6/2022, 8:24:06 PM] [@0x5e/homebridge-tuya-platform] Start MQTT connection.
> [11/6/2022, 8:24:06 PM] [@0x5e/homebridge-tuya-platform] Fetching home list.
> [11/6/2022, 8:24:06 PM] [@0x5e/homebridge-tuya-platform] [TuyaOpenMQ] Get MQTT config failed. code = 28841001, msg = No permissions.
> [11/6/2022, 8:24:06 PM] [@0x5e/homebridge-tuya-platform] Fetching home list failed. code=28841001, msg=No permissions.homebridge-tuya-platform) is running on port 42864.
> [11/6/2022, 8:24:06 PM] [@0x5e/homebridge-tuya-platform] Start MQTT connection.
> [11/6/2022, 8:24:06 PM] [@0x5e/homebridge-tuya-platform] Fetching home list.
**> [11/6/2022, 8:24:06 PM] [@0x5e/homebridge-tuya-platform] [TuyaOpenMQ] Get MQTT config failed. code = 28841001, msg = No permissions.
> [11/6/2022, 8:24:06 PM] [@0x5e/homebridge-tuya-platform] Fetching home list failed. code=28841001, msg=No permissions.**

**Comment by weyemar** [comment]
Ok guess I didn't Google enough originally. I found some stuff about authorizing API. Then I enabled one and received the message below. After enabling all the ones listed in the error, the devices are now showing up.

> API not subscribed. Please go to "Tuya IoT Platform -> Cloud -> Development -> Project -> Service API",
> and Authorize the following APIs before using:
> - Authorization Token Management
> - Device Status Notification
> - IoT Core
> - Industry Project Client Service (for "Custom" project)

**Comment by weyemar** [comment]
So since I just activated trials for all those service APIs, will this eventually require me to purchase some kind of subscription with Tuya?

**Comment by 0x5e** [comment]
MQTT requires 'Device Status Notification' service subscribed.

Currently all these APIs used by plugin is free for trial, and the time can be extended after expiration.
In the future will it be charged and when, I don't know :)
