### ISSUE TITLE
Having issues with operating Garage Door Opener using Plugin. 

### ISSUE THREAD

**Issue by mitch5772** [0x5e/homebridge-tuya-platform#58]
Having issues with operating Garage Door Opener using Plugin.

Plugin cannot read state of garage door.
![Screenshot 2022-11-07 181337](https://user-images.githubusercontent.com/117628415/200247279-63fec608-d769-4805-bbb1-70b2c93588db.jpg)

" [07/11/2022, 17:49:08] [@0x5e/homebridge-tuya-platform] This plugin threw an error from the characteristic 'Target Door State': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://homebridge.io/w/JtMGR for more info.
[07/11/2022, 17:49:08] [@0x5e/homebridge-tuya-platform] This plugin threw an error from the characteristic 'Current Door State': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://homebridge.io/w/JtMGR for more info."

**Comment by 0x5e** [comment]
Please upload the TuyaDeviceList.{uid}.json, the path is in the log.

**Comment by mitch5772** [comment]
Excuse my ignorance, but how do I do that and what am I looking for?

**Comment by 0x5e** [comment]
On your log's second line, `/var/lib/homebridge/persist/TuyaDeviceList.{uid}.json`, just get the file, and paste it here.

**Comment by mitch5772** [comment]
Apologies again, but how do i "get the file"? where do I paste that path? On the homebridge web interface itself?

**Comment by 0x5e** [comment]
If you are running homebridge inside the docker, you can goo to homebridge web terminal page, execute `cat /var/lib/homebridge/persist/TuyaDeviceList.{uid}.json` and get the content.

**Comment by mitch5772** [comment]
I'm running Homebridge on a Raspberry Pi, so accessing through web via IP address.

**Comment by mitch5772** [comment]
I was able to Execute it:

pi@homebridge:/var/lib/homebridge $ cat /var/lib/homebridge/persist/TuyaDeviceList.eu1638084895669pxMTR.json
[
  {
    "active_time": 1667801252,
    "biz_type": 18,
    "category": "ckmkzq",
    "create_time": 1667017243,
    "icon": "smart/icon/ay1551739974191WD3qA/8f0e6fa1c7ffcf2b817ec951452bd7de.png",
    "id": "31334334e8db84fff99e",
    "ip": "101.182.82.175",
    "lat": "-36.7393",
    "local_key": "6482025f0d8cb001",
    "lon": "144.1393",
    "model": "CSH-GRGDROPN",
    "name": "Smart Wireless Garage Door Opener",
    "online": true,
    "owner_id": "43167835",
    "product_id": "tzfwglemct9dh6j5",
    "product_name": "",
    "status": [],
    "sub": false,
    "time_zone": "+10:00",
    "uid": "eu1638084895669pxMTR",
    "update_time": 1667801255,
    "uuid": "31334334e8db84fff99e",
    "schema": []
  },
  {
    "active_time": 1666786372,
    "biz_type": 18,
    "category": "pc",
    "create_time": 1638669190,
    "icon": "smart/icon/ay1567436186279ak5wg/15744812044b864aa55e6.jpg",
    "id": "485754762462ab39fe17",
    "ip": "101.182.82.175",
    "lat": "-36.7395",
    "local_key": "4346b0c30ca7debf",
    "lon": "144.1391",
    "model": "BSD31-200303",
    "name": "Moon Lamp",
    "online": true,
    "owner_id": "43167835",
    "product_id": "pm8c3o8c4gsftq5t",
    "product_name": "USB Smart plug",
    "status": [
      {
        "code": "switch_1",
        "value": false
      },
      {
        "code": "switch_2",
        "value": false
      },
      {
        "code": "countdown_1",
        "value": 0
      },
      {
        "code": "countdown_2",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "+10:00",
    "uid": "eu1638084895669pxMTR",
    "update_time": 1666786393,
    "uuid": "485754762462ab39fe17",
    "schema": [
      {
        "code": "switch_1",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "switch_2",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "countdown_1",
        "mode": "rw",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "property": {
          "unit": "s",
          "min": 0,
          "max": 86400,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "countdown_2",
        "mode": "rw",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "property": {
          "unit": "s",
          "min": 0,
          "max": 86400,
          "scale": 0,
          "step": 1
        }
      }
    ]
  },
  {
    "active_time": 1638085475,
    "biz_type": 18,
    "category": "kt",
    "create_time": 1638085475,
    "icon": "smart/product_icon/kt.png",
    "id": "41570146500291bb77df",
    "ip": "175.33.165.64",
    "lat": "-37.9270",
    "local_key": "3059681299e6bc98",
    "lon": "145.2305",
    "model": "A011A.02.010.001",
    "name": "Portable air conditioner",
    "online": false,
    "owner_id": "43167835",
    "product_id": "4RUISW6Lmtz2u1l8",
    "product_name": "Portable air conditioner",
    "status": [
      {
        "code": "switch",
        "value": false
      },
      {
        "code": "temp_set",
        "value": 20
      },
      {
        "code": "temp_current",
        "value": 18
      },
      {
        "code": "humidity_set",
        "value": 32
      },
      {
        "code": "mode",
        "value": "cold"
      },
      {
        "code": "windspeed",
        "value": "1"
      },
      {
        "code": "c_f",
        "value": "C"
      },
      {
        "code": "temp_set_f",
        "value": 62
      },
      {
        "code": "temp_current_f",
        "value": 32
      },
      {
        "code": "humidity_current",
        "value": 32
      }
    ],
    "sub": false,
    "time_zone": "+10:00",
    "uid": "eu1638084895669pxMTR",
    "update_time": 1646347833,
    "uuid": "41570146500291bb77df",
    "schema": [
      {
        "code": "humidity_current",
        "mode": "ro",
        "type": "",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"%\",\"max\":100,\"step\":1}",
        "property": {
          "min": 0,
          "scale": 0,
          "unit": "%",
          "max": 100,
          "step": 1
        }
      },
      {
        "code": "windspeed",
        "mode": "rw",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\" ]}",
        "property": {
          "range": [
            "1",
            "2",
            "3"
          ]
        }
      },
      {
        "code": "humidity_set",
        "mode": "rw",
        "type": "Integer",
        "values": "{\"min\":0,\"unit\":\"%\",\"scale\":0,\"max\":100,\"type\":\"value\",\"step\":1}",
        "property": {
          "min": 0,
          "unit": "%",
          "scale": 0,
          "max": 100,
          "type": "value",
          "step": 1
        }
      },
      {
        "code": "temp_current",
        "mode": "ro",
        "type": "",
        "values": "{\"min\":-20,\"scale\":0,\"unit\":\"℃\",\"max\":100,\"step\":1}",
        "property": {
          "min": -20,
          "scale": 0,
          "unit": "℃",
          "max": 100,
          "step": 1
        }
      },
      {
        "code": "temp_set",
        "mode": "rw",
        "type": "",
        "values": "{\"min\":16,\"unit\":\"℃\",\"scale\":0,\"max\":31,\"type\":\"value\",\"step\":1}",
        "property": {
          "min": 16,
          "unit": "℃",
          "scale": 0,
          "max": 31,
          "type": "value",
          "step": 1
        }
      },
      {
        "code": "switch",
        "mode": "rw",
        "type": "",
        "values": "{}",
        "property": {}
      },
      {
        "code": "mode",
        "mode": "rw",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"cold\",\"hot\",\"wet\",\"wind\",\"eco\"]}",
        "property": {
          "range": [
            "auto",
            "cold",
            "hot",
            "wet",
            "wind",
            "eco"
          ]
        }
      },
      {
        "code": "temp_current_f",
        "mode": "ro",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":32,\"max\":99,\"scale\":0,\"step\":1}",
        "property": {
          "unit": "℉",
          "min": 32,
          "max": 99,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "c_f",
        "mode": "rw",
        "type": "Enum",
        "values": "{\"range\":[\"C\",\"F\"]}",
        "property": {
          "range": [
            "C",
            "F"
          ]
        }
      },
      {
        "code": "temp_set_f",
        "mode": "rw",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":62,\"max\":90,\"scale\":0,\"step\":1}",
        "property": {
          "unit": "℉",
          "min": 62,
          "max": 90,
          "scale": 0,
          "step": 1
        }
      }
    ]
  }

**Comment by 0x5e** [comment]
You can use ssh run `cat /path/to/file`, or scp to copy file to your computer, or via web interface terminal page `http://ip:port/platform-tools/terminal`

**Comment by mitch5772** [comment]
I believe most of that is relating to the air conditioner that is not supported.

**Comment by 0x5e** [comment]
Your Garage Door Opener `31334334e8db84fff99e`'s `status` and `schema` is empty. why would that happens...
Please go to Tuya Platform -> Cloud Develop -> device debugging and take photos for this device's standard instruct set and standard status set.

**Comment by 0x5e** [comment]
> I believe most of that is relating to the air conditioner that is not supported.

That's not related, AC is not supported yet, I will support it next version.

**Comment by mitch5772** [comment]
> Your Garage Door Opener `31334334e8db84fff99e`'s `status` and `schema` is empty. why would that happens... Please go to Tuya Platform -> Cloud Develop -> device debugging and take photos for this device's standard instruct set and standard status set.

There is no standard instruct set or standard set. 
![Screenshot 2022-11-07 191342](https://user-images.githubusercontent.com/117628415/200259306-3f7d2f40-f714-479c-b6c2-bf34d93581dc.jpg)

**Comment by 0x5e** [comment]
Can you control the device via Tuya App? Seems this device is not controlable. It can't be controled via Tuya Platform debugging to.

**Comment by mitch5772** [comment]
I am using the Smart Life App for this device, and it does work via Smart Life app.

**Comment by 0x5e** [comment]
Is it ble device? Please confirm when you close the wifi, and disable ble in system setting (or leave away from the device), can it be controlled?

**Comment by mitch5772** [comment]
It's a wifi only device I believe. When I close wifi it can still be controlled.

**Comment by 0x5e** [comment]
#111
