### ISSUE TITLE
Add support for Motion Spot Light

### ISSUE THREAD

**Issue by devindice** [0x5e/homebridge-tuya-platform#64]
UME Smart WiFi LED Security Light Motion Sensor Outdoor, Work with Alexa/Google/SmartThings, 3000LM,2700-6500K,Waterproof,Dusk to Dawn Flood Light with APP Control Perfect for Yard,Exterio(Black)
 
 https://www.amazon.com/gp/product/B09BZ24H17/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
 
[device.txt](https://github.com/0x5e/homebridge-tuya-platform/files/9973341/device.txt)

 Please refer to the troubleshooting section to get device list info. https://github.com/0x5e/homebridge-tuya-platform#troubleshooting

**Comment by 0x5e** [comment]
Can we treat sensor light as a normal light? Currently code reuse acrossing accessories still need to improve, I need to copy code from Motion sensor to any accessory which need motion features.

**Comment by 0x5e** [comment]
Added in beta.29
