### ISSUE TITLE
Plugin not creating ./persist subfolder

### ISSUE THREAD

**Issue by travisnerd** [0x5e/homebridge-tuya-platform#67]
Following a fresh install of this plugin v1.6.0-beta-28 on HOOBS v4.2.3 installed on a Raspberry Pi 4, having the Tuya IoT platform cloud project and authorizations in place, the plugin was throwing the following error for the configuration file:

`WARNING unhandled rejection: Error: ENOENT: no such file or directory, open /var/lib/hoobs/tuyaplatformbridge/persist/TuyaDeviceList.az164[...]GIQh.json`

As such, the device list file was unable to be written and my smart switches were not populating in HOOBS.

The resolution to this was to simply create the directory:
`sudo mkdir /var/lib/hoobs/tuyaplatformbridge/persist`

In this instance, I have the TuyaPlatform plugin installed as a separate bridge which may have impacted permissions during plugin setup.

**Comment by 0x5e** [comment]
Ok I will create the folder before file creation.

**Comment by 0x5e** [comment]
Fixed in beta.29
