### ISSUE TITLE
Add inching button for switches

### ISSUE THREAD

**Issue by FrAcTi0N** [0x5e/homebridge-tuya-platform#78]
**Is your feature request related to a problem? Please describe:**
Some switches contains an inching feature. You basically set, when the switch turns off after you turned it on (1 minute, 2 minutes ...). The problem is, that i am unable to turn this feature on/off in homekit. To do that, you need to open tuya app, which is ok for me, but not ok for the rest of my family.

**Describe the solution you'd like:**
Add 1 more button, that will turn on/off inching. The same way as the backlight button is done.

When inching button switched on, the main switch automatically turns off after the time i specified in tuya app. When inching button is switched off, the main switch remains turned on until i manually turn it off.

**Describe alternatives you've considered:**
An alternative is to use dummy switches, but this solution is not reliable...

**Additional context:**
![IMG_D095C8760E57-1](https://user-images.githubusercontent.com/26749550/201684791-28b10699-817a-468c-b590-274aa1b3ec54.jpeg)

TY

**Comment by 0x5e** [comment]
thanks for the feedback, can you upload the device info and tell me which schema code it is? I've never seen it before.

**Comment by FrAcTi0N** [comment]
To be honest, i can't find anything about inching in device info. I have tried to search the web and i just came into these sites... https://developer.tuya.com/en/docs/iot-device-dev/Jog-switch-Wi-Fi?id=Kaung27s713rc and https://iot.tuya.com/cloud/setMode?id=p1667381675915r3muuj&pid=vxo9yezswiumvync. But it has to work somehow.) For the device info, can you tell me, which info in tuya cloud api explorer is best for you? Or if there is any better way, please tel me how. TY

**Comment by 0x5e** [comment]
please see readme troubleshooting section.

**Comment by FrAcTi0N** [comment]
`[
  {
    "active_time": 1668365199,
    "biz_type": 0,
    "category": "kg",
    "create_time": 1667314432,
    "icon": "smart/icon/bay1595250271099fQze/438ab299500d4da49548540ac5bae547.png",
    "id": "bf3f34f9e68797dd996mlh",

    "model": "K2-01",
    "name": "Bathroom",
    "online": true,
    "owner_id": "69789387",
    "product_id": "vxo9yezswiumvync",
    "product_name": "1-Gang_WiFI",
    "status": [
      {
        "code": "switch_1",
        "value": true
      },
      {
        "code": "countdown_1",
        "value": 0
      },
      {
        "code": "relay_status",
        "value": "power_off"
      },
      {
        "code": "switch_backlight",
        "value": true
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "eu166731409331243PiB",
    "update_time": 1668365199,
    "uuid": "23a7afeb554571ee",
    "schema": [
      {
        "code": "switch_1",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "countdown_1",
        "mode": "rw",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "property": {
          "unit": "s",
          "min": 0,
          "max": 86400,
          "scale": 0,
          "step": 1
        }
      },
      {
        "code": "relay_status",
        "mode": "rw",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}",
        "property": {
          "range": [
            "power_off",
            "power_on",
            "last"
          ]
        }
      }
    ] 
  }
]`

**Comment by FrAcTi0N** [comment]
Ok, anyway thank You. I will monitor it and if they add it to the schema, i will let you know.

**Comment by FrAcTi0N** [comment]
Hi @0x5e it seems that inching appeared in the schema of the switch. Can you look into it?`data = {
  "result": {
    "category": "kg",
    "functions": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "switch_backlight",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "switch_backlight",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "type": "String",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1683574494499,

}`

**Comment by 0x5e** [comment]
> Hi @0x5e it seems that inching appeared in the schema of the switch. Can you look into it?`data = {
> 
>   "result": {
> 
>     "category": "kg",
> 
>     "functions": [
> 
>       {
> 
>         "code": "switch_1",
> 
>         "type": "Boolean",
> 
>         "values": "{}"
> 
>       },
> 
>       {
> 
>         "code": "countdown_1",
> 
>         "type": "Integer",
> 
>         "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
> 
>       },
> 
>       {
> 
>         "code": "relay_status",
> 
>         "type": "Enum",
> 
>         "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
> 
>       },
> 
>       {
> 
>         "code": "switch_backlight",
> 
>         "type": "Boolean",
> 
>         "values": "{}"
> 
>       },
> 
>       {
> 
>         "code": "switch_inching",
> 
>         "type": "String",
> 
>         "values": "{}"
> 
>       }
> 
>     ],
> 
>     "status": [
> 
>       {
> 
>         "code": "switch_1",
> 
>         "type": "Boolean",
> 
>         "values": "{}"
> 
>       },
> 
>       {
> 
>         "code": "countdown_1",
> 
>         "type": "Integer",
> 
>         "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
> 
>       },
> 
>       {
> 
>         "code": "relay_status",
> 
>         "type": "Enum",
> 
>         "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
> 
>       },
> 
>       {
> 
>         "code": "switch_backlight",
> 
>         "type": "Boolean",
> 
>         "values": "{}"
> 
>       },
> 
>       {
> 
>         "code": "switch_inching",
> 
>         "type": "String",
> 
>         "values": "{}"
> 
>       }
> 
>     ]
> 
>   },
> 
>   "success": true,
> 
>   "t": 1683574494499,
> 
> 
> 
> }`

the type should be boolean. string type is not supported. whay did you do? changed the control mode?

**Comment by FrAcTi0N** [comment]
> 
according to https://developer.tuya.com/en/docs/iot-device-dev/Jog-switch-Wi-Fi?id=Kaung27s713rc it uses 64base encoding.. 
examples:
turn inching off:
{
  "commands": [
    {
      "code": "switch_inching",
      "value": "AAOE"
    }
  ]
}

set inching for 15 minutes
{
  "commands": [
    {
      "code": "switch_inching",
      "value": "AQOE"
    }
  ]
}

set inching for 30 minutes

{
  "commands": [
    {
      "code": "switch_inching",
      "value": "AQcI"
    }
  ]
}
....

**Comment by 0x5e** [comment]
'AAOE' (off) -> '\x00\x03\x84'
'AQOE' (15min) -> '\x01\x03\x84'
'AQcI' (30min) -> '\x01\x07\x08'

I guess the first byte 01/00 means on/off, the last two bytes means time?

**Comment by FrAcTi0N** [comment]
yes, exactly 1st byte enable/disable inching, second 2 bytes represents time in seconds

**Comment by FrAcTi0N** [comment]
Confirming that i can see switch inching button for 1 button switch. Not sure if its possible to be able to change the inching time, but i dont see anything about it. Also i am missing switch inching for switches with more than 1 button. Inching is available just for the first button on the switch. But anyway, Thank you for implementing it.

**Comment by 0x5e** [comment]
changing time is not supported by homekit.
what's the dp codes of your multiple button switch? the logs you posted above seems only have one button.

**Comment by FrAcTi0N** [comment]
I ma unable to find DP instructions set for buttons, can you point me just a little please?

**Comment by 0x5e** [comment]
just like what you did previously, https://github.com/0x5e/homebridge-tuya-platform/issues/78#issuecomment-1314047554
I want to confirm the inching dp code of your multiple button switch

**Comment by FrAcTi0N** [comment]
`{
  "result": {
    "category": "kg",
    "functions": [
      {
        "code": "switch_1",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch 2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 2",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "lang_config": {
          "last": "Keep as last status",
          "power_off": "OFF",
          "power_on": "ON"
        },
        "name": "Restart status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "switch_backlight",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "backlight switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "lang_config": {
          "unit": ""
        },
        "name": "Switch inching",
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch 2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 2",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "lang_config": {
          "last": "Keep as last status",
          "power_off": "OFF",
          "power_on": "ON"
        },
        "name": "Restart status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "switch_backlight",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "backlight switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "lang_config": {
          "unit": ""
        },
        "name": "Switch inching",
        "type": "String",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1684158733543,
  "tid": "b20ab7ccf32711ed9b213e97a7ff9260"
}`
Is this enough?

**Comment by 0x5e** [comment]
I see `switch_1` and `switch_2`, but only see one `switch_inching`. where is the secound one?

**Comment by FrAcTi0N** [comment]
looks like that inching for both buttons is set with the same dp. But first 4 bytes are for button 2, last 4 bytes for button 1...
    {
      "code": "switch_inching",
      "value": "AwOEAQEs"
    }


AwOE --> 2nd button
AQEs --> 1st button

**Comment by FrAcTi0N** [comment]
well, i was testing different states.
1st byte and 5th byte always stay A
2nd byte has 2 states (w or g) - w = second button inching on, g = second button inching off
6th byte has 2 states (Q or A) - Q = first button inching on, A = first button inching off
byte 3 and 4 - time for button 2
byte 7 and 8 - time for button 1

here are states (upper row always for button 1, lower row for button 2)
on 15
on 15
AwOEAQOE

off 15
on 15
AwOEAAOE

off 15
off 15
AgOEAAOE

on 5
off 15
AgOEAQEs

on 5
on 5
AwEsAQEs

**Comment by 0x5e** [comment]
I think we should decode the base64 string before guess it's meaning (that's not a big problem), but the problem is, if the value of `switch_inching` contains multiple buttons, only support one button and two buttons are not enough, how about 3/4/5/6 buttons?
