### ISSUE TITLE
Smoke Sensor OK but no notification/update status

### ISSUE THREAD

**Issue by GotierLdl** [0x5e/homebridge-tuya-platform#83]
Hello,

I have 2 smoke detectors. The plugin goes back to me well these last but I have a problem. 
When I press the test button, I do have a report in the logs but no change in HomeKit. (Notifications via Tuya App is OK)

logs : 

`[15/11/2022 20:27:56] [@0x5e/homebridge-tuya-platform] [TuyaDeviceManager] Unhandled mqtt message: bizCode = online, bizData = { time: 1668540476 }`

**Comment by 0x5e** [comment]
Hi, please refer to the troubleshooting section to get device list info and debug logs. https://github.com/0x5e/homebridge-tuya-platform#troubleshooting

**Comment by GotierLdl** [comment]
Thanks but the path ~/.homebridge/persist/ doesn't exist

The device is : 
- LSC Smoke Detector (WiFi) 
- Product Category : ywbj

DP Instruction | Standard Instruction

Code | Type | Values
smoke_sensor_state | enum | "Active"
fault | bitmap  | "0","1"
battery_state | enum | "range":  "low","middle","high"

**Comment by 0x5e** [comment]
The specific path can be found in your homebridge log, I'm not sure what your path is, and for the mqtt log, please enable the homebridge debug mode, otherwise we can't see the incoming message.

The message `online` is useless we can just ignore it :)

**Comment by GotierLdl** [comment]
ok i'll take care of that when i get home from work

**Comment by 0x5e** [comment]
I only have virtual device so it may have different behavior or different schemas with yours, thanks for the informations!

**Comment by GotierLdl** [comment]
```
 {
    "active_time": 1668530869,
    "biz_type": 0,
    "category": "ywbj",
    "create_time": 1668528540,
    "icon": "smart/icon/ay1541056239985fDGjj/a1d1460f5a071a3412cc0c4659fc9756.png",
    "id": "32303682c45bbef51e91",
    "ip": "xx.xxx.xxx.xx",
    "lat": "", => empty
    "local_key": "xxxxxxxxxxxxxxxxxxx",
    "lon": "", => empty
    "model": "PD-8912",
    "name": "Détecteur de fumée RDC",
    "online": true,
    "owner_id": "71124810",
    "product_id": "cjlutkuuvxnie17o",
    "product_name": "Smoke Alarm",
    "status": [
      {
        "code": "battery_state",
        "value": "high"
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "xxxxxxxxxxxxxxxxxxxxxx",
    "update_time": 1668537974,
    "uuid": "32303682c45bbef51e91",
    "schema": [
      {
        "code": "battery_state",
        "mode": "ro",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}",
        "property": {
          "range": [
            "low",
            "middle",
            "high"
          ]
        }
      }
    ]
  }
```

**Comment by GotierLdl** [comment]
the log is here ;) 
[homebridge.log_tuya.txt](https://github.com/0x5e/homebridge-tuya-platform/files/10024304/homebridge.log_tuya.txt)


All info is ok but no reaction on Homekit

**Comment by 0x5e** [comment]
The problem is, your device's `schema` only have `battery_state`, some non-standard schema was hidden by the API.
https://github.com/0x5e/homebridge-tuya-platform/issues/44#issuecomment-1305353363

Your device are not able to supported at current, but still have hope. I will update the document later, about how to solve this. And it need a big modification with the plugin.

**Comment by 0x5e** [comment]
I open a new issue, this one will be closed.
#111

**Comment by GotierLdl** [comment]
The update v1.6.0-beta.40 résolve this issue THX !!

**Comment by arturlukosek** [comment]
Is there any additional requirements to get the smoke sensor working in homekit? Just bought one and it shows up in home as unsupported device.
 Product Category: ywbj

**Comment by 0x5e** [comment]
@arturlukosek Please see #111, current there's only one action you can try: switch device control modes into "dp instruction". If still not work, please wait the 1.7.0
