### ISSUE TITLE
Add support for SUNTEC DryFix Select 16 App

### ISSUE THREAD

**Issue by MrBrownFromLa** [0x5e/homebridge-tuya-platform#86]
Hello,
Could you add the SUNTEC DryFix Select 16 App dehumidifier?
Thanks for this great plugin!
Here are the Device info from TuyaDeviceList.{uid}.json

>  {
    "active_time": 1668353407,
    "biz_type": 18,
    "category": "cs",
    "create_time": 1663176969,
    "icon": "smart/icon/bay1613141165751aiAr/4088350eab5946eb4246eac89323e5dd.png",
    "id": "10737113e868e7f074da",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "16356",
    "name": "DryFix 16 Select App ",
    "online": true,
    "owner_id": "",
    "product_id": "qhxmvae667uap4zh",
    "product_name": "",
    "status": [
      {
        "code": "fault",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "",
    "update_time": 1668353407,
    "uuid": "10737113e868e7f074da",
    "schema": [
      {
        "code": "fault",
        "mode": "ro",
        "type": "Bitmap",
        "values": "{\"label\":[\"E1\",\"E2\"]}",
        "property": {
          "label": [
            "E1",
            "E2"
          ]
        }
      }
    ]
  }
]

**Comment by MrBrownFromLa** [comment]
That's great!
I'll wait patiently ^^ 
Tell me if you need some logs or anything.

**Comment by 0x5e** [comment]
It's supported, please try :)

**Comment by 0x5e** [comment]
Supported in 1.7.0-beta.5, please see the latest readme and advance configs.

**Comment by MrBrownFromLa** [comment]
Last update broke it ... could you help me?

[DryFix 16 Select App ] Existing schema: [
  { code: 'Power', mode: 'rw', type: 'Boolean', property: {} },
  { code: 'SLEEP', mode: 'rw', type: 'Boolean', property: {} },
  {
    code: 'countdown',
    mode: 'rw',
    type: 'Enum',
    property: {
      range: [
        '0',  '1',          '2',
        '3',  '4',          '5',
        '6',  '7',          '8',
        '9',  '10',         '11',
        '12', '13',         '14',
        '15', '16',         '17',
        '18', '19',         '20',
        '21', '22',         '23',
        '24', [length]: 25
      ]
    }
  },
  {
    code: 'fault',
    mode: 'ro',
    type: 'Bitmap',
    property: { label: [ '0', '1', '2', '3', [length]: 4 ], maxlen: 4 }
  },
  {
    code: 'get_hum',
    mode: 'ro',
    type: 'Integer',
    property: { unit: '%', min: 0, max: 99, scale: 0, step: 1 }
  },
  {
    code: 'get_temp',
    mode: 'ro',
    type: 'Integer',
    property: { unit: '℃', min: 0, max: 99, scale: 0, step: 1 }
  },
  { code: 'hs', mode: 'ro', type: 'Boolean', property: {} },
  {
    code: 'humidity',
    mode: 'rw',
    type: 'Integer',
    property: { unit: '％', min: 30, max: 80, scale: 0, step: 5 }
  },
  { code: 'lock', mode: 'rw', type: 'Boolean', property: {} },
  {
    code: 'mode',
    mode: 'rw',
    type: 'Enum',
    property: { range: [ '0', '1', '2', '3', [length]: 4 ] }
  },
  { code: 'time', mode: 'rw', type: 'Boolean', property: {} },
  {
    code: 'windspeed',
    mode: 'rw',
    type: 'Enum',
    property: { range: [ '1', '3', [length]: 2 ] }
  },
  [length]: 12
]
[14/02/2023 21:07:45] [@0x5e/homebridge-tuya-platform] Unsupported device: DryFix 16 Select App .

**Comment by 0x5e** [comment]
there's a breaking change on advanced options, sorry for the inconvience, `oldCode` `code` has renamed to `code` `newCode`, see latest docs.
