### ISSUE TITLE
Request to add fan rotation direction

### ISSUE THREAD

**Issue by r2shyyou** [0x5e/homebridge-tuya-platform#93]
Hi there,

I would like to request to add fan rotation direction as well as a toggle to change the direction (for a ceiling fan). And also to be able to select different HomeKit icons, or at least be able to use the ceiling fan icon, if possible.

Thanks!

**Comment by 0x5e** [comment]
Hi @r2shyyou , thanks for the feedback.
The icon is not controled by the plugin, it is provided by HomeKit App itself. I see the Switch Accessory have options in HomeKit to change the device type as light/fan/switch, then the icon can be changed. But unfortunately Fan Accessory doesn't have this feature 🤔.

OK the rotation direction will be added these days, could you please provide your device's informations? Please refer to https://github.com/0x5e/homebridge-tuya-platform#troubleshooting and upload your device info json, so I can confirm the function can works on your device.

**Comment by r2shyyou** [comment]
Thanks for the quick response. If the Switch Accessory has options in HomeKit to change the device type to light/fan/switch, the perhaps it would be best (more flexible) to change the Fan part of the plugin to register as a Switch Accessory, since it still includes fan as an option.

Regardless, as requested, attached is the device info json.
[TuyaDeviceList.eu1668598294535ekMby.txt](https://github.com/0x5e/homebridge-tuya-platform/files/10039460/TuyaDeviceList.eu1668598294535ekMby.txt)

**Comment by 0x5e** [comment]
Yes I will add override config option to let users choose the device type in 1.7.0. It's implementation will be a bit complicated.
But there is another problem, if you change your fan device into Switch Accessory, it will lose fan speed, only power on/off left. :(

**Comment by 0x5e** [comment]
Please try beta.34

**Comment by r2shyyou** [comment]
Rotation works perfectly, thanks!! The speed seems funky though. Doesn't seem to work right. That might be that my fan has a 0-6 scale, while Home.app shows a 0-100 scale.

**Comment by 0x5e** [comment]
This can be supported. I will remap 0-6 into 0-100 then it should work.

**Comment by r2shyyou** [comment]
it's working perfectly, thank you! great work!

**Comment by mitch7391** [comment]
@r2shyyou I was wondering if you might be able to share how you were able to configure the Rotation Direction characteristic? I am not quite sure where to get started on this one...

**Comment by r2shyyou** [comment]
> @r2shyyou I was wondering if you might be able to share how you were able to configure the Rotation Direction characteristic? I am not quite sure where to get started on this one...

if you're referring to configuration within the plugin itself, note that i am not the plugin developer so unfortunately i can't advise on that

**Comment by mitch7391** [comment]
@r2shyyou I do not mean within the plug-in itself sorry. It sounds like you had got this working for yourself, when setting up your device did you have to do anything extra in the Homebridge config for this plug-in (the device setup you put in the popup box) or did it just already appear with RotationDirection?

**Comment by r2shyyou** [comment]
> @r2shyyou I do not mean within the plug-in itself sorry. It sounds like you had got this working for yourself, when setting up your device did you have to do anything extra in the Homebridge config for this plug-in (the device setup you put in the popup box) or did it just already appear with RotationDirection?

i see. no, i did not have to do anything extra. rotation direction is part of the native functionality of the fan itself and also shows up in the device debugging section of the Tuya website

**Comment by mitch7391** [comment]
Bugger, yeah my Fan appears in HomeKit without it but in the Tuya app it is there. I will have to do some further digging when I can find the time. Thanks for the info!

**Comment by r2shyyou** [comment]
> Bugger, yeah my Fan appears in HomeKit without it but in the Tuya app it is there. I will have to do some further digging when I can find the time. Thanks for the info!

i should clarify that while i didn't have to do anything extra in the config, i did have to ask the developer to add the functionality (see first posts in this thread). maybe you have to do something similar?

**Comment by mitch7391** [comment]
I would say prior to your situation this plug-in could not expose the characteristic, the developer then added the ability. From what I can see in the readme is that I need to set up “Non-Standard DP” to be able to use it, but have no idea how to do it and was hoping you did it haha… It sounds like you were luckier than me and it just worked for you without having to do that…

**Comment by r2shyyou** [comment]
> I would say prior to your situation this plug-in could not expose the characteristic, the developer then added the ability. From what I can see in the readme is that I need to set up “Non-Standard DP” to be able to use it, but have no idea how to do it and was hoping you did it haha… It sounds like you were luckier than me and it just worked for you without having to do that…

i actually do have a non-standard DP device, in addition to 2 standard DP devices. i just followed the instructions in the readme. one important thing is to make sure you select the right data center.
