### ISSUE TITLE
Error when turning light on/off

### ISSUE THREAD

**Issue by Konstix08** [0x5e/homebridge-tuya-platform#96]
[@0x5e/homebridge-tuya-platform] This plugin threw an error from the characteristic 'Brightness': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'property'). See https://homebridge.io/w/JtMGR for more info.

**Comment by Konstix08** [comment]
But i think all works as expected.

**Comment by 0x5e** [comment]
Thanks for the feedback, I will modify the code later, to ensure the values won't over the range.

**Comment by Konstix08** [comment]
I don't know if it is related to the other error but when i try to control a RGB Strip the homebridge crashes with this error:

`
[11/19/2022, 12:32:24 PM] [@0x5e/homebridge-tuya-platform] This plugin threw an error from the characteristic 'Brightness': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'property'). See https://homebridge.io/w/JtMGR for more info.
[11/19/2022, 12:32:28 PM] [@0x5e/homebridge-tuya-platform] This plugin threw an error from the characteristic 'Brightness': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'property'). See https://homebridge.io/w/JtMGR for more info.
[11/19/2022, 12:32:28 PM] [@0x5e/homebridge-tuya-platform] This plugin threw an error from the characteristic 'Brightness': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'property'). See https://homebridge.io/w/JtMGR for more info.
[11/19/2022, 12:32:30 PM] [@0x5e/homebridge-tuya-platform] This plugin threw an error from the characteristic 'Brightness': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'property'). See https://homebridge.io/w/JtMGR for more info.
TypeError: Cannot read properties of undefined (reading 'property')
    at /var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/LightAccessory.ts:189:32
    at LightAccessory.onDeviceStatusUpdate (/var/lib/homebridge/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/BaseAccessory.ts:168:46)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/19/2022, 12:32:31 PM] [@0x5e/homebridge-tuya-platform] Child bridge process ended`

**Comment by 0x5e** [comment]
I think your device is missing some schema. Can you follow the readme troubleshooting section and upload your device info json?

**Comment by Konstix08** [comment]
Unfortunately the error persists. I will troubleshoot my device later. Thanks for your effort! :)

**Comment by Konstix08** [comment]
Here is the json file from the device. I hope it helps.
`{
    "active_time": 1668780129,
    "biz_type": 0,
    "category": "dd",
    "create_time": 1668780129,
    "model": "",
    "name": "LZB1_1st 双模音乐幻彩灯带 2",
    "online": true,
    "product_id": "ffwyeij5r4tdpel2",
    "product_name": "Magic striplight ",
    "status": [
      {
        "code": "switch_led",
        "value": false
      },
      {
        "code": "work_mode",
        "value": "dynamic_mod"
      },
      {
        "code": "colour_data",
        "value": "{\"h\":0,\"s\":0,\"v\":1000}"
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "update_time": 1668859170,
    "schema": [
      {
        "code": "switch_led",
        "mode": "rw",
        "type": "Boolean",
        "values": "{}",
        "property": {}
      },
      {
        "code": "work_mode",
        "mode": "rw",
        "type": "Enum",
        "values": "{\"range\":[\"music\"]}",
        "property": {
          "range": [
            "music"
          ]
        }
      },
      {
        "code": "colour_data",
        "mode": "rw",
        "type": "Json",
        "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}",
        "property": {
          "h": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 360,
            "step": 1
          },
          "s": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 1000,
            "step": 1
          },
          "v": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 1000,
            "step": 1
          }
        }
      },
      {
        "code": "control_data",
        "mode": "wo",
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\$
        "property": {
          "change_mode": {
            "range": [
              "direct",
              "gradient"
            ]
          },
          "bright": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 1000,
            "step": 1
          },
          "temperature": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 1000,
            "step": 1
          },
          "h": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 360,
            "step": 1
          },
          "s": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 255,
            "step": 1
          },
          "v": {
            "min": 0,
            "scale": 0,
            "unit": "",
            "max": 255,
            "step": 1
          }
        }
      }
    ]
  }`

**Comment by 0x5e** [comment]
Thanks for the information. Your device don't have `brightness_value` code.
Now the logic is:
- If the device is in color mode (`work_mode=colour`), plugin will read and write brightness from `colour_data.v`
- Else (`work_mode=white`), plugin will read and write brightness from `brightness_value`

You are not in `colour` and `white` modes so the logic is wrong.
For the varites of other modes `scene`, `music`, `sleep`... I don't know how to handle them properly because they are too much. I will just ignore the brightness read & write when lights are not in `color` and `white` modes.

**Comment by Konstix08** [comment]
Thank you it now works fine.

**Comment by 0x5e** [comment]
Thanks for spend time testing too.

**Comment by Konstix08** [comment]
I don't if it's known but when i try to change the color i need to adjust the brightness in homekit obly after changing brightness the color will be updated.

**Comment by 0x5e** [comment]
sorry I'm not clearly understand that?

**Comment by Konstix08** [comment]
So when i want to change the color of my led strip i need to adjust the brightness. Only after changing the brightness the device changes the color.

**Comment by 0x5e** [comment]
Can you run homebridge in debug mode and provide some logs? It looks like a bug.

**Comment by Konstix08** [comment]
Sure i will run homebridge in debug mode when i am at home.
