### ISSUE TITLE
Support for scene switch (cjkg)

### ISSUE THREAD

**Issue by Konstix08** [0x5e/homebridge-tuya-platform#99]
It would be great if you can add support for a scene switch. In home it could appear as a normal switch.

**Comment by 0x5e** [comment]
Sure. It's in the todo list now.

**Comment by 0x5e** [comment]
The issue about scene switch is that they are stateless. They don't have on and off. So I have to create a on/off switch and force the state to 'off'. When user turn it on, fire a command and automatically turn it of. User experience may not very good but it works.

**Comment by 0x5e** [comment]
So you have the wxkg instead of cjkg ? If anyone have the cjkg, please upload some informations then I can submit a version to test.

**Comment by Konstix08** [comment]
Yes, sorry for the mistake.

**Comment by 0x5e** [comment]
It's supported now, tested with only virtual device. If anyone works
